// EvidenceGraphPanel.jsx — AI output provenance panel.
// Renders the EvidenceGraph attached to every AI answer:
//   • Sources used (what real data the AI saw)
//   • Claims with per-claim confidence bars
//   • Conflicting signals (counter-evidence shown honestly)
//   • Why this recommendation
//   • What would falsify this diagnosis
//
// Used in ExplanationPanel and CopilotPanel — same component, same contract.

const CONF_COLOR = (c) => c >= 70 ? "#34d399" : c >= 40 ? "#f59e0b" : "#ef4444";
const CONF_BG    = (c) => c >= 70 ? "rgba(52,211,153,0.10)" : c >= 40 ? "rgba(245,158,11,0.09)" : "rgba(239,68,68,0.09)";
const CONF_BORDER= (c) => c >= 70 ? "rgba(52,211,153,0.28)" : c >= 40 ? "rgba(245,158,11,0.25)" : "rgba(239,68,68,0.25)";

const SOURCE_ICON = {
  event:    { icon: "🔔", color: "#f87171" },
  log:      { icon: "📋", color: "#94a3b8" },
  metric:   { icon: "📈", color: "#38bdf8" },
  change:   { icon: "🚀", color: "#a78bfa" },
  trace:    { icon: "🔍", color: "#fb923c" },
  topology: { icon: "🕸️", color: "#34d399" },
};

const METHOD_LABEL = {
  llm:        { label: "LLM-powered",  color: "#a78bfa", title: "Claims generated by AI and grounded in evidence" },
  rule_based: { label: "Rule-based",   color: "#38bdf8", title: "Claims derived deterministically from incident data" },
  hybrid:     { label: "Hybrid",       color: "#34d399", title: "AI summary with rule-based evidence graph" },
};

// ─── Sub-components ───────────────────────────────────────────────────────────

function ConfBar({ value, width = 56 }) {
  const pct = Math.min(100, Math.max(0, value || 0));
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
      <div style={{ width, height: 4, borderRadius: 2, background: "rgba(255,255,255,0.07)", flexShrink: 0 }}>
        <div style={{ width: `${pct}%`, height: "100%", borderRadius: 2, background: CONF_COLOR(pct), transition: "width 0.3s" }} />
      </div>
      <span style={{ fontSize: "0.7rem", fontWeight: 700, color: CONF_COLOR(pct), minWidth: 28 }}>{pct}%</span>
    </div>
  );
}

function SourcesSection({ sources }) {
  if (!sources || sources.length === 0) return null;
  return (
    <div style={{ marginBottom: 18 }}>
      <div style={{ fontSize: "0.65rem", color: "#64748b", textTransform: "uppercase", letterSpacing: "0.08em", fontWeight: 700, marginBottom: 8 }}>
        EVIDENCE SOURCES USED ({sources.length})
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
        {sources.map((src, i) => {
          const cfg = SOURCE_ICON[src.type] || { icon: "📄", color: "#94a3b8" };
          return (
            <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 8, padding: "6px 10px", borderRadius: 7, background: "rgba(255,255,255,0.025)", border: "1px solid rgba(90,123,186,0.10)" }}>
              <span style={{ fontSize: "0.8rem", flexShrink: 0, marginTop: 1 }}>{cfg.icon}</span>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: "0.75rem", color: cfg.color, fontWeight: 600, truncate: "ellipsis" }}>{src.label}</div>
                {src.detail && <div style={{ fontSize: "0.68rem", color: "#475569", marginTop: 1 }}>{src.detail}</div>}
              </div>
              <span style={{ fontSize: "0.6rem", color: "#475569", flexShrink: 0, marginTop: 2 }}>{src.type}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function ClaimsSection({ claims }) {
  if (!claims || claims.length === 0) return null;
  return (
    <div style={{ marginBottom: 18 }}>
      <div style={{ fontSize: "0.65rem", color: "#64748b", textTransform: "uppercase", letterSpacing: "0.08em", fontWeight: 700, marginBottom: 8 }}>
        CLAIMS & CONFIDENCE
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        {claims.map((c, i) => (
          <div key={i} style={{
            padding: "10px 14px", borderRadius: 10,
            background: CONF_BG(c.confidence),
            border: `1px solid ${CONF_BORDER(c.confidence)}`,
          }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 10, marginBottom: 6 }}>
              <div style={{ flex: 1, fontSize: "0.82rem", color: "#e2e8f0", fontWeight: 600, lineHeight: 1.4 }}>{c.claim}</div>
              <ConfBar value={c.confidence} />
            </div>

            {/* Why */}
            {c.reasoning && (
              <div style={{ marginBottom: 6 }}>
                <span style={{ fontSize: "0.62rem", color: "#38bdf8", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em" }}>Why: </span>
                <span style={{ fontSize: "0.73rem", color: "#94a3b8" }}>{c.reasoning}</span>
              </div>
            )}

            {/* Falsification */}
            {c.falsified_by && (
              <div style={{ padding: "5px 8px", borderRadius: 6, background: "rgba(248,113,113,0.06)", border: "1px solid rgba(248,113,113,0.18)" }}>
                <span style={{ fontSize: "0.62rem", color: "#f87171", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em" }}>Falsified by: </span>
                <span style={{ fontSize: "0.71rem", color: "#94a3b8", fontStyle: "italic" }}>{c.falsified_by}</span>
              </div>
            )}

            {/* Evidence refs for this claim */}
            {c.evidence_refs && c.evidence_refs.length > 0 && (
              <div style={{ marginTop: 6, display: "flex", flexWrap: "wrap", gap: 4 }}>
                {c.evidence_refs.map((ref, j) => {
                  const cfg = SOURCE_ICON[ref.type] || { icon: "📄", color: "#94a3b8" };
                  return (
                    <span key={j} style={{ fontSize: "0.62rem", padding: "1px 6px", borderRadius: 5, background: "rgba(255,255,255,0.05)", color: cfg.color, border: "1px solid rgba(255,255,255,0.07)" }}>
                      {cfg.icon} {ref.label || ref.id}
                    </span>
                  );
                })}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

function ConflictsSection({ conflicts }) {
  if (!conflicts || conflicts.length === 0) return null;
  return (
    <div style={{ marginBottom: 18 }}>
      <div style={{ fontSize: "0.65rem", color: "#64748b", textTransform: "uppercase", letterSpacing: "0.08em", fontWeight: 700, marginBottom: 8 }}>
        CONFLICTING SIGNALS ({conflicts.length})
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        {conflicts.map((cs, i) => (
          <div key={i} style={{ padding: "9px 12px", borderRadius: 9, background: "rgba(245,158,11,0.06)", border: "1px solid rgba(245,158,11,0.22)" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 4 }}>
              <div style={{ fontSize: "0.78rem", color: "#fbbf24", fontWeight: 600 }}>{cs.signal}</div>
              <div style={{ display: "flex", alignItems: "center", gap: 5, flexShrink: 0 }}>
                <div style={{ width: 40, height: 3, borderRadius: 2, background: "rgba(255,255,255,0.07)" }}>
                  <div style={{ width: `${cs.strength || 0}%`, height: "100%", borderRadius: 2, background: "#f59e0b" }} />
                </div>
                <span style={{ fontSize: "0.65rem", color: "#f59e0b", minWidth: 24 }}>{cs.strength || 0}%</span>
              </div>
            </div>
            {cs.resolution && (
              <div>
                <span style={{ fontSize: "0.62rem", color: "#34d399", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em" }}>Resolution: </span>
                <span style={{ fontSize: "0.71rem", color: "#64748b" }}>{cs.resolution}</span>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

function RecommendationSection({ rec }) {
  if (!rec) return null;
  return (
    <div style={{ marginBottom: 18 }}>
      <div style={{ fontSize: "0.65rem", color: "#64748b", textTransform: "uppercase", letterSpacing: "0.08em", fontWeight: 700, marginBottom: 8 }}>
        RECOMMENDATION
      </div>
      <div style={{ padding: "12px 14px", borderRadius: 10, background: "rgba(58,167,255,0.07)", border: "1px solid rgba(58,167,255,0.22)" }}>
        <div style={{ display: "flex", gap: 8, alignItems: "flex-start", marginBottom: 6, flexWrap: "wrap" }}>
          <div style={{ flex: 1, fontSize: "0.84rem", color: "#8fd3ff", fontWeight: 600 }}>{rec.action}</div>
          <div style={{ display: "flex", gap: 5, flexShrink: 0 }}>
            {rec.priority && (
              <span style={{
                fontSize: "0.6rem", padding: "1px 7px", borderRadius: 5, fontWeight: 700,
                background: rec.priority === "immediate" ? "rgba(239,68,68,0.15)" : rec.priority === "soon" ? "rgba(245,158,11,0.15)" : "rgba(100,116,139,0.15)",
                color:      rec.priority === "immediate" ? "#fca5a5"                : rec.priority === "soon" ? "#fbbf24"             : "#94a3b8",
              }}>
                {rec.priority.toUpperCase()}
              </span>
            )}
            {rec.risk_level && (
              <span style={{ fontSize: "0.6rem", padding: "1px 7px", borderRadius: 5, background: "rgba(255,255,255,0.05)", color: "#94a3b8" }}>
                {rec.risk_level} risk
              </span>
            )}
          </div>
        </div>
        {rec.why && (
          <div>
            <span style={{ fontSize: "0.62rem", color: "#38bdf8", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.06em" }}>Why this action: </span>
            <span style={{ fontSize: "0.72rem", color: "#64748b" }}>{rec.why}</span>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Main export ──────────────────────────────────────────────────────────────

export default function EvidenceGraphPanel({ graph, collapsed = false }) {
  if (!graph) return null;

  const method = METHOD_LABEL[graph.method] || METHOD_LABEL.rule_based;
  const hasSources    = graph.sources_used?.length > 0;
  const hasClaims     = graph.claims?.length > 0;
  const hasConflicts  = graph.conflicting_signals?.length > 0;
  const hasRec        = !!graph.recommendation;

  if (!hasSources && !hasClaims && !hasConflicts && !hasRec) return null;

  return (
    <div style={{ marginTop: 16, padding: "14px 16px", borderRadius: 12, background: "rgba(5,13,29,0.6)", border: "1px solid rgba(90,123,186,0.18)" }}>
      {/* Header row */}
      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14, flexWrap: "wrap" }}>
        <div style={{ fontSize: "0.65rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "#475569", fontWeight: 700 }}>
          EVIDENCE GRAPH
        </div>
        <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
          {/* Overall confidence pill */}
          <span style={{
            fontSize: "0.7rem", fontWeight: 800, padding: "2px 10px", borderRadius: 6,
            background: CONF_BG(graph.overall_confidence),
            border: `1px solid ${CONF_BORDER(graph.overall_confidence)}`,
            color: CONF_COLOR(graph.overall_confidence),
          }}>
            {graph.overall_confidence}% confidence
          </span>
          {/* Method badge */}
          <span title={method.title} style={{ fontSize: "0.62rem", padding: "1px 7px", borderRadius: 5, background: "rgba(255,255,255,0.04)", color: method.color, border: "1px solid rgba(255,255,255,0.07)", cursor: "help" }}>
            {method.label}
          </span>
        </div>
        {/* Mini stats */}
        <div style={{ marginLeft: "auto", display: "flex", gap: 10, fontSize: "0.65rem", color: "#475569" }}>
          {hasSources   && <span>{graph.sources_used.length} sources</span>}
          {hasClaims    && <span>{graph.claims.length} claims</span>}
          {hasConflicts && <span style={{ color: "#f59e0b" }}>{graph.conflicting_signals.length} conflicts</span>}
        </div>
      </div>

      {!collapsed && (
        <>
          <SourcesSection sources={graph.sources_used} />
          <ClaimsSection claims={graph.claims} />
          <ConflictsSection conflicts={graph.conflicting_signals} />
          <RecommendationSection rec={graph.recommendation} />
        </>
      )}
    </div>
  );
}
