// PostMortemPanel.jsx — Phase 2, Week 6
// LLM-generated post-mortem editor. Edits in 5 min, not 90.

import { useState, useEffect, useCallback } from "react";
import { getPostMortem, generatePostMortem, updatePostMortem } from "../api/postmortem.js";

export default function PostMortemPanel({ incidentID }) {
  const [pm, setPm] = useState(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [dirty, setDirty] = useState(false);

  // Editable fields
  const [title, setTitle] = useState("");
  const [executiveSummary, setExecutiveSummary] = useState("");
  const [timelineNarrative, setTimelineNarrative] = useState("");
  const [rootCause, setRootCause] = useState("");
  const [impact, setImpact] = useState("");
  const [resolution, setResolution] = useState("");
  const [actionItemsRaw, setActionItemsRaw] = useState(""); // newline-separated
  const [lessons, setLessons] = useState("");
  const [status, setStatus] = useState("draft");

  const loadPM = useCallback(async () => {
    if (!incidentID) return;
    setLoading(true);
    setError("");
    try {
      const data = await getPostMortem(incidentID);
      if (data) applyPM(data);
    } catch {
      // 404 means no post-mortem yet — that's fine
    } finally {
      setLoading(false);
    }
  }, [incidentID]);

  useEffect(() => {
    loadPM();
  }, [loadPM]);

  function applyPM(data) {
    setPm(data);
    setTitle(data.title || "");
    setExecutiveSummary(data.executive_summary || "");
    setTimelineNarrative(data.timeline_narrative || "");
    setRootCause(data.root_cause || "");
    setImpact(data.impact || "");
    setResolution(data.resolution || "");
    setActionItemsRaw((data.action_items || []).join("\n"));
    setLessons(data.lessons || "");
    setStatus(data.status || "draft");
    setDirty(false);
  }

  async function handleGenerate() {
    setGenerating(true);
    setError("");
    try {
      const data = await generatePostMortem(incidentID);
      applyPM(data);
    } catch (e) {
      setError("Failed to generate post-mortem: " + e.message);
    } finally {
      setGenerating(false);
    }
  }

  async function handleSave(nextStatus) {
    setSaving(true);
    setError("");
    try {
      const payload = {
        title,
        status: nextStatus || status,
        executive_summary: executiveSummary,
        timeline_narrative: timelineNarrative,
        root_cause: rootCause,
        impact,
        resolution,
        action_items: actionItemsRaw.split("\n").map(s => s.trim()).filter(Boolean),
        lessons,
      };
      const data = await updatePostMortem(incidentID, payload);
      applyPM(data);
    } catch (e) {
      setError("Failed to save: " + e.message);
    } finally {
      setSaving(false);
    }
  }

  function markDirty() { setDirty(true); }

  const statusColor = { draft: "#6b7280", review: "#f59e0b", published: "#10b981" };

  if (loading) {
    return <div className="lux-muted" style={{ padding: "1.5rem" }}>Loading post-mortem...</div>;
  }

  return (
    <div className="pm-root">
      {/* Header */}
      <div className="pm-header">
        <div>
          <div className="lux-eyebrow">POST-MORTEM</div>
          <h3 style={{ margin: 0 }}>{pm ? title || "Untitled Post-Mortem" : "No post-mortem yet"}</h3>
          {pm && (
            <div style={{ display: "flex", gap: "0.5rem", alignItems: "center", marginTop: "0.25rem" }}>
              <span className="lux-mini-chip" style={{ color: statusColor[status] }}>
                {status.toUpperCase()}
              </span>
              <span className="lux-muted" style={{ fontSize: "0.75rem" }}>
                Generated by {pm.generated_by || "LLM"} · Last saved {pm.updated_at ? new Date(pm.updated_at).toLocaleString() : "—"}
              </span>
            </div>
          )}
        </div>
        <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
          <button
            className="lux-secondary-btn"
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating ? "Generating..." : pm ? "Regenerate" : "Generate with AI"}
          </button>
          {pm && (
            <>
              <button
                className="lux-secondary-btn"
                onClick={() => handleSave("draft")}
                disabled={saving || !dirty}
              >
                {saving ? "Saving..." : "Save Draft"}
              </button>
              <button
                className="lux-secondary-btn"
                onClick={() => handleSave("review")}
                disabled={saving}
              >
                Send for Review
              </button>
              <button
                className="lux-primary-btn"
                onClick={() => handleSave("published")}
                disabled={saving}
              >
                Publish
              </button>
            </>
          )}
        </div>
      </div>

      {error && <div className="pm-error">{error}</div>}

      {!pm && !generating && (
        <div className="pm-empty">
          <div className="pm-empty-icon">📋</div>
          <p>No post-mortem exists for this incident.</p>
          <p className="lux-muted">Click "Generate with AI" to have the LLM draft one from the incident timeline and RCA in under a minute. Edit the fields and publish.</p>
          <button className="lux-primary-btn" onClick={handleGenerate} disabled={generating}>
            {generating ? "Generating..." : "Generate with AI"}
          </button>
        </div>
      )}

      {generating && (
        <div className="pm-empty">
          <div style={{ fontSize: "2rem" }}>🤖</div>
          <p>AI is analyzing the incident and writing your post-mortem...</p>
          <div className="lux-muted" style={{ fontSize: "0.8rem" }}>This usually takes 5–15 seconds</div>
        </div>
      )}

      {pm && !generating && (
        <div className="pm-body">
          {/* Title */}
          <div className="pm-field">
            <label className="pm-label">Title</label>
            <input
              className="pm-input"
              value={title}
              onChange={e => { setTitle(e.target.value); markDirty(); }}
              placeholder="Post-Mortem: Service — Date"
            />
          </div>

          {/* Executive Summary */}
          <div className="pm-field">
            <label className="pm-label">Executive Summary <span className="pm-hint">Customer-facing 2–3 sentences</span></label>
            <textarea
              className="pm-textarea"
              rows={3}
              value={executiveSummary}
              onChange={e => { setExecutiveSummary(e.target.value); markDirty(); }}
              placeholder="Brief description of what happened and business impact..."
            />
          </div>

          <div className="pm-two-grid">
            {/* Root Cause */}
            <div className="pm-field">
              <label className="pm-label">Root Cause</label>
              <textarea
                className="pm-textarea"
                rows={4}
                value={rootCause}
                onChange={e => { setRootCause(e.target.value); markDirty(); }}
                placeholder="Technical root cause explanation..."
              />
            </div>

            {/* Impact */}
            <div className="pm-field">
              <label className="pm-label">Impact</label>
              <textarea
                className="pm-textarea"
                rows={4}
                value={impact}
                onChange={e => { setImpact(e.target.value); markDirty(); }}
                placeholder="Who was affected, for how long, what was degraded..."
              />
            </div>
          </div>

          {/* Timeline Narrative */}
          <div className="pm-field">
            <label className="pm-label">Timeline Narrative</label>
            <textarea
              className="pm-textarea"
              rows={5}
              value={timelineNarrative}
              onChange={e => { setTimelineNarrative(e.target.value); markDirty(); }}
              placeholder="Chronological narrative of what happened and how the team responded..."
            />
          </div>

          {/* Resolution */}
          <div className="pm-field">
            <label className="pm-label">Resolution</label>
            <textarea
              className="pm-textarea"
              rows={3}
              value={resolution}
              onChange={e => { setResolution(e.target.value); markDirty(); }}
              placeholder="How the incident was resolved, steps taken..."
            />
          </div>

          <div className="pm-two-grid">
            {/* Action Items */}
            <div className="pm-field">
              <label className="pm-label">Action Items <span className="pm-hint">One per line</span></label>
              <textarea
                className="pm-textarea"
                rows={5}
                value={actionItemsRaw}
                onChange={e => { setActionItemsRaw(e.target.value); markDirty(); }}
                placeholder={"Add circuit breaker on payments-api DB pool\nAlert on connection pool saturation\nRunbook for DB failover..."}
              />
              <div className="pm-action-items-preview">
                {actionItemsRaw.split("\n").filter(Boolean).map((item, i) => (
                  <div key={i} className="pm-action-item">
                    <span className="pm-ai-num">{i + 1}</span>
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Lessons Learned */}
            <div className="pm-field">
              <label className="pm-label">Lessons Learned</label>
              <textarea
                className="pm-textarea"
                rows={5}
                value={lessons}
                onChange={e => { setLessons(e.target.value); markDirty(); }}
                placeholder="Key takeaways the team should remember going forward..."
              />
            </div>
          </div>

          {/* Status selector */}
          <div className="pm-field pm-status-row">
            <label className="pm-label">Status</label>
            <div style={{ display: "flex", gap: "0.5rem" }}>
              {["draft", "review", "published"].map(s => (
                <button
                  key={s}
                  className={status === s ? "lux-primary-btn small" : "lux-secondary-btn small"}
                  onClick={() => { setStatus(s); markDirty(); }}
                >
                  {s.charAt(0).toUpperCase() + s.slice(1)}
                </button>
              ))}
            </div>
          </div>

          {dirty && (
            <div className="pm-unsaved">
              Unsaved changes — click Save Draft or Publish
            </div>
          )}
        </div>
      )}
    </div>
  );
}
