ALTER TABLE incidents
ADD COLUMN IF NOT EXISTS confidence INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS risk_score INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS event_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS root_cause_summary TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS root_cause_type TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS reasoning_json TEXT NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS what_changed_type TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS what_changed_service TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS what_changed_version TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS what_changed_description TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS what_changed_timestamp TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS impacted_services_json TEXT NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS impact_count INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS changes (
    id SERIAL PRIMARY KEY,
    service TEXT NOT NULL,
    type TEXT NOT NULL,
    version TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    timestamp TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_changes_service_timestamp
ON changes (service, timestamp DESC);