ALTER TABLE incidents
ADD COLUMN IF NOT EXISTS correlation_pattern TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS correlation_score INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS correlation_reason TEXT NOT NULL DEFAULT '';
