package services

func buildJavaEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "java-heap-oom", Category: "application", SubCategory: "java",
			Keywords: []string{"outofmemoryerror", "java heap space", "java.lang.outofmemoryerror"},
			Severity: "critical",
			RootCause: "Java process ran out of heap memory — the JVM cannot allocate more objects",
			Reasoning: []string{
				"The JVM heap is full and garbage collection cannot free enough memory",
				"Common causes: memory leak, undersized heap, or loading too much data into memory",
				"The process will either crash or become unresponsive with constant GC",
			},
			Impact:          "Service crashes or hangs; requests fail; potential data loss from in-flight transactions",
			ResolutionSteps: []string{"Take heap dump before restart: jmap -dump:live,format=b,file=heap.hprof <PID>", "Increase heap size: -Xmx4g (double current value as temporary fix)", "Analyze heap dump with Eclipse MAT or VisualVM to find the leak", "Check for common leaks: unclosed connections, growing caches, static collections", "Restart the service as immediate mitigation"},
			Prevention:      "Set -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp; monitor heap usage trends; run leak detection in staging",
			BaseConfidence: 90, BaseRiskScore: 85,
		},
		{
			ID: "java-metaspace-oom", Category: "application", SubCategory: "java",
			Keywords: []string{"metaspace", "outofmemoryerror: metaspace", "permgen"},
			Severity: "critical",
			RootCause: "Java Metaspace (class metadata area) is exhausted, usually from classloader leaks",
			Reasoning: []string{
				"Metaspace grows when new classes are loaded; it does not shrink unless classloaders are GC'd",
				"Common in applications with hot-reloading, many dynamic proxies, or reflection-heavy frameworks",
				"Repeated deployments without full restart in app servers often cause this",
			},
			Impact:          "JVM crashes; no new classes can be loaded; application cannot process requests",
			ResolutionSteps: []string{"Increase Metaspace: -XX:MaxMetaspaceSize=512m", "Check classloader count: jcmd <PID> VM.classloaders", "For app servers (Tomcat): do a full restart instead of hot-deploy", "Profile class loading: -verbose:class to see what is loading classes", "Check for Groovy/scripting engines that generate classes dynamically"},
			Prevention:      "Set MaxMetaspaceSize explicitly; avoid hot-deploy in production; monitor Metaspace usage",
			BaseConfidence: 85, BaseRiskScore: 80,
		},
		{
			ID: "java-stackoverflow", Category: "application", SubCategory: "java",
			Keywords: []string{"stackoverflowerror", "stack overflow java", "java.lang.stackoverflowerror"},
			Severity: "high",
			RootCause: "Java thread exceeded its stack size due to deep or infinite recursion",
			Reasoning: []string{
				"Each method call adds a frame to the thread stack; infinite recursion exhausts it",
				"Default thread stack is 512KB-1MB, which handles ~5000-10000 frames",
				"Usually a bug in recursive algorithms without proper termination conditions",
			},
			Impact:          "The affected thread dies; if it is a request handler thread, that request fails",
			ResolutionSteps: []string{"Check the stack trace to find the recursive call cycle", "Fix the recursive algorithm to have a proper base case", "Convert deep recursion to iterative approach", "If legitimate deep recursion: increase stack size with -Xss2m", "Check for circular bean dependencies in Spring (common cause)"},
			Prevention:      "Code review recursive methods for termination conditions; limit recursion depth in algorithms",
			BaseConfidence: 80, BaseRiskScore: 60,
		},
		{
			ID: "java-nullpointer", Category: "application", SubCategory: "java",
			Keywords: []string{"nullpointerexception", "null pointer", "java.lang.nullpointerexception"},
			Severity: "high",
			RootCause: "NullPointerException — code attempted to use a null reference",
			Reasoning: []string{
				"A variable expected to hold an object reference is null",
				"Common causes: missing input validation, failed dependency injection, or race conditions",
				"The stack trace shows exactly where the null dereference occurred",
			},
			Impact:          "Request fails with 500 error; if in a critical path, all similar requests fail",
			ResolutionSteps: []string{"Read the stack trace to identify the exact line and variable that is null", "Check if the null comes from a database query returning no results", "Add null checks or use Optional<T> for values that can legitimately be absent", "Check if a Spring/DI bean failed to inject (look for @Autowired on the field)", "Deploy a fix or rollback to the previous version"},
			Prevention:      "Use @NonNull annotations; adopt Optional<T>; add null checks at service boundaries",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "java-classnotfound", Category: "application", SubCategory: "java",
			Keywords: []string{"classnotfoundexception", "classnotfounderror", "noclassdeffounderror"},
			Severity: "high",
			RootCause: "Java cannot find a required class at runtime — classpath issue or missing dependency",
			Reasoning: []string{
				"The class exists at compile time but is missing at runtime",
				"Common causes: missing JAR in deployment, version conflict, or shade/relocate issue",
				"NoClassDefFoundError specifically means the class was available at compile time but not at runtime",
			},
			Impact:          "Application fails to start or specific functionality breaks",
			ResolutionSteps: []string{"Check which class is missing from the exception message", "Verify the dependency is in the classpath: find /app -name '*.jar' | xargs grep -l <ClassName>", "Check for dependency conflicts: mvn dependency:tree or gradle dependencies", "Rebuild and redeploy the application with all dependencies", "Check if a transitive dependency was excluded in pom.xml/build.gradle"},
			Prevention:      "Use dependency management (BOM); run integration tests before deploy; use fat JARs for deployment",
			BaseConfidence: 80, BaseRiskScore: 65,
		},
		{
			ID: "java-connection-pool", Category: "application", SubCategory: "java",
			Keywords: []string{"connection pool exhausted", "pool exhausted", "hikaripool", "connection pool timeout"},
			Severity: "critical",
			RootCause: "Database connection pool is exhausted — all connections are in use and new requests cannot get a connection",
			Reasoning: []string{
				"All connections in the pool are checked out by active queries or leaked transactions",
				"Slow queries hold connections longer, reducing pool throughput",
				"Connection leaks (not closing connections) gradually exhaust the pool",
			},
			Impact:          "All database operations block; request queue grows; service becomes unresponsive",
			ResolutionSteps: []string{"Check pool metrics: look for HikariCP metrics in /actuator/metrics or JMX", "Identify long-running queries: SELECT pid, now() - pg_stat_activity.query_start AS duration, query FROM pg_stat_activity WHERE state != 'idle' ORDER BY duration DESC", "Increase pool size temporarily: spring.datasource.hikari.maximum-pool-size=20", "Fix connection leaks: ensure try-with-resources or @Transactional on all DB operations", "Kill long-running queries: SELECT pg_terminate_backend(<pid>)"},
			Prevention:      "Set connection pool leak detection: spring.datasource.hikari.leak-detection-threshold=30000; monitor pool utilization",
			BaseConfidence: 85, BaseRiskScore: 80,
		},
		{
			ID: "java-gc-overhead", Category: "application", SubCategory: "java",
			Keywords: []string{"gc overhead limit exceeded", "gc overhead", "excessive gc"},
			Severity: "critical",
			RootCause: "JVM is spending more than 98% of time in garbage collection and recovering less than 2% of heap",
			Reasoning: []string{
				"This indicates the heap is nearly full and GC cannot free enough memory",
				"The application is effectively stalled — all threads are waiting for GC",
				"It is a precursor to OutOfMemoryError and service failure",
			},
			Impact:          "Application is frozen; all requests time out; effectively an outage",
			ResolutionSteps: []string{"Restart the service immediately to restore availability", "Increase heap size: -Xmx (at least 2x current)", "Enable GC logging: -Xlog:gc*:file=gc.log to analyze GC behavior", "Take heap dump for analysis: jmap -dump:live,format=b,file=heap.hprof <PID>", "Switch to G1GC or ZGC for better large-heap performance: -XX:+UseG1GC"},
			Prevention:      "Monitor GC pause times and frequency; set heap size to at least 2x live data; use G1GC or ZGC",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "java-deadlock", Category: "application", SubCategory: "java",
			Keywords: []string{"deadlock detected", "thread deadlock", "java deadlock", "waiting to lock"},
			Severity: "critical",
			RootCause: "Thread deadlock detected — two or more threads are permanently blocked waiting on each other",
			Reasoning: []string{
				"Deadlocks occur when threads acquire locks in inconsistent order",
				"The deadlocked threads will never recover without intervention",
				"Other threads may cascade-block if they need the same locks",
			},
			Impact:          "Affected threads are permanently stuck; requests to those code paths hang indefinitely",
			ResolutionSteps: []string{"Get thread dump to see the deadlock: jstack <PID>", "Restart the service as immediate mitigation", "Identify the lock ordering from the thread dump", "Fix lock ordering: always acquire locks in the same global order", "Consider using java.util.concurrent locks with tryLock timeout instead of synchronized"},
			Prevention:      "Use consistent lock ordering; prefer java.util.concurrent utilities; add deadlock detection to monitoring",
			BaseConfidence: 90, BaseRiskScore: 80,
		},
		{
			ID: "java-connect-refused", Category: "application", SubCategory: "java",
			Keywords: []string{"java.net.connectexception", "connection refused java", "connect exception"},
			Severity: "high",
			RootCause: "Java application cannot connect to a downstream service — connection refused",
			Reasoning: []string{
				"Connection refused means the target host is reachable but nothing is listening on the port",
				"The target service may be down, restarting, or the port is wrong",
				"Network firewalls may also manifest as connection refused in some configurations",
			},
			Impact:          "Dependent functionality fails; requests relying on the downstream service return errors",
			ResolutionSteps: []string{"Check if target service is running: curl -v <host>:<port>", "Verify the connection string (host, port) in application config", "Check target service logs for startup errors", "Verify network path: telnet <host> <port>", "Check firewall rules: iptables -L -n | grep <port>"},
			Prevention:      "Implement circuit breaker pattern (Resilience4j, Hystrix); add health checks for dependencies; use service discovery",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "java-socket-timeout", Category: "application", SubCategory: "java",
			Keywords: []string{"sockettimeoutexception", "socket timeout", "read timed out java"},
			Severity: "high",
			RootCause: "Java socket read/connect timeout — downstream service is not responding in time",
			Reasoning: []string{
				"The downstream service accepted the connection but did not respond within the timeout period",
				"The downstream may be overloaded, GC-paused, or processing a slow query",
				"Network latency spikes can also cause socket timeouts",
			},
			Impact:          "Requests to the downstream fail; user-facing latency if on critical path; potential cascading failure",
			ResolutionSteps: []string{"Check downstream service health and response time", "Increase timeout if downstream is legitimately slow: setConnectTimeout/setReadTimeout", "Add retry logic with exponential backoff for transient timeouts", "Check if downstream is GC-pausing: review GC logs on the downstream", "Implement circuit breaker to fail fast instead of waiting for timeout"},
			Prevention:      "Set appropriate timeouts for each dependency; implement circuit breakers; monitor downstream latency",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "java-ssl-handshake", Category: "application", SubCategory: "java",
			Keywords: []string{"sslhandshakeexception", "ssl handshake", "certificate_unknown", "handshake_failure java"},
			Severity: "high",
			RootCause: "TLS/SSL handshake failed — certificate validation or protocol mismatch",
			Reasoning: []string{
				"Common causes: expired certificate, untrusted CA, hostname mismatch, or TLS version incompatibility",
				"Java truststore may not contain the required CA certificate",
				"Server may require TLS 1.2+ while client is offering older versions",
			},
			Impact:          "All HTTPS connections to the target fail; service-to-service communication breaks",
			ResolutionSteps: []string{"Check certificate expiry: openssl s_client -connect <host>:443 2>/dev/null | openssl x509 -noout -dates", "Import CA certificate to Java truststore: keytool -importcert -keystore $JAVA_HOME/lib/security/cacerts -file ca.crt", "Check TLS version: openssl s_client -connect <host>:443 -tls1_2", "Verify hostname matches certificate CN/SAN", "Update Java truststore password from default 'changeit' if security requires"},
			Prevention:      "Monitor certificate expiry 30 days in advance; automate cert renewal; keep JDK updated for latest CA roots",
			BaseConfidence: 80, BaseRiskScore: 65,
		},
		{
			ID: "java-file-not-found", Category: "application", SubCategory: "java",
			Keywords: []string{"filenotfoundexception", "java file not found", "no such file java"},
			Severity: "medium",
			RootCause: "Java application cannot find a required file at the expected path",
			Reasoning: []string{
				"The file path may be wrong, the file was not deployed, or permissions prevent access",
				"Configuration files, keystores, and data files are common causes",
				"In containers, the file may exist on the image but not be mounted at runtime",
			},
			Impact:          "Feature dependent on the file fails; may prevent service startup",
			ResolutionSteps: []string{"Check the full path from the exception message", "Verify the file exists: ls -la <path>", "Check file permissions: stat <path>", "For containers: verify volume mounts are correct in the deployment spec", "Check if path is relative — it resolves from the working directory, not the JAR location"},
			Prevention:      "Use absolute paths in configuration; validate required files at startup; document required volume mounts",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "java-illegal-state", Category: "application", SubCategory: "java",
			Keywords: []string{"illegalstateexception", "illegal state", "invalid state java"},
			Severity: "high",
			RootCause: "Java method invoked at an inappropriate time or object is in invalid state",
			Reasoning: []string{
				"Common causes: calling methods on closed resources, using objects before initialization",
				"Spring context not fully initialized when beans are accessed",
				"Thread safety issues where shared state is modified without synchronization",
			},
			Impact:          "Request handling fails; may indicate a concurrency bug affecting multiple requests",
			ResolutionSteps: []string{"Read the full exception message and stack trace for context", "Check if the exception comes from a framework (Spring, Hibernate) lifecycle issue", "Verify object lifecycle: was the resource closed/disposed before use?", "Check for thread-safety issues: is the object shared across threads without synchronization?", "Add proper initialization checks or use @PostConstruct for setup"},
			Prevention:      "Use proper lifecycle management; implement thread-safe patterns; validate preconditions at method entry",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "java-concurrent-modification", Category: "application", SubCategory: "java",
			Keywords: []string{"concurrentmodificationexception", "concurrent modification", "fail-fast iterator"},
			Severity: "high",
			RootCause: "A collection was modified while being iterated, violating the fail-fast iterator contract",
			Reasoning: []string{
				"This is almost always a thread-safety bug — multiple threads accessing the same collection",
				"Can also happen in single-threaded code if removing elements during for-each iteration",
				"The exception may be intermittent, appearing only under specific timing conditions",
			},
			Impact:          "Intermittent request failures; data corruption if the collection contains shared state",
			ResolutionSteps: []string{"Check the stack trace to find which collection is being modified", "Use ConcurrentHashMap instead of HashMap for shared maps", "Use CopyOnWriteArrayList instead of ArrayList for shared lists", "For single-threaded iteration: use Iterator.remove() instead of Collection.remove()", "Add proper synchronization around the collection access"},
			Prevention:      "Use concurrent collections from java.util.concurrent; review shared mutable state in code reviews",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "java-spring-bean-error", Category: "application", SubCategory: "java",
			Keywords: []string{"beancreationexception", "unsatisfied dependency", "no qualifying bean", "spring context"},
			Severity: "high",
			RootCause: "Spring application context failed to start due to bean creation or dependency injection error",
			Reasoning: []string{
				"A Spring bean could not be created because its dependencies are missing or circular",
				"This typically prevents the entire application from starting",
				"Common after dependency version upgrades or configuration changes",
			},
			Impact:          "Application fails to start; complete service outage until fixed and redeployed",
			ResolutionSteps: []string{"Read the full error chain — Spring reports the root cause at the bottom", "Check if a required bean is missing: verify @Component/@Service/@Repository annotation", "Check for circular dependencies: Spring reports these explicitly", "Verify @ConditionalOnProperty or @Profile conditions match the environment", "Rollback to the previous version if this is a recent deployment issue"},
			Prevention:      "Run integration tests before deploy; use constructor injection to catch circular deps at compile time",
			BaseConfidence: 80, BaseRiskScore: 70,
		},
	}
}

func buildPythonEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "py-memory-error", Category: "application", SubCategory: "python",
			Keywords: []string{"memoryerror", "python out of memory", "killed signal 9 python"},
			Severity: "critical",
			RootCause: "Python process ran out of memory — allocation failed",
			Reasoning: []string{
				"Python has no heap limit by default, so MemoryError means the OS refused more memory",
				"Common causes: loading entire large files into memory, growing lists without bounds",
				"The process was either killed by OOM killer (signal 9) or raised MemoryError",
			},
			Impact:          "Service crash; in-flight requests lost; potential data corruption if writes were buffered",
			ResolutionSteps: []string{"Profile memory usage: python -m tracemalloc in the code", "Use generators instead of lists for large datasets: (x for x in ...) instead of [x for x in ...]", "Process files line-by-line instead of loading entirely: for line in open(file)", "Check for memory leaks with objgraph: objgraph.show_most_common_types()", "Increase container/server memory as temporary mitigation"},
			Prevention:      "Stream large datasets; use memory profiling in CI; set container memory limits with OOM alerts",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "py-recursion-error", Category: "application", SubCategory: "python",
			Keywords: []string{"recursionerror", "maximum recursion depth", "recursion limit"},
			Severity: "high",
			RootCause: "Python hit the maximum recursion depth limit (default 1000)",
			Reasoning: []string{
				"Python does not optimize tail recursion, so deep recursion always hits the limit",
				"Common causes: infinite recursion bug, deeply nested data structures",
				"Increasing the limit is a band-aid — convert to iterative approach",
			},
			Impact:          "Request fails; the recursive operation is aborted",
			ResolutionSteps: []string{"Find the recursive function in the stack trace", "Convert recursive logic to iterative with an explicit stack", "If legitimate depth: sys.setrecursionlimit(3000) as temporary fix", "Check for circular references in data structures (e.g., self-referencing dicts)", "Use functools.lru_cache to avoid redundant recursive calls"},
			Prevention:      "Prefer iterative algorithms; limit recursion depth in business logic; test with deep inputs",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "py-import-error", Category: "application", SubCategory: "python",
			Keywords: []string{"importerror", "modulenotfounderror", "no module named"},
			Severity: "high",
			RootCause: "Python cannot find a required module — missing dependency or virtual environment issue",
			Reasoning: []string{
				"The module is not installed in the current Python environment",
				"Common causes: missing from requirements.txt, wrong virtualenv, or Python version mismatch",
				"In containers: a dependency may be missing from the Docker image",
			},
			Impact:          "Application fails to start; or a specific feature fails when the import is triggered",
			ResolutionSteps: []string{"Install the missing module: pip install <module_name>", "Verify virtual environment is activated: which python && pip list", "Check requirements.txt includes the dependency: grep <module> requirements.txt", "For containers: rebuild the image with pip install -r requirements.txt", "Check Python version compatibility: python --version"},
			Prevention:      "Pin all dependencies in requirements.txt; use pip freeze; run import checks in CI",
			BaseConfidence: 80, BaseRiskScore: 65,
		},
		{
			ID: "py-connection-refused", Category: "application", SubCategory: "python",
			Keywords: []string{"connectionrefusederror", "connection refused python", "errno 111"},
			Severity: "high",
			RootCause: "Python application cannot connect to a service — target is not listening",
			Reasoning: []string{
				"Connection refused means the target host is reachable but the port is not open",
				"The target service may be down, restarting, or misconfigured",
				"Check database, Redis, or API service that the Python app depends on",
			},
			Impact:          "All operations requiring the downstream service fail",
			ResolutionSteps: []string{"Verify target service is running: systemctl status <service>", "Test connectivity: python -c \"import socket; s=socket.socket(); s.connect(('<host>', <port>))\"", "Check target service logs for errors", "Verify connection string in environment variables or config", "Check firewall and security groups between the two hosts"},
			Prevention:      "Add health checks for dependencies at startup; implement retry logic with backoff; use circuit breakers",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "py-timeout-error", Category: "application", SubCategory: "python",
			Keywords: []string{"timeouterror", "timeout python", "timed out python", "readtimeouterror"},
			Severity: "high",
			RootCause: "Python operation timed out — downstream service or I/O took too long",
			Reasoning: []string{
				"The downstream service or network operation did not complete within the timeout window",
				"Common in HTTP requests (requests library), database queries, and external API calls",
				"The downstream may be overloaded, network may be congested, or the operation is inherently slow",
			},
			Impact:          "Request fails; upstream callers also wait longer; potential cascading timeout",
			ResolutionSteps: []string{"Check downstream service health and response time", "Increase timeout if the operation is legitimately slow: requests.get(url, timeout=30)", "Add retry with exponential backoff: from urllib3.util.retry import Retry", "Implement async processing for long operations", "Add circuit breaker: pip install pybreaker"},
			Prevention:      "Always set explicit timeouts on all external calls; implement circuit breakers; monitor p99 latency",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "py-permission-error", Category: "application", SubCategory: "python",
			Keywords: []string{"permissionerror", "permission denied python", "errno 13 python"},
			Severity: "medium",
			RootCause: "Python process lacks filesystem permissions to read or write the target file/directory",
			Reasoning: []string{
				"The OS denied access due to file ownership or permission bits",
				"Common in containers where the process runs as non-root",
				"SELinux or AppArmor may also deny access even with correct UNIX permissions",
			},
			Impact:          "Specific file operations fail; may prevent logging, config reading, or data writes",
			ResolutionSteps: []string{"Check file permissions: ls -la <path>", "Check process user: id", "Fix ownership: chown <user>:<group> <path>", "Fix permissions: chmod 644 <path> (files) or chmod 755 <path> (directories)", "Check SELinux: getenforce && ausearch -m avc | tail -5"},
			Prevention:      "Run containers as non-root with appropriate UID; set correct file permissions in Dockerfile; test file access",
			BaseConfidence: 70, BaseRiskScore: 45,
		},
		{
			ID: "py-key-error", Category: "application", SubCategory: "python",
			Keywords: []string{"keyerror", "key error python"},
			Severity: "medium",
			RootCause: "Python dictionary key access failed — the key does not exist",
			Reasoning: []string{
				"Code accessed dict[key] but the key is not in the dictionary",
				"Common causes: changed API response format, missing config key, or data inconsistency",
				"Use dict.get(key, default) to safely access keys that may be absent",
			},
			Impact:          "Request fails with 500 error; specific data processing pipeline breaks",
			ResolutionSteps: []string{"Check the KeyError message to identify which key is missing", "Use dict.get('key', default_value) instead of dict['key']", "Validate the input data structure before accessing nested keys", "Check if the upstream API changed its response format", "Add defensive coding: if 'key' in data: ..."},
			Prevention:      "Use .get() with defaults; validate API responses against schemas; add type hints",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "py-json-decode-error", Category: "application", SubCategory: "python",
			Keywords: []string{"json.decoder.jsondecodeerror", "json decode error", "expecting value", "json loads"},
			Severity: "medium",
			RootCause: "Python failed to parse JSON — the input is not valid JSON",
			Reasoning: []string{
				"The input string is either empty, truncated, or contains invalid JSON syntax",
				"Common causes: empty HTTP response body, HTML error page instead of JSON, or encoding issues",
				"The upstream service may be returning an error page instead of a JSON API response",
			},
			Impact:          "Data parsing fails; dependent operations cannot proceed",
			ResolutionSteps: []string{"Log the raw input before json.loads() to see what was received", "Check if the upstream service is returning an error page (HTML 500/502/503)", "Handle empty responses: if response.text: data = response.json()", "Check Content-Type header: ensure response is application/json", "Wrap json.loads in try/except with meaningful error logging"},
			Prevention:      "Validate Content-Type before parsing; handle empty responses; log raw responses on parse failure",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "py-unicode-error", Category: "application", SubCategory: "python",
			Keywords: []string{"unicodedecodeerror", "unicode error", "codec can't decode", "encoding error python"},
			Severity: "medium",
			RootCause: "Python encountered bytes that cannot be decoded with the expected encoding",
			Reasoning: []string{
				"The file or data stream contains bytes that are not valid in the assumed encoding (usually UTF-8)",
				"Common when reading files created on different OS (Windows Latin-1 vs Linux UTF-8)",
				"Database content may have mixed encodings from legacy data imports",
			},
			Impact:          "Data processing fails for records with non-standard characters",
			ResolutionSteps: []string{"Specify encoding explicitly: open(file, encoding='utf-8', errors='replace')", "Detect encoding: pip install chardet && chardet.detect(raw_bytes)", "Use errors='replace' or errors='ignore' for resilient parsing", "For database: verify database and connection encoding match", "Convert the source data to UTF-8: iconv -f <source_encoding> -t utf-8 <file>"},
			Prevention:      "Always specify encoding; use UTF-8 everywhere; validate encoding at data ingestion boundaries",
			BaseConfidence: 60, BaseRiskScore: 40,
		},
		{
			ID: "py-celery-max-retries", Category: "application", SubCategory: "python",
			Keywords: []string{"maxretriesexceedederror", "max retries exceeded", "celery retry"},
			Severity: "high",
			RootCause: "Celery task has exceeded its maximum retry count and permanently failed",
			Reasoning: []string{
				"The task kept failing on every retry attempt, indicating a persistent issue",
				"The underlying cause (DB down, service unavailable) persisted longer than the retry window",
				"The task is now dead-lettered and its work is lost unless the result is stored",
			},
			Impact:          "Background job permanently failed; any work it was supposed to do is not completed",
			ResolutionSteps: []string{"Check Celery logs for the original exception causing retries", "Fix the underlying cause (DB connectivity, service availability)", "Resubmit the failed task manually: task.apply_async(args=...)", "Increase max_retries or retry_backoff in the task decorator", "Set up a dead-letter queue to capture permanently failed tasks"},
			Prevention:      "Use exponential backoff for retries; implement dead-letter queues; monitor task failure rate",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "py-django-operational-error", Category: "application", SubCategory: "python",
			Keywords: []string{"django.db.utils.operationalerror", "operational error django", "database operational error"},
			Severity: "high",
			RootCause: "Django database operational error — cannot connect to or query the database",
			Reasoning: []string{
				"OperationalError covers connection failures, timeouts, and server-side issues",
				"The database server may be down, overloaded, or the connection pool is exhausted",
				"This blocks all database-dependent views and API endpoints",
			},
			Impact:          "All database-dependent requests fail; site is effectively down",
			ResolutionSteps: []string{"Check database connectivity: python manage.py dbshell", "Verify DATABASE_URL or DATABASES config in settings.py", "Check database server status: systemctl status postgresql", "Check for connection pool exhaustion: increase CONN_MAX_AGE or pool size", "Restart Django application to reset stale connections"},
			Prevention:      "Use database connection pooling (django-db-connection-pool); add database health checks; monitor query performance",
			BaseConfidence: 80, BaseRiskScore: 70,
		},
		{
			ID: "py-gunicorn-timeout", Category: "application", SubCategory: "python",
			Keywords: []string{"gunicorn timeout", "worker timeout", "gunicorn worker killed"},
			Severity: "high",
			RootCause: "Gunicorn worker process was killed for exceeding the request timeout",
			Reasoning: []string{
				"Default gunicorn timeout is 30 seconds — any request taking longer kills the worker",
				"The worker is killed with SIGKILL, so cleanup code does not run",
				"Common causes: slow database query, external API timeout, or CPU-intensive processing",
			},
			Impact:          "The request fails; the worker is respawned but in-flight request data is lost",
			ResolutionSteps: []string{"Increase timeout: gunicorn --timeout 120 (if long requests are expected)", "Identify slow requests: check access logs for response times", "Move long operations to background tasks (Celery)", "Use async workers for I/O-bound requests: gunicorn -k uvicorn.workers.UvicornWorker", "Add request timeout monitoring to identify consistently slow endpoints"},
			Prevention:      "Use background tasks for long operations; set appropriate timeouts; monitor p95 response times",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "py-ssl-error", Category: "application", SubCategory: "python",
			Keywords: []string{"ssl.sslerror", "certificate_verify_failed", "ssl error python"},
			Severity: "high",
			RootCause: "Python SSL certificate verification failed when connecting to an HTTPS endpoint",
			Reasoning: []string{
				"The server certificate is expired, self-signed, or the CA is not trusted by the system",
				"The certifi package may be outdated and missing recent CA certificates",
				"In containers, the CA bundle may not be installed",
			},
			Impact:          "All HTTPS connections to the affected endpoint fail",
			ResolutionSteps: []string{"Check certificate: openssl s_client -connect <host>:443 2>/dev/null | openssl x509 -noout -dates", "Update certifi: pip install --upgrade certifi", "For self-signed certs: set REQUESTS_CA_BUNDLE=/path/to/ca-bundle.crt", "Install CA certificates in container: apt-get install ca-certificates", "Do NOT use verify=False in production — it disables all certificate validation"},
			Prevention:      "Keep certifi updated; automate certificate renewal; monitor certificate expiry",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "py-type-error", Category: "application", SubCategory: "python",
			Keywords: []string{"typeerror", "type error python", "not subscriptable", "not callable", "not iterable"},
			Severity: "medium",
			RootCause: "Python TypeError — operation applied to an object of inappropriate type",
			Reasoning: []string{
				"Common causes: None where an object is expected, str where int is needed, or wrong argument count",
				"Often indicates missing type validation at API boundaries",
				"May be caused by API changes in upstream libraries after version update",
			},
			Impact:          "Request processing fails; specific code paths break",
			ResolutionSteps: []string{"Read the TypeError message — it describes exactly what went wrong", "Check if a function is receiving None instead of an expected value", "Add type hints and use mypy for static analysis: mypy <module>", "Validate input types at API boundaries before processing", "Check if a library version change altered function signatures"},
			Prevention:      "Use type hints and mypy; validate inputs at boundaries; pin dependency versions",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "py-value-error", Category: "application", SubCategory: "python",
			Keywords: []string{"valueerror", "value error python", "invalid literal"},
			Severity: "medium",
			RootCause: "Python ValueError — function received an argument with the right type but wrong value",
			Reasoning: []string{
				"Common causes: int('abc'), invalid date format, or out-of-range values",
				"Often from user input that was not validated before processing",
				"Can also come from data corruption or format changes in external data sources",
			},
			Impact:          "Data processing fails for the affected input; request returns 400/500",
			ResolutionSteps: []string{"Read the ValueError message to see what value was invalid", "Add input validation before the operation: try/except ValueError", "Use a validation library (pydantic, marshmallow) for structured input", "Check if external data format changed (API response, file format)", "Log the invalid value for debugging: log the input that caused the error"},
			Prevention:      "Validate all external input; use pydantic models; add error handling around type conversions",
			BaseConfidence: 60, BaseRiskScore: 40,
		},
	}
}

func buildNodeEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "node-oom", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"javascript heap out of memory", "heap out of memory", "fatal error: allocation", "v8 heap"},
			Severity: "critical",
			RootCause: "Node.js V8 heap memory exhausted — process cannot allocate more memory",
			Reasoning: []string{
				"V8 has a default heap limit (~1.7GB on 64-bit) which was exceeded",
				"Common causes: large data processing in memory, memory leaks, or unbounded caches",
				"The process crashes immediately when the heap limit is reached",
			},
			Impact:          "Process crash; all in-flight requests are lost; service outage until restart",
			ResolutionSteps: []string{"Increase heap limit: node --max-old-space-size=4096 app.js", "Profile heap: use --inspect flag and Chrome DevTools Memory tab", "Check for memory leaks: take two heap snapshots 5 min apart and compare", "Stream large data instead of loading into memory: use Node.js streams API", "Use worker_threads for memory-intensive operations"},
			Prevention:      "Set --max-old-space-size explicitly; monitor process.memoryUsage().heapUsed; take periodic heap snapshots",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "node-econnrefused", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"econnrefused", "connection refused node", "connect econnrefused"},
			Severity: "high",
			RootCause: "Node.js cannot connect to a downstream service — the target port is not listening",
			Reasoning: []string{
				"ECONNREFUSED means TCP handshake was rejected — nothing listening on the target port",
				"The target service (database, Redis, API) may be down or misconfigured",
				"Firewall rules may also cause connection refusals",
			},
			Impact:          "All requests depending on the downstream service fail",
			ResolutionSteps: []string{"Check target service health: curl -v <host>:<port>", "Verify connection string in .env or config: echo $DATABASE_URL", "Restart the target service: systemctl restart <service>", "Check firewall rules: iptables -L -n | grep <port>", "Implement retry logic: npm install retry or p-retry"},
			Prevention:      "Add startup health checks for dependencies; implement circuit breakers; use connection retry with backoff",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "node-etimedout", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"etimedout", "connect etimedout", "socket timeout node"},
			Severity: "high",
			RootCause: "Node.js connection or socket timed out waiting for a response",
			Reasoning: []string{
				"ETIMEDOUT means the TCP handshake or data read exceeded the timeout",
				"The target service may be overloaded or network path has high latency",
				"Different from ECONNREFUSED: here the host is reachable but not responding",
			},
			Impact:          "Requests to the downstream service hang then fail; event loop may become congested with pending connections",
			ResolutionSteps: []string{"Check downstream service response time", "Increase timeout: {timeout: 30000} in request options", "Check network latency: ping <host>", "Add connection pooling with keep-alive", "Implement circuit breaker: npm install opossum"},
			Prevention:      "Set explicit timeouts on all outbound connections; implement circuit breakers; monitor downstream latency",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "node-eaddrinuse", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"eaddrinuse", "address already in use", "port already in use node"},
			Severity: "high",
			RootCause: "Node.js cannot bind to the port because another process is already using it",
			Reasoning: []string{
				"EADDRINUSE occurs when server.listen() attempts to bind to an occupied port",
				"The previous instance may not have shut down cleanly",
				"Multiple instances may be configured to use the same port",
			},
			Impact:          "Application fails to start; service outage until the port conflict is resolved",
			ResolutionSteps: []string{"Find the process using the port: lsof -i :<port>", "Kill the old process: kill <PID>", "If stuck in TIME_WAIT: sysctl -w net.ipv4.tcp_tw_reuse=1", "Use SO_REUSEADDR: server.listen(port, () => {}).on('error', ...)", "Change the application port in configuration"},
			Prevention:      "Implement graceful shutdown with server.close(); use process managers (PM2) for restart handling",
			BaseConfidence: 80, BaseRiskScore: 55,
		},
		{
			ID: "node-unhandled-promise", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"unhandledpromiserejection", "unhandled promise rejection", "unhandledrejection"},
			Severity: "high",
			RootCause: "A Promise was rejected but no .catch() handler was attached",
			Reasoning: []string{
				"Unhandled rejections indicate missing error handling in async code",
				"In Node.js 15+, unhandled rejections crash the process by default",
				"Common causes: missing .catch(), forgetting await in try/catch, or uncaught async errors in event handlers",
			},
			Impact:          "Process may crash (Node 15+); the operation silently fails in older versions; data may be lost",
			ResolutionSteps: []string{"Add .catch() to the Promise chain shown in the warning", "Add global handler: process.on('unhandledRejection', (reason) => { console.error(reason); })", "Use try/catch with await instead of .then().catch()", "Add error handling to all async Express middleware", "Check for missing await before async function calls"},
			Prevention:      "Use eslint rule no-floating-promises; add global unhandledRejection handler; use async error middleware in Express",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "node-event-loop-blocked", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"event loop blocked", "event loop lag", "event loop delay", "event loop stuck"},
			Severity: "high",
			RootCause: "Node.js event loop is blocked by synchronous code, preventing all I/O processing",
			Reasoning: []string{
				"When the event loop is blocked, no callbacks fire — all network I/O stalls",
				"Common causes: CPU-intensive computation, synchronous file I/O, JSON.parse on large data",
				"Even 100ms of blocking causes noticeable request latency for all connections",
			},
			Impact:          "All requests stall; health checks fail; WebSocket connections drop; process appears hung",
			ResolutionSteps: []string{"Profile with clinic.js: npx clinic doctor -- node app.js", "Use --prof flag: node --prof app.js (then process with --prof-process)", "Move CPU-intensive work to worker_threads", "Replace sync file ops with async: fs.readFileSync -> fs.promises.readFile", "Use streaming JSON parsing for large payloads: npm install stream-json"},
			Prevention:      "Monitor event loop lag; use eslint rules to flag sync I/O; offload CPU-bound work to worker threads",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "node-max-listeners", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"maxlistenersexceededwarning", "max listeners", "possible eventemitter memory leak"},
			Severity: "medium",
			RootCause: "EventEmitter has more than the default 10 listeners, indicating a likely memory leak",
			Reasoning: []string{
				"Node.js warns at 11+ listeners because it usually indicates handlers being added but not removed",
				"Each request adding a listener without cleanup will grow the listener count indefinitely",
				"This is a classic memory/resource leak pattern in Node.js",
			},
			Impact:          "Memory leak; degrading performance over time; eventual crash",
			ResolutionSteps: []string{"Find where listeners are being added: search code for .on( or .addListener(", "Remove listeners when no longer needed: emitter.removeListener() or emitter.off()", "If legitimate: increase limit for that emitter: emitter.setMaxListeners(50)", "Check for listeners added in request handlers that are never removed", "Use once() instead of on() for one-time event listeners"},
			Prevention:      "Use .once() for one-time listeners; always removeListener in cleanup; monitor emitter listener counts",
			BaseConfidence: 70, BaseRiskScore: 50,
		},
		{
			ID: "node-require-esm", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"err_require_esm", "cannot use import statement", "require() of es module"},
			Severity: "medium",
			RootCause: "Node.js tried to require() an ES Module package, which is not supported",
			Reasoning: []string{
				"The dependency has been updated to ESM-only (e.g., got, chalk, node-fetch v3+)",
				"CommonJS require() cannot load ES Modules directly",
				"This is increasingly common as the npm ecosystem migrates to ESM",
			},
			Impact:          "Application fails to start or the specific import fails at runtime",
			ResolutionSteps: []string{"Use dynamic import: const pkg = await import('package-name')", "Downgrade to the last CommonJS version of the package", "Convert your project to ESM: set \"type\": \"module\" in package.json", "Use an ESM-compatible wrapper if available", "For TypeScript: set moduleResolution to 'nodenext' in tsconfig.json"},
			Prevention:      "Check package changelogs before major version updates; use import() for ESM packages in CommonJS",
			BaseConfidence: 70, BaseRiskScore: 45,
		},
		{
			ID: "node-mongoose-timeout", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"mongoose timeout", "mongooseerror", "operation timed out mongodb", "mongodb connection error"},
			Severity: "high",
			RootCause: "Mongoose/MongoDB operation timed out — database is not responding",
			Reasoning: []string{
				"The MongoDB server is not responding within the configured timeout",
				"Common causes: MongoDB is down, network issues, or the query is too slow",
				"Connection pool may be exhausted from slow queries holding connections",
			},
			Impact:          "All database operations fail; application cannot read or write data",
			ResolutionSteps: []string{"Check MongoDB connectivity: mongosh --eval 'db.serverStatus()'", "Check MongoDB logs: journalctl -u mongod | tail -50", "Increase timeout: mongoose.connect(uri, { serverSelectionTimeoutMS: 10000 })", "Check for slow queries: db.currentOp({\"secs_running\": {\"$gt\": 5}})", "Restart MongoDB if unresponsive: systemctl restart mongod"},
			Prevention:      "Monitor MongoDB health; set appropriate timeouts; add indexes for common queries; use connection pooling",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "node-sequelize-error", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"sequelizeconnectionerror", "sequelize connection", "sequelize error"},
			Severity: "high",
			RootCause: "Sequelize ORM cannot connect to the database",
			Reasoning: []string{
				"The database connection configured in Sequelize is failing",
				"Common causes: wrong credentials, database server down, or network issues",
				"Connection pool may be exhausted from leaked connections",
			},
			Impact:          "All database operations fail; API requests return 500 errors",
			ResolutionSteps: []string{"Verify DATABASE_URL or Sequelize config: check host, port, user, password, database name", "Test database connectivity directly: psql -h <host> -U <user> <database>", "Check database server status: systemctl status postgresql", "Increase pool size: sequelize = new Sequelize({ pool: { max: 20 } })", "Run pending migrations: npx sequelize-cli db:migrate"},
			Prevention:      "Use environment variables for DB config; implement connection health checks; monitor pool usage",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "node-headers-sent", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"err_http_headers_sent", "cannot set headers", "headers already sent"},
			Severity: "medium",
			RootCause: "Express/Node.js tried to send a response after headers were already sent",
			Reasoning: []string{
				"This happens when response methods (res.send, res.json, res.end) are called multiple times",
				"Common causes: missing return after res.send(), async callback executing after response",
				"Middleware calling next() and also sending a response",
			},
			Impact:          "Request may get incomplete response; server logs error; no data loss but poor user experience",
			ResolutionSteps: []string{"Find the route handler with multiple response calls in the stack trace", "Add 'return' before res.send() / res.json() to prevent further execution", "Check for async callbacks that fire after the response was already sent", "Use a flag to track if response was sent: if (res.headersSent) return", "Fix middleware that both sends a response and calls next()"},
			Prevention:      "Always return after sending a response; use async/await instead of callbacks; lint for double-response patterns",
			BaseConfidence: 65, BaseRiskScore: 35,
		},
		{
			ID: "node-entity-too-large", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"request entity too large", "payload too large", "413 node"},
			Severity: "medium",
			RootCause: "Request body exceeds the configured size limit in Express/Node.js",
			Reasoning: []string{
				"Express body-parser defaults to 100KB limit for JSON payloads",
				"The client is sending a request larger than this limit",
				"May be legitimate (file upload, large JSON) or an attack (body bomb)",
			},
			Impact:          "The specific request fails with 413; legitimate large requests are blocked",
			ResolutionSteps: []string{"Increase body limit: app.use(express.json({ limit: '10mb' }))", "For file uploads: use multer middleware with appropriate limits", "Check if the large request is legitimate or an attack", "Implement request size validation per route for security", "Use streaming for very large payloads instead of body parsing"},
			Prevention:      "Set per-route body size limits; use streaming for large uploads; implement rate limiting",
			BaseConfidence: 65, BaseRiskScore: 35,
		},
		{
			ID: "node-dns-failure", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"enotfound", "getaddrinfo enotfound", "dns lookup failed node"},
			Severity: "high",
			RootCause: "Node.js DNS resolution failed — the hostname cannot be resolved",
			Reasoning: []string{
				"ENOTFOUND means the DNS server returned no records for the hostname",
				"Common causes: typo in hostname, DNS server unreachable, or the domain does not exist",
				"In Kubernetes: CoreDNS may be overloaded or the service name may be wrong",
			},
			Impact:          "All connections to the unresolvable hostname fail; dependent service is unreachable",
			ResolutionSteps: []string{"Verify the hostname is correct in configuration", "Test DNS resolution: nslookup <hostname> or dig <hostname>", "Check /etc/resolv.conf for correct DNS servers", "In Kubernetes: check CoreDNS pods: kubectl get pods -n kube-system -l k8s-app=kube-dns", "Use IP address as temporary workaround while fixing DNS"},
			Prevention:      "Validate hostnames in configuration; monitor DNS resolution latency; use multiple DNS servers",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "node-cert-error", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"unable_to_verify_leaf_signature", "self_signed_cert", "certificate expired node", "cert_has_expired"},
			Severity: "high",
			RootCause: "Node.js TLS certificate validation failed",
			Reasoning: []string{
				"The server certificate is expired, self-signed, or issued by an untrusted CA",
				"Node.js uses its own CA bundle which may not include custom or internal CAs",
				"Setting NODE_TLS_REJECT_UNAUTHORIZED=0 is dangerous and should never be used in production",
			},
			Impact:          "All HTTPS connections to the endpoint fail; service-to-service communication breaks",
			ResolutionSteps: []string{"Check certificate: openssl s_client -connect <host>:443", "Set NODE_EXTRA_CA_CERTS=/path/to/ca.crt for custom CA", "Renew the certificate if expired", "Update Node.js to get latest CA roots", "For development only: use --tls-min-v1.0 if version mismatch"},
			Prevention:      "Monitor certificate expiry; automate renewal with cert-manager/certbot; keep Node.js updated",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "node-file-descriptor", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"emfile", "too many open files node", "enfile"},
			Severity: "high",
			RootCause: "Node.js process exceeded the file descriptor limit",
			Reasoning: []string{
				"Each file open, socket connection, and pipe uses a file descriptor",
				"Default ulimit is often 1024 which is too low for busy services",
				"Leaked file descriptors (unclosed files/sockets) exhaust the limit over time",
			},
			Impact:          "Cannot open new files or network connections; service degrades and eventually fails",
			ResolutionSteps: []string{"Check current limits: cat /proc/<PID>/limits | grep 'Max open files'", "Increase limit: ulimit -n 65536 (or set in /etc/security/limits.conf)", "Find open file descriptors: ls /proc/<PID>/fd | wc -l", "Check for leaked file handles: lsof -p <PID> | wc -l", "Use graceful-fs: npm install graceful-fs (queues opens when limit is near)"},
			Prevention:      "Set ulimit -n 65536 in service config; always close files in finally blocks; monitor FD count",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
	}
}

func buildGoEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "go-oom", Category: "application", SubCategory: "go",
			Keywords: []string{"runtime: out of memory", "go out of memory", "fatal error: runtime: out of memory"},
			Severity: "critical",
			RootCause: "Go process ran out of memory — the runtime cannot allocate more",
			Reasoning: []string{
				"Go has no configurable heap limit; it grows until the OS refuses more memory",
				"Common causes: goroutine leak with per-goroutine allocations, unbounded caches, or large slice growth",
				"The process exits with a fatal error — there is no recovery",
			},
			Impact:          "Process crash; all in-flight requests lost; service outage",
			ResolutionSteps: []string{"Profile memory: go tool pprof http://localhost:6060/debug/pprof/heap", "Check for goroutine leaks: curl http://localhost:6060/debug/pprof/goroutine?debug=1 | head -50", "Set GOMEMLIMIT environment variable (Go 1.19+): export GOMEMLIMIT=2GiB", "Review code for unbounded slice/map growth", "Restart the service and increase container memory limit as temporary fix"},
			Prevention:      "Set GOMEMLIMIT; enable pprof endpoint in production; monitor goroutine count and heap usage",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "go-goroutine-leak", Category: "application", SubCategory: "go",
			Keywords: []string{"goroutine leak", "goroutine count growing", "too many goroutines", "goroutine"},
			Severity: "high",
			RootCause: "Goroutine leak detected — goroutine count is growing without bound",
			Reasoning: []string{
				"Goroutines stuck on blocked channel operations, network I/O, or mutexes accumulate",
				"Each goroutine consumes ~8KB stack initially, growing to MB if active",
				"Common causes: channel without consumer, HTTP client without timeout, missing context cancellation",
			},
			Impact:          "Increasing memory usage; eventual OOM; CPU wasted on blocked goroutines",
			ResolutionSteps: []string{"Check goroutine count: curl http://localhost:6060/debug/pprof/goroutine?debug=1 | head -5", "Profile goroutine stacks: go tool pprof http://localhost:6060/debug/pprof/goroutine", "Look for goroutines stuck on channel receive or network I/O", "Add context.WithTimeout to all outbound network calls", "Ensure all spawned goroutines have a shutdown path via context or channel close"},
			Prevention:      "Always pass context.Context to goroutines; use errgroup for goroutine lifecycle management; monitor goroutine count",
			BaseConfidence: 75, BaseRiskScore: 70,
		},
		{
			ID: "go-index-out-of-range", Category: "application", SubCategory: "go",
			Keywords: []string{"index out of range", "runtime error: index out of range", "slice bounds out of range"},
			Severity: "high",
			RootCause: "Go runtime panic — slice or array access with an invalid index",
			Reasoning: []string{
				"Code accessed a slice/array at an index beyond its length",
				"Common causes: empty slice access, off-by-one errors, or concurrent slice modification",
				"The panic crashes the goroutine; if unrecovered, crashes the process",
			},
			Impact:          "Request fails with panic; if in main goroutine, process crashes",
			ResolutionSteps: []string{"Check the stack trace for the exact file and line number", "Add bounds checking: if len(slice) > index { ... }", "Check for concurrent access: use sync.Mutex or channels", "Add recover() in HTTP handlers to prevent process crash on panic", "Review the data pipeline to understand why the slice is shorter than expected"},
			Prevention:      "Always check slice length before access; use recover() in request handlers; add race detector to tests: go test -race",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "go-nil-pointer", Category: "application", SubCategory: "go",
			Keywords: []string{"nil pointer dereference", "invalid memory address", "nil pointer", "runtime error: invalid memory"},
			Severity: "high",
			RootCause: "Go runtime panic — nil pointer dereference (accessing a field or method on a nil pointer)",
			Reasoning: []string{
				"A variable of pointer type is nil and was used as if it had a value",
				"Common causes: error not checked and result used, uninitialized pointer, or interface value is nil",
				"The panic crashes the goroutine; must be caught with recover() to prevent process exit",
			},
			Impact:          "Request fails with panic; potential process crash if recover() is not in place",
			ResolutionSteps: []string{"Check the stack trace for the file and line of the nil dereference", "Add nil checks before using pointers: if ptr != nil { ... }", "Check all error returns: if err != nil { return err } — do not use the result when err is set", "Add recover() middleware in HTTP server to catch panics gracefully", "Check interface assertions: use val, ok := iface.(Type) instead of val := iface.(Type)"},
			Prevention:      "Use go vet and staticcheck; check all errors; add nil guards; use recover() in handlers",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "go-context-deadline", Category: "application", SubCategory: "go",
			Keywords: []string{"context deadline exceeded", "context canceled", "deadline exceeded go"},
			Severity: "high",
			RootCause: "Go context deadline expired — the operation took too long and was cancelled",
			Reasoning: []string{
				"The context.WithTimeout or context.WithDeadline timer expired before the operation completed",
				"The downstream service is too slow or the timeout is too short",
				"This is working as intended — timeouts prevent unbounded waits",
			},
			Impact:          "The specific request fails; resources used by the timed-out operation may not be cleaned up",
			ResolutionSteps: []string{"Check which operation timed out from the error context", "Increase the timeout if the operation legitimately takes longer", "Investigate why the downstream is slow: check its logs and metrics", "Add timeout logging: log the operation duration before the deadline", "Implement retry with backoff for transient timeouts"},
			Prevention:      "Set appropriate timeouts per operation; monitor operation durations; implement circuit breakers",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "go-tls-unknown-authority", Category: "application", SubCategory: "go",
			Keywords: []string{"x509: certificate signed by unknown authority", "x509 unknown authority", "certificate verify go"},
			Severity: "high",
			RootCause: "Go TLS client does not trust the server certificate — unknown certificate authority",
			Reasoning: []string{
				"The server certificate was signed by a CA not in the system CA store",
				"Common with internal/private CAs, self-signed certificates, or missing intermediate certs",
				"Go uses the system CA store by default; custom CAs need explicit configuration",
			},
			Impact:          "All HTTPS connections to the affected endpoint fail",
			ResolutionSteps: []string{"Check the certificate chain: openssl s_client -connect <host>:443 -showcerts", "Add the CA cert to the system store: cp ca.crt /usr/local/share/ca-certificates/ && update-ca-certificates", "In code: load custom CA into tls.Config.RootCAs", "Check for missing intermediate certificates on the server", "Set SSL_CERT_FILE env var to point to the CA bundle"},
			Prevention:      "Include all intermediate certs in server configuration; distribute internal CA certs to all services",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "go-too-many-open-files", Category: "application", SubCategory: "go",
			Keywords: []string{"too many open files go", "socket: too many open files", "open files go"},
			Severity: "high",
			RootCause: "Go process exceeded the file descriptor limit",
			Reasoning: []string{
				"Each open file, socket, and pipe uses a file descriptor",
				"Leaked HTTP response bodies (not calling resp.Body.Close()) are the most common cause in Go",
				"The default ulimit may be too low for a busy server",
			},
			Impact:          "Cannot open new files or connections; all network operations fail",
			ResolutionSteps: []string{"Increase file descriptor limit: ulimit -n 65536", "Check for leaked file descriptors: ls /proc/<PID>/fd | wc -l", "Audit code for unclosed resp.Body: always defer resp.Body.Close()", "Check for unclosed os.File handles: search for os.Open without defer f.Close()", "Set in systemd service: LimitNOFILE=65536"},
			Prevention:      "Always close HTTP response bodies; use defer for file closes; set high ulimit for server processes",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "go-http-wrong-protocol", Category: "application", SubCategory: "go",
			Keywords: []string{"http: server gave http response to https client", "wrong protocol go"},
			Severity: "medium",
			RootCause: "Go HTTP client sent HTTPS but the server responded with plain HTTP",
			Reasoning: []string{
				"The URL uses https:// but the server is only serving HTTP",
				"Common when TLS termination is done at a load balancer and the backend is HTTP",
				"Internal service-to-service calls may not need HTTPS if within a trusted network",
			},
			Impact:          "Connection fails; requests to this endpoint do not complete",
			ResolutionSteps: []string{"Change the URL from https:// to http:// if TLS is terminated upstream", "Or configure TLS on the target server", "Check if a proxy or load balancer is doing TLS termination", "Verify the port — HTTPS is typically 443, HTTP is typically 80/8080"},
			Prevention:      "Document which services use TLS vs plain HTTP; standardize on TLS for all services",
			BaseConfidence: 70, BaseRiskScore: 40,
		},
		{
			ID: "go-connection-refused", Category: "application", SubCategory: "go",
			Keywords: []string{"connection refused go", "dial tcp.*refused", "connect: connection refused"},
			Severity: "high",
			RootCause: "Go application cannot connect to a downstream service — connection refused",
			Reasoning: []string{
				"The TCP handshake was rejected — nothing is listening on the target port",
				"The target service is down, hasn't started yet, or the address/port is wrong",
				"In Kubernetes: the Service may have no ready endpoints",
			},
			Impact:          "All requests depending on the downstream service fail with errors",
			ResolutionSteps: []string{"Check if target service is running: curl -v <host>:<port>", "Verify connection details in environment config", "Check target service logs for startup errors", "In Kubernetes: kubectl get endpoints <service-name>", "Implement retry with exponential backoff for startup races"},
			Prevention:      "Implement health check dependencies; add connection retry at startup; use circuit breakers",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "go-dns-lookup-failed", Category: "application", SubCategory: "go",
			Keywords: []string{"dial tcp: lookup", "no such host", "dns lookup go"},
			Severity: "high",
			RootCause: "Go DNS resolution failed for a hostname — the hostname cannot be resolved",
			Reasoning: []string{
				"The DNS server returned NXDOMAIN or no records for the hostname",
				"Common causes: wrong hostname in config, DNS server unreachable, or network isolation",
				"In Kubernetes: service may not exist in the namespace or CoreDNS is down",
			},
			Impact:          "Cannot connect to the service by hostname; dependent operations fail",
			ResolutionSteps: []string{"Verify hostname: nslookup <hostname>", "Check /etc/resolv.conf for DNS server configuration", "In Kubernetes: verify service exists: kubectl get svc <name>", "Check CoreDNS health: kubectl get pods -n kube-system -l k8s-app=kube-dns", "Use IP address as temporary workaround"},
			Prevention:      "Validate hostnames in config; monitor DNS health; use service discovery",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
	}
}

func buildGenericAppEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "app-connection-refused", Category: "application", SubCategory: "generic",
			Keywords: []string{"connection refused", "econnrefused", "connect refused"},
			AntiWords: []string{"java", "python", "node", "go", "redis", "postgres", "mysql", "mongodb"},
			Severity: "high",
			RootCause: "Application cannot connect to a dependency — the target service is not listening on the expected port",
			Reasoning: []string{
				"Connection refused means the target host received the TCP SYN but nothing is listening",
				"The dependency may be down, restarting, or the port number is wrong",
				"Firewall resets can also manifest as connection refused",
			},
			Impact:          "All functionality depending on the unreachable service fails",
			ResolutionSteps: []string{"Check if target service is running: systemctl status <service> or docker ps", "Test connectivity: telnet <host> <port> or nc -zv <host> <port>", "Verify the host:port in application configuration or environment variables", "Check firewall rules: iptables -L -n | grep <port>", "Restart the target service if it is down"},
			Prevention:      "Implement health checks for dependencies; use circuit breaker pattern; add connection retry with backoff",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "app-connection-timeout", Category: "application", SubCategory: "generic",
			Keywords: []string{"connection timeout", "connect timeout", "timed out connecting"},
			AntiWords: []string{"read timeout", "socket timeout"},
			Severity: "high",
			RootCause: "TCP connection attempt timed out — the target host is unreachable or a firewall is silently dropping packets",
			Reasoning: []string{
				"Unlike connection refused, a timeout means no response at all — the SYN packet was lost",
				"Common causes: wrong IP, firewall dropping packets, network partition, or host is down",
				"The application waits for the full timeout period, wasting resources",
			},
			Impact:          "Requests hang for the timeout duration then fail; thread/connection pool may become saturated",
			ResolutionSteps: []string{"Check if host is reachable: ping <host>", "Trace the network path: traceroute <host>", "Check firewall rules for the port: nmap -p <port> <host>", "Verify the target IP/hostname is correct", "Reduce connection timeout to fail faster: typically 3-5 seconds is appropriate"},
			Prevention:      "Set short connection timeouts (3-5s); implement circuit breakers; verify network path for all dependencies",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "app-connection-reset", Category: "application", SubCategory: "generic",
			Keywords: []string{"connection reset by peer", "connection reset", "econnreset"},
			Severity: "high",
			RootCause: "The remote side forcefully closed the TCP connection by sending a RST packet",
			Reasoning: []string{
				"Connection reset indicates the remote server crashed, restarted, or hit a resource limit",
				"Load balancers reset connections when backends are unhealthy or idle timeout expires",
				"Firewalls may reset connections that exceed state table limits",
			},
			Impact:          "In-flight request fails; data may have been partially sent; client must retry",
			ResolutionSteps: []string{"Check target service logs for crashes or restarts", "Check load balancer idle timeout settings", "Verify keep-alive settings match between client and server", "Check firewall connection state table: conntrack -L | wc -l", "Implement automatic retry for idempotent operations"},
			Prevention:      "Align keep-alive timeouts; implement retry for transient errors; monitor connection reset rates",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "app-ssl-handshake-failure", Category: "application", SubCategory: "generic",
			Keywords: []string{"ssl handshake", "tls handshake", "handshake failure", "certificate expired"},
			Severity: "high",
			RootCause: "TLS/SSL handshake failed — certificate issue, protocol mismatch, or cipher incompatibility",
			Reasoning: []string{
				"TLS handshake failures block all encrypted communication to the endpoint",
				"Common causes: expired certificate, untrusted CA, hostname mismatch, or TLS version mismatch",
				"After a certificate expires, all clients fail simultaneously",
			},
			Impact:          "All HTTPS/TLS connections to the endpoint fail; services cannot communicate securely",
			ResolutionSteps: []string{"Check certificate: openssl s_client -connect <host>:<port> 2>/dev/null | openssl x509 -noout -dates -subject -issuer", "Verify certificate covers the hostname: check SAN (Subject Alternative Name)", "Check TLS version compatibility: openssl s_client -connect <host>:<port> -tls1_2", "Renew certificate if expired", "Check cipher suite compatibility: openssl s_client -connect <host>:<port> -cipher <suite>"},
			Prevention:      "Monitor certificate expiry 30+ days in advance; automate renewal; maintain a certificate inventory",
			BaseConfidence: 80, BaseRiskScore: 70,
		},
		{
			ID: "app-auth-failure-401", Category: "application", SubCategory: "generic",
			Keywords: []string{"401 unauthorized", "authentication failure", "auth failed", "invalid credentials", "token expired"},
			Severity: "high",
			RootCause: "Authentication failure — credentials, tokens, or API keys are invalid or expired",
			Reasoning: []string{
				"The service rejected authentication — this is not a connectivity issue",
				"Common causes: rotated API keys, expired JWT tokens, or wrong credentials in config",
				"If all requests suddenly fail with 401, a credential rotation likely happened",
			},
			Impact:          "All authenticated requests to the service fail; functionality requiring this service is broken",
			ResolutionSteps: []string{"Check if API keys or passwords were recently rotated", "Verify credentials in environment variables or secrets manager", "Check token expiry: decode JWT at jwt.io to check exp claim", "Regenerate API key if compromised or expired", "Check if the service account was deactivated or permissions changed"},
			Prevention:      "Automate credential rotation with advance notice; monitor 401 response rates; use short-lived tokens with auto-refresh",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "app-permission-denied-403", Category: "application", SubCategory: "generic",
			Keywords: []string{"403 forbidden", "permission denied", "access denied", "forbidden"},
			AntiWords: []string{"filesystem", "file permission", "linux permission"},
			Severity: "medium",
			RootCause: "Authorization failure — the authenticated identity lacks permission for the requested operation",
			Reasoning: []string{
				"Authentication succeeded but the user/service does not have the required permissions",
				"Common after role changes, policy updates, or resource permission modifications",
				"IAM policy changes can take minutes to propagate in cloud environments",
			},
			Impact:          "Specific operations are blocked; the service can still perform other authorized operations",
			ResolutionSteps: []string{"Identify which permission is needed from the 403 response body", "Check IAM/RBAC policies for the service account or user", "Grant the required permission: follow least-privilege principle", "If cloud: check resource-level policies (S3 bucket policy, GCS IAM)", "Wait 5-10 minutes for IAM policy propagation in cloud environments"},
			Prevention:      "Test IAM policies in staging before production; audit permission changes; use infrastructure-as-code for policies",
			BaseConfidence: 70, BaseRiskScore: 45,
		},
		{
			ID: "app-rate-limited-429", Category: "application", SubCategory: "generic",
			Keywords: []string{"429 too many requests", "rate limited", "throttled", "rate limit exceeded"},
			Severity: "medium",
			RootCause: "API rate limit exceeded — the service is sending too many requests",
			Reasoning: []string{
				"The upstream API has a rate limit and the application is exceeding it",
				"Retry storms can amplify rate limiting — failed requests retry immediately and hit the limit again",
				"Bursty traffic patterns can exceed per-second limits even when average is within budget",
			},
			Impact:          "Requests to the rate-limited API fail; dependent functionality degrades",
			ResolutionSteps: []string{"Check the Retry-After header in the 429 response for wait time", "Implement exponential backoff: wait 2^n seconds between retries", "Add request queuing or batching to smooth out burst traffic", "Reduce request rate by caching responses", "Request a higher rate limit from the API provider if legitimately needed"},
			Prevention:      "Implement client-side rate limiting; use exponential backoff; cache responses; monitor request rates",
			BaseConfidence: 70, BaseRiskScore: 45,
		},
		{
			ID: "app-internal-server-error-500", Category: "application", SubCategory: "generic",
			Keywords: []string{"500 internal server error", "internal server error", "500 error"},
			Severity: "high",
			RootCause: "Upstream service returned HTTP 500 — an unhandled error occurred on the server",
			Reasoning: []string{
				"500 errors indicate a bug or unhandled exception in the upstream service",
				"The error is on the server side, not the client side",
				"If intermittent: may be a race condition or resource exhaustion; if constant: a bug or outage",
			},
			Impact:          "Requests to the upstream fail; functionality depending on it is broken",
			ResolutionSteps: []string{"Check the upstream service error logs for the stack trace", "Look for recent deployments to the upstream service", "Check if the 500 is intermittent or constant", "If intermittent: check for resource exhaustion (DB connections, memory, threads)", "If constant: rollback the upstream service to the previous version"},
			Prevention:      "Add comprehensive error handling; implement canary deployments; monitor 5xx rates per service",
			BaseConfidence: 65, BaseRiskScore: 60,
		},
		{
			ID: "app-bad-gateway-502", Category: "application", SubCategory: "generic",
			Keywords: []string{"502 bad gateway", "bad gateway", "502"},
			Severity: "high",
			RootCause: "Load balancer or proxy received an invalid response from the upstream service",
			Reasoning: []string{
				"502 means the proxy connected to the backend but got a malformed response",
				"Common causes: backend crashed mid-request, backend not ready, or protocol mismatch",
				"The proxy (nginx, ALB, ingress) is working — the issue is the backend behind it",
			},
			Impact:          "Requests fail at the proxy layer; end users see 502 errors",
			ResolutionSteps: []string{"Check backend service health: is it running and responding?", "Check proxy/load balancer logs for connection errors to backends", "Verify backend health check is passing", "Check if backend process crashed: systemctl status <service> or kubectl get pods", "Restart backend service if it is in a bad state"},
			Prevention:      "Implement proper health checks; use graceful shutdown in backends; configure proxy timeouts appropriately",
			BaseConfidence: 70, BaseRiskScore: 65,
		},
		{
			ID: "app-service-unavailable-503", Category: "application", SubCategory: "generic",
			Keywords: []string{"503 service unavailable", "service unavailable", "503"},
			Severity: "high",
			RootCause: "Service is temporarily unavailable — typically overloaded or in maintenance",
			Reasoning: []string{
				"503 indicates the server cannot handle the request right now but may recover",
				"Common causes: all backends down, circuit breaker open, or maintenance mode",
				"Unlike 500, 503 is often intentional — the service is protecting itself from overload",
			},
			Impact:          "All requests to the service fail; users experience outage",
			ResolutionSteps: []string{"Check if the service is in maintenance mode", "Check backend instance health: are pods/instances running?", "Check if a circuit breaker tripped: review circuit breaker metrics", "Scale up backend instances if overloaded", "Check if a deployment is in progress and wait for it to complete"},
			Prevention:      "Implement auto-scaling; use circuit breakers with sensible thresholds; add health checks; implement graceful degradation",
			BaseConfidence: 70, BaseRiskScore: 65,
		},
		{
			ID: "app-gateway-timeout-504", Category: "application", SubCategory: "generic",
			Keywords: []string{"504 gateway timeout", "gateway timeout", "504"},
			Severity: "high",
			RootCause: "The proxy/load balancer timed out waiting for a response from the backend",
			Reasoning: []string{
				"504 means the backend did not respond within the proxy's configured timeout",
				"The backend is likely processing a slow query, waiting on a dependency, or hung",
				"The proxy timeout is typically 60 seconds — if the backend takes longer, it gets a 504",
			},
			Impact:          "Long-running requests fail; users see timeout errors",
			ResolutionSteps: []string{"Check backend service response times: are requests slow?", "Increase proxy timeout if long requests are expected (nginx: proxy_read_timeout)", "Check backend for slow database queries or dependency timeouts", "Move long operations to async processing with a job queue", "Check if the backend is deadlocked or GC-paused"},
			Prevention:      "Optimize slow operations; use async processing for long tasks; set appropriate proxy timeouts; add request timeout monitoring",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "app-file-descriptor-exhaustion", Category: "application", SubCategory: "generic",
			Keywords: []string{"too many open files", "file descriptor", "ulimit", "emfile", "enfile"},
			AntiWords: []string{"node", "go"},
			Severity: "high",
			RootCause: "Process has exhausted its file descriptor limit — cannot open new files or sockets",
			Reasoning: []string{
				"Every open file, socket, and pipe uses a file descriptor",
				"The default ulimit (1024) is often too low for server processes",
				"Leaked connections or unclosed files gradually exhaust the limit",
			},
			Impact:          "Cannot open new files or network connections; service degrades and fails",
			ResolutionSteps: []string{"Check current limit and usage: cat /proc/<PID>/limits | grep 'Max open files' && ls /proc/<PID>/fd | wc -l", "Increase limit: ulimit -n 65536 (temporary) or edit /etc/security/limits.conf (permanent)", "For systemd: add LimitNOFILE=65536 to the service unit", "Find leaked file descriptors: lsof -p <PID> | sort -k9 | tail -20", "Fix leaked connections in application code"},
			Prevention:      "Set high ulimit for server processes; audit code for resource leaks; monitor open FD count",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "app-segfault", Category: "application", SubCategory: "generic",
			Keywords: []string{"segfault", "segmentation fault", "core dumped", "sigsegv"},
			Severity: "critical",
			RootCause: "Process received SIGSEGV — segmentation fault from invalid memory access",
			Reasoning: []string{
				"The process accessed memory that it is not allowed to (null pointer, freed memory, stack overflow)",
				"Common in C/C++ applications, native library bindings, or JNI/CGo code",
				"A core dump may have been generated for post-mortem analysis",
			},
			Impact:          "Process crash; all in-flight operations are lost; requires restart",
			ResolutionSteps: []string{"Check for core dump: ls /var/crash/ or /tmp/core.*", "Analyze core dump: gdb <program> <core-dump>", "Check dmesg for the fault details: dmesg | grep segfault", "If in a native library: check library version compatibility", "Enable core dumps: ulimit -c unlimited && sysctl kernel.core_pattern=/tmp/core.%e.%p"},
			Prevention:      "Use memory-safe languages; run with AddressSanitizer in testing; keep native libraries updated",
			BaseConfidence: 85, BaseRiskScore: 80,
		},
		{
			ID: "app-dns-failure", Category: "application", SubCategory: "generic",
			Keywords: []string{"dns resolution failure", "name resolution failed", "could not resolve host"},
			AntiWords: []string{"kubernetes", "coredns", "node", "go"},
			Severity: "critical",
			RootCause: "DNS resolution failed — the application cannot resolve hostnames to IP addresses",
			Reasoning: []string{
				"DNS failures affect all hostname-based connections across the application",
				"The DNS server may be unreachable, overloaded, or misconfigured",
				"Cached DNS entries expire after TTL, so failures appear with a delay after DNS goes down",
			},
			Impact:          "All connections using hostnames fail; virtually every external dependency becomes unreachable",
			ResolutionSteps: []string{"Test DNS: dig <hostname> @<dns_server>", "Check resolv.conf: cat /etc/resolv.conf", "Try public DNS: dig <hostname> @8.8.8.8", "Restart DNS resolver: systemctl restart systemd-resolved", "Check if DNS port (UDP 53) is blocked by firewall"},
			Prevention:      "Use multiple DNS servers; implement DNS caching; monitor DNS resolution latency",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
	}
}
