package services

func buildPostgresEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "pg-conn-refused", Category: "database", SubCategory: "postgres",
			Keywords: []string{"connection refused 5432", "postgres connection refused", "could not connect to server postgres"},
			Severity: "critical",
			RootCause: "PostgreSQL is not accepting connections — the database server may be down",
			Reasoning: []string{
				"Nothing is listening on port 5432, which means the PostgreSQL process is not running",
				"Could be a crash, failed restart, or the server was intentionally stopped",
				"All services depending on this database are affected simultaneously",
			},
			Impact:          "Complete database outage; all queries fail; application cannot read or write data",
			ResolutionSteps: []string{"Check PostgreSQL status: systemctl status postgresql", "Check for crash logs: tail -100 /var/log/postgresql/postgresql-*-main.log", "Restart PostgreSQL: systemctl restart postgresql", "If crash-looping: check disk space (df -h) and memory (free -h)", "Check pg_hba.conf for connection restrictions: cat /etc/postgresql/*/main/pg_hba.conf"},
			Prevention:      "Monitor PostgreSQL process health; set up automatic failover with Patroni/repmgr; use connection pooling (PgBouncer)",
			BaseConfidence: 90, BaseRiskScore: 90,
		},
		{
			ID: "pg-too-many-connections", Category: "database", SubCategory: "postgres",
			Keywords: []string{"too many connections", "remaining connection slots", "max_connections postgres"},
			Severity: "critical",
			RootCause: "PostgreSQL has reached its maximum connection limit — no new connections can be established",
			Reasoning: []string{
				"Default max_connections is 100, which is easily exhausted without connection pooling",
				"Each connection consumes ~10MB of memory plus backend process overhead",
				"Connection leaks, pool misconfigurations, or traffic spikes cause exhaustion",
			},
			Impact:          "New queries and connections are rejected; applications fail to connect; users see errors",
			ResolutionSteps: []string{"Check current connections: SELECT count(*), state FROM pg_stat_activity GROUP BY state", "Kill idle connections: SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state = 'idle' AND query_start < now() - interval '5 minutes'", "Increase max_connections in postgresql.conf (requires restart): max_connections = 200", "Deploy PgBouncer as connection pooler: pgbouncer -d pgbouncer.ini", "Check for connection leaks in application code: ensure connections are returned to pool"},
			Prevention:      "Use PgBouncer for connection pooling; set idle_in_transaction_session_timeout; monitor connection count",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "pg-auth-failed", Category: "database", SubCategory: "postgres",
			Keywords: []string{"password authentication failed", "auth failed postgres", "pg_hba.conf rejects"},
			Severity: "high",
			RootCause: "PostgreSQL authentication failed — wrong password or pg_hba.conf rejects the connection method",
			Reasoning: []string{
				"The credentials in the application config do not match the PostgreSQL user password",
				"pg_hba.conf may require a different authentication method (peer, md5, scram-sha-256)",
				"This may follow a password rotation that was not propagated to all services",
			},
			Impact:          "Applications using the failed credentials cannot connect; service outage for affected apps",
			ResolutionSteps: []string{"Verify the password in application config matches PostgreSQL: PGPASSWORD=<pwd> psql -h <host> -U <user> <db>", "Check pg_hba.conf: cat /etc/postgresql/*/main/pg_hba.conf | grep -v '^#'", "Reset the password: ALTER USER <username> PASSWORD '<new_password>'", "Reload pg_hba.conf after changes: SELECT pg_reload_conf()", "Check if password was recently rotated in secrets manager and update application config"},
			Prevention:      "Use secrets manager with automatic rotation; synchronize password changes across all services; test auth before cutover",
			BaseConfidence: 80, BaseRiskScore: 65,
		},
		{
			ID: "pg-database-not-exist", Category: "database", SubCategory: "postgres",
			Keywords: []string{"database does not exist", "database not found postgres", "fatal: database"},
			Severity: "high",
			RootCause: "PostgreSQL connection failed because the specified database does not exist",
			Reasoning: []string{
				"The database name in the connection string is wrong or the database was dropped",
				"May occur after a migration or environment setup issue",
				"Check if the database name uses uppercase or special characters that require quoting",
			},
			Impact:          "Application cannot connect at all; complete functionality failure for affected service",
			ResolutionSteps: []string{"List existing databases: psql -l", "Create the database if missing: CREATE DATABASE <name>", "Check connection string in application config for typos", "If migrating: ensure the database was created before running migrations", "Check if the database was accidentally dropped: review PostgreSQL logs"},
			Prevention:      "Include database creation in deployment scripts; protect production databases with pg_hba.conf restrictions",
			BaseConfidence: 80, BaseRiskScore: 60,
		},
		{
			ID: "pg-relation-not-exist", Category: "database", SubCategory: "postgres",
			Keywords: []string{"relation does not exist", "table not found postgres", "undefined table"},
			Severity: "high",
			RootCause: "Query references a table or view that does not exist in the database",
			Reasoning: []string{
				"The table was not created (migration not run), was dropped, or the schema is wrong",
				"Search_path may not include the schema where the table lives",
				"Case-sensitive table names require double-quoting in queries",
			},
			Impact:          "Queries referencing this table fail; specific functionality is broken",
			ResolutionSteps: []string{"Check if table exists: \\dt <table_name> or SELECT * FROM information_schema.tables WHERE table_name = '<name>'", "Run pending migrations: alembic upgrade head / migrate / flyway migrate", "Check search_path: SHOW search_path", "If wrong schema: SET search_path TO <schema>,public", "Check for case sensitivity: table names are lowercase unless double-quoted"},
			Prevention:      "Run migrations as part of deployment pipeline; validate schema after migration; use CI checks for SQL syntax",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "pg-deadlock", Category: "database", SubCategory: "postgres",
			Keywords: []string{"deadlock detected", "deadlock postgres"},
			Severity: "high",
			RootCause: "PostgreSQL detected a deadlock between two or more transactions",
			Reasoning: []string{
				"Two transactions each hold locks that the other needs, creating a circular wait",
				"PostgreSQL automatically aborts one transaction to break the deadlock",
				"The aborted transaction receives an error; the other proceeds normally",
			},
			Impact:          "One transaction is rolled back with an error; retry logic can usually recover",
			ResolutionSteps: []string{"Check deadlock details in PostgreSQL logs: grep -i deadlock /var/log/postgresql/*.log | tail -20", "Review the two queries involved to understand the lock ordering conflict", "Ensure all transactions access tables in the same order (e.g., always lock table A before table B)", "Add retry logic in the application for deadlock errors", "Use SELECT ... FOR UPDATE SKIP LOCKED for queue-like patterns"},
			Prevention:      "Standardize lock ordering across the application; add retry logic for deadlock errors; use advisory locks for complex coordination",
			BaseConfidence: 80, BaseRiskScore: 55,
		},
		{
			ID: "pg-out-of-shared-memory", Category: "database", SubCategory: "postgres",
			Keywords: []string{"out of shared memory", "shared memory postgres", "shmem"},
			Severity: "critical",
			RootCause: "PostgreSQL ran out of shared memory — cannot allocate resources for locks or buffers",
			Reasoning: []string{
				"Shared memory is used for shared_buffers, lock tables, and inter-process communication",
				"Too many concurrent locks (large batch operations) can exhaust the lock table",
				"shared_buffers may be set too high relative to available system memory",
			},
			Impact:          "Queries fail; new connections may be rejected; database becomes partially unusable",
			ResolutionSteps: []string{"Check shared memory settings: SHOW shared_buffers; SHOW max_locks_per_transaction", "If lock table full: reduce batch sizes in application queries", "Increase max_locks_per_transaction in postgresql.conf (requires restart)", "Check system shared memory: sysctl kernel.shmmax", "Increase kernel.shmmax: sysctl -w kernel.shmmax=<bytes>"},
			Prevention:      "Size shared_buffers to 25% of RAM; set max_locks_per_transaction based on workload; monitor shared memory usage",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "pg-standby-conflict", Category: "database", SubCategory: "postgres",
			Keywords: []string{"canceling statement due to conflict", "conflict with recovery", "standby conflict"},
			Severity: "medium",
			RootCause: "Query on PostgreSQL replica was cancelled because it conflicts with WAL replay",
			Reasoning: []string{
				"Hot standby must replay WAL records to stay in sync with the primary",
				"If a query on the standby holds a snapshot that conflicts with a WAL operation, the query is cancelled",
				"This is more common with long-running analytical queries on replicas",
			},
			Impact:          "Read queries on the replica are cancelled; application sees query errors",
			ResolutionSteps: []string{"Increase standby delay: SET max_standby_streaming_delay = '60s'", "Enable hot_standby_feedback on the replica: ALTER SYSTEM SET hot_standby_feedback = on", "Use a dedicated replica for analytics with higher delay tolerance", "Optimize long-running queries to reduce snapshot hold time", "Reload configuration: SELECT pg_reload_conf()"},
			Prevention:      "Set hot_standby_feedback=on; use dedicated replicas for analytics; keep analytical queries short",
			BaseConfidence: 70, BaseRiskScore: 45,
		},
		{
			ID: "pg-replication-lag", Category: "database", SubCategory: "postgres",
			Keywords: []string{"replication lag", "replication delay", "pg_stat_replication", "replica lag postgres"},
			Severity: "high",
			RootCause: "PostgreSQL replication is lagging — the replica is behind the primary",
			Reasoning: []string{
				"Replication lag means reads from the replica return stale data",
				"Common causes: network bandwidth between primary and replica, slow disk on replica, or heavy write load",
				"Large transactions (bulk imports) can cause temporary replication lag spikes",
			},
			Impact:          "Read queries on replica return stale data; failover to replica would lose recent writes",
			ResolutionSteps: []string{"Check lag: SELECT now() - pg_last_xact_replay_timestamp() AS replication_lag", "On primary: SELECT pid, client_addr, state, sent_lsn, write_lsn, replay_lsn FROM pg_stat_replication", "Check network bandwidth: iperf3 -c <replica_host>", "Check replica disk I/O: iostat -x 1 5 on the replica", "If chronic: increase wal_sender_timeout and consider faster network/disk"},
			Prevention:      "Monitor replication lag; provision fast disks on replicas; set up lag alerts at > 10s",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "pg-disk-full", Category: "database", SubCategory: "postgres",
			Keywords: []string{"no space left on device postgres", "disk full postgres", "could not write to file postgres"},
			Severity: "critical",
			RootCause: "PostgreSQL data directory disk is full — all writes fail",
			Reasoning: []string{
				"PostgreSQL needs disk space for WAL, data files, temp files, and pg_xlog/pg_wal",
				"Without space for WAL, the database cannot commit transactions",
				"Disk full during a checkpoint can cause data corruption",
			},
			Impact:          "All write operations fail; database may crash; risk of data corruption",
			ResolutionSteps: []string{"Check disk: df -h $(SHOW data_directory)", "Clear WAL archives if using archiving: find /archive -name '*.gz' -mtime +7 -delete", "Remove old backups from the data disk", "Vacuum to reclaim space: VACUUM FULL <large_table> (requires exclusive lock)", "Expand the data volume: resize2fs /dev/<device> (after expanding underlying storage)"},
			Prevention:      "Monitor data directory disk usage; separate WAL to its own volume; automate WAL archival cleanup",
			BaseConfidence: 90, BaseRiskScore: 95,
		},
		{
			ID: "pg-slow-query", Category: "database", SubCategory: "postgres",
			Keywords: []string{"slow query postgres", "query time exceeded", "statement timeout postgres"},
			Severity: "medium",
			RootCause: "PostgreSQL query is running longer than expected — possible missing index or table scan",
			Reasoning: []string{
				"A query exceeding a few seconds in OLTP workloads usually indicates a missing index",
				"The query planner may be choosing a sequential scan due to stale statistics",
				"Large result sets being materialized in memory can also cause slow queries",
			},
			Impact:          "Slow queries hold connections longer, reducing pool throughput; user-facing latency increases",
			ResolutionSteps: []string{"Identify the slow query: SELECT pid, now() - query_start AS duration, query FROM pg_stat_activity WHERE state = 'active' ORDER BY duration DESC LIMIT 10", "Analyze the query plan: EXPLAIN (ANALYZE, BUFFERS) <query>", "Check for missing indexes: look for Seq Scan on large tables in the plan", "Create an index: CREATE INDEX CONCURRENTLY idx_name ON table(column)", "Update statistics: ANALYZE <table>"},
			Prevention:      "Enable pg_stat_statements; set log_min_duration_statement=1000; review slow query logs regularly",
			BaseConfidence: 70, BaseRiskScore: 50,
		},
		{
			ID: "pg-idle-in-transaction", Category: "database", SubCategory: "postgres",
			Keywords: []string{"idle in transaction", "long transaction", "transaction idle postgres"},
			Severity: "medium",
			RootCause: "A PostgreSQL session has been idle inside a transaction for too long, holding locks and preventing VACUUM",
			Reasoning: []string{
				"An idle-in-transaction session holds locks and prevents autovacuum from cleaning dead tuples",
				"Common causes: application code that opens a transaction but forgets to commit/rollback",
				"Network issues between application and database can leave transactions hanging",
			},
			Impact:          "Table bloat from blocked autovacuum; locks may block other queries; connection pool slot wasted",
			ResolutionSteps: []string{"Find idle transactions: SELECT pid, now() - xact_start AS duration, query FROM pg_stat_activity WHERE state = 'idle in transaction' ORDER BY duration DESC", "Kill old idle transactions: SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state = 'idle in transaction' AND xact_start < now() - interval '10 minutes'", "Set timeout: ALTER SYSTEM SET idle_in_transaction_session_timeout = '5min'", "Reload config: SELECT pg_reload_conf()", "Fix application code to properly commit/rollback transactions"},
			Prevention:      "Set idle_in_transaction_session_timeout=300000; use connection pool health checks; audit transaction management in code",
			BaseConfidence: 70, BaseRiskScore: 50,
		},
		{
			ID: "pg-lock-timeout", Category: "database", SubCategory: "postgres",
			Keywords: []string{"lock timeout", "lock wait timeout postgres", "waiting for lock postgres"},
			Severity: "high",
			RootCause: "PostgreSQL query timed out waiting to acquire a lock held by another transaction",
			Reasoning: []string{
				"Another transaction is holding the required lock (row lock, table lock, or advisory lock)",
				"DDL operations like ALTER TABLE acquire exclusive locks that block all queries",
				"Long-running transactions can hold locks for extended periods",
			},
			Impact:          "Blocked queries fail or hang; application requests time out; potential cascading timeouts",
			ResolutionSteps: []string{"Find blocking queries: SELECT blocked.pid AS blocked_pid, blocked.query AS blocked_query, blocking.pid AS blocking_pid, blocking.query AS blocking_query FROM pg_stat_activity blocked JOIN pg_locks bl ON bl.pid = blocked.pid JOIN pg_locks bk ON bk.pid != bl.pid AND bk.relation = bl.relation JOIN pg_stat_activity blocking ON blocking.pid = bk.pid WHERE NOT bl.granted", "Kill the blocking query: SELECT pg_terminate_backend(<blocking_pid>)", "Set lock_timeout: SET lock_timeout = '5s'", "Use CONCURRENTLY for index creation: CREATE INDEX CONCURRENTLY ...", "Schedule DDL operations during maintenance windows"},
			Prevention:      "Set lock_timeout globally; use CREATE INDEX CONCURRENTLY; avoid DDL during peak traffic; keep transactions short",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "pg-connection-pool-pgbouncer", Category: "database", SubCategory: "postgres",
			Keywords: []string{"pgbouncer", "connection pool exhausted postgres", "pgbouncer pool full"},
			Severity: "high",
			RootCause: "PgBouncer connection pool is exhausted — no available connections for new queries",
			Reasoning: []string{
				"All pooled connections are in use by active queries",
				"Slow queries hold connections longer, reducing effective pool size",
				"PgBouncer pool size may be too small for the current workload",
			},
			Impact:          "New database queries are queued or rejected; application response times increase",
			ResolutionSteps: []string{"Check pool status: SHOW POOLS in pgbouncer admin console", "Check server connections: SHOW SERVERS in pgbouncer admin console", "Increase pool size: edit default_pool_size in pgbouncer.ini", "Kill long-running queries on the database side", "Restart PgBouncer: systemctl restart pgbouncer"},
			Prevention:      "Monitor PgBouncer pool utilization; size pools based on peak workload; optimize slow queries",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "pg-wal-archive-failed", Category: "database", SubCategory: "postgres",
			Keywords: []string{"archive command failed", "wal archive failed", "wal archiving postgres"},
			Severity: "high",
			RootCause: "PostgreSQL WAL archiving is failing — cannot send WAL segments to the archive destination",
			Reasoning: []string{
				"WAL archiving is required for point-in-time recovery (PITR)",
				"If archiving fails, pg_wal directory fills up, eventually causing disk full",
				"Common causes: archive destination unreachable, disk full at destination, or permissions issue",
			},
			Impact:          "PITR capability is lost; pg_wal directory may fill up and crash the database",
			ResolutionSteps: []string{"Check archive status: SELECT * FROM pg_stat_archiver", "Test archive command manually: run the archive_command with a WAL file", "Check archive destination: verify disk space and permissions", "Fix archive_command in postgresql.conf", "If pg_wal is growing: free space urgently and fix archiving"},
			Prevention:      "Monitor pg_stat_archiver; alert on archive failures; test archive destination connectivity",
			BaseConfidence: 75, BaseRiskScore: 70,
		},
		{
			ID: "pg-sequence-overflow", Category: "database", SubCategory: "postgres",
			Keywords: []string{"sequence overflow", "nextval out of range", "integer out of range postgres"},
			Severity: "critical",
			RootCause: "Integer primary key sequence has overflowed — cannot generate new IDs",
			Reasoning: []string{
				"32-bit integer (SERIAL) max is 2,147,483,647 — exhausted after ~2 billion inserts",
				"This prevents any new rows from being inserted into the table",
				"The fix requires a schema change (ALTER to BIGSERIAL) which takes a lock on the table",
			},
			Impact:          "Cannot insert new rows into the affected table; write operations fail with an error",
			ResolutionSteps: []string{"Identify the sequence: SELECT * FROM information_schema.sequences WHERE sequence_name LIKE '%<table>%'", "Check current value: SELECT last_value FROM <sequence_name>", "Alter column to BIGINT: ALTER TABLE <table> ALTER COLUMN id TYPE BIGINT", "Alter sequence: ALTER SEQUENCE <sequence_name> AS BIGINT", "If table is huge: use pg_repack for online column type change to avoid long lock"},
			Prevention:      "Use BIGSERIAL (BIGINT) for primary keys from the start; monitor sequence utilization",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "pg-index-corruption", Category: "database", SubCategory: "postgres",
			Keywords: []string{"invalid page", "index corrupt", "relation invalid postgres"},
			Severity: "critical",
			RootCause: "PostgreSQL index corruption detected — queries using this index may return wrong results",
			Reasoning: []string{
				"Index corruption can be caused by hardware failures, filesystem bugs, or PostgreSQL bugs",
				"Queries using the corrupt index silently return incorrect results",
				"Data in the table itself may still be correct even if the index is corrupt",
			},
			Impact:          "Queries may return incorrect results; data integrity is compromised",
			ResolutionSteps: []string{"Verify corruption: SELECT * FROM pg_amcheck.check_index('<index_name>')", "Rebuild the index: REINDEX TABLE <table_name>", "For concurrent rebuild: REINDEX TABLE CONCURRENTLY <table_name> (PostgreSQL 12+)", "Check hardware: run SMART test on disk, check ECC memory", "If data corruption: restore from backup and replay WAL"},
			Prevention:      "Use ECC memory; monitor disk health; enable data checksums at initdb; run amcheck periodically",
			BaseConfidence: 85, BaseRiskScore: 90,
		},
		{
			ID: "pg-xid-wraparound", Category: "database", SubCategory: "postgres",
			Keywords: []string{"transaction id wraparound", "xid wraparound", "vacuum to prevent wraparound"},
			Severity: "critical",
			RootCause: "PostgreSQL is at risk of transaction ID wraparound — data will become invisible without VACUUM FREEZE",
			Reasoning: []string{
				"PostgreSQL uses 32-bit transaction IDs that wrap around after ~2 billion transactions",
				"Without VACUUM FREEZE, old tuples become invisible (appears as data loss)",
				"At 40 million transactions remaining, PostgreSQL enters read-only mode to prevent corruption",
			},
			Impact:          "Data becomes invisible; database may enter read-only mode; effectively a data loss scenario",
			ResolutionSteps: []string{"Check current XID age: SELECT datname, age(datfrozenxid) FROM pg_database ORDER BY age DESC", "Run vacuum freeze on affected databases: VACUUM FREEZE", "For specific tables: VACUUM FREEZE <table_name>", "Tune autovacuum: SET autovacuum_freeze_max_age = 200000000", "If in single-user mode: pg_ctl stop && postgres --single <database> then VACUUM FREEZE"},
			Prevention:      "Tune autovacuum aggressively; monitor datfrozenxid age; alert at > 1 billion age",
			BaseConfidence: 90, BaseRiskScore: 95,
		},
		{
			ID: "pg-checkpoint-warning", Category: "database", SubCategory: "postgres",
			Keywords: []string{"checkpoint occurring too frequently", "checkpoint warning postgres", "checkpoints are occurring too frequently"},
			Severity: "medium",
			RootCause: "PostgreSQL checkpoints are occurring too frequently, indicating high write load or undersized WAL",
			Reasoning: []string{
				"Frequent checkpoints increase I/O load and WAL write amplification",
				"Default max_wal_size (1GB) may be too small for write-heavy workloads",
				"This degrades performance but is not an immediate risk to data integrity",
			},
			Impact:          "Increased disk I/O; slightly higher write latency; more WAL generated",
			ResolutionSteps: []string{"Check checkpoint frequency: SELECT * FROM pg_stat_bgwriter", "Increase max_wal_size: ALTER SYSTEM SET max_wal_size = '4GB'", "Increase checkpoint_completion_target: ALTER SYSTEM SET checkpoint_completion_target = 0.9", "Reload config: SELECT pg_reload_conf()", "Check for bulk write operations that could be batched"},
			Prevention:      "Set max_wal_size based on write volume; tune checkpoint_completion_target=0.9; monitor checkpoint frequency",
			BaseConfidence: 65, BaseRiskScore: 40,
		},
	}
}

func buildMySQLEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "mysql-too-many-connections", Category: "database", SubCategory: "mysql",
			Keywords: []string{"too many connections mysql", "max_connections mysql", "connection limit mysql"},
			Severity: "critical",
			RootCause: "MySQL has reached its maximum connection limit — new connections are rejected",
			Reasoning: []string{
				"Default max_connections is 151, which is quickly exhausted without pooling",
				"Each connection uses memory for the thread stack and per-session buffers",
				"Connection leaks or slow queries holding connections cause pool exhaustion",
			},
			Impact:          "New database connections are rejected; applications fail to connect; user-facing errors",
			ResolutionSteps: []string{"Check connections: SHOW STATUS LIKE 'Threads_connected'", "Increase limit: SET GLOBAL max_connections = 300", "Kill idle connections: SELECT CONCAT('KILL ', id, ';') FROM information_schema.processlist WHERE command = 'Sleep' AND time > 300", "Deploy connection pooler (ProxySQL, MySQL Router)", "Fix connection leaks in application code"},
			Prevention:      "Use connection pooling; set wait_timeout to close idle connections; monitor connection count",
			BaseConfidence: 85, BaseRiskScore: 80,
		},
		{
			ID: "mysql-lock-wait-timeout", Category: "database", SubCategory: "mysql",
			Keywords: []string{"lock wait timeout exceeded", "lock wait timeout mysql", "innodb lock timeout"},
			Severity: "high",
			RootCause: "MySQL InnoDB lock wait timeout exceeded — a transaction is blocking another",
			Reasoning: []string{
				"A query waited longer than innodb_lock_wait_timeout (default 50s) for a row lock",
				"The blocking transaction is holding a lock and not releasing it",
				"Common with long-running UPDATE/DELETE statements or forgotten transactions",
			},
			Impact:          "Blocked queries fail; application requests time out; user experience degraded",
			ResolutionSteps: []string{"Find blocking transactions: SELECT * FROM information_schema.innodb_lock_waits", "Show lock details: SHOW ENGINE INNODB STATUS (look for LATEST DETECTED DEADLOCK)", "Kill blocking query: KILL <processlist_id>", "Increase timeout: SET GLOBAL innodb_lock_wait_timeout = 120", "Optimize the blocking query to hold locks for less time"},
			Prevention:      "Keep transactions short; avoid SELECT ... FOR UPDATE on large result sets; use READ COMMITTED isolation when possible",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "mysql-deadlock", Category: "database", SubCategory: "mysql",
			Keywords: []string{"deadlock found mysql", "deadlock mysql", "innodb deadlock"},
			Severity: "high",
			RootCause: "MySQL detected a deadlock between two transactions",
			Reasoning: []string{
				"Two transactions each hold locks needed by the other, creating circular wait",
				"InnoDB automatically rolls back the smaller transaction to break the deadlock",
				"The application receives an error for the rolled-back transaction",
			},
			Impact:          "One transaction is rolled back; retry logic can typically recover",
			ResolutionSteps: []string{"Check deadlock details: SHOW ENGINE INNODB STATUS (search for LATEST DETECTED DEADLOCK)", "Add retry logic in application for deadlock errors (MySQL error 1213)", "Ensure transactions access tables in consistent order", "Keep transactions as short as possible to reduce lock hold time", "Consider using SELECT ... FOR UPDATE SKIP LOCKED"},
			Prevention:      "Standardize table access order; keep transactions short; add automatic retry for deadlock errors",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "mysql-table-full", Category: "database", SubCategory: "mysql",
			Keywords: []string{"table is full", "table full mysql", "innodb tablespace full"},
			Severity: "critical",
			RootCause: "MySQL table or tablespace is full — cannot insert new rows",
			Reasoning: []string{
				"InnoDB tablespace or data directory disk is full",
				"If using innodb_file_per_table: the individual .ibd file cannot grow",
				"Temp table space may also fill up during large sorts or joins",
			},
			Impact:          "All inserts and updates to the affected table fail; application write operations break",
			ResolutionSteps: []string{"Check disk space: df -h", "Check InnoDB space: SELECT * FROM information_schema.innodb_tablespaces", "Free space: OPTIMIZE TABLE <table_name> (reclaims fragmented space)", "Delete unnecessary data or archive old records", "Expand disk or tablespace"},
			Prevention:      "Monitor table sizes and disk space; archive old data regularly; use partitioning for large tables",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "mysql-max-packet", Category: "database", SubCategory: "mysql",
			Keywords: []string{"max_allowed_packet", "packet bigger than", "packet too large mysql"},
			Severity: "medium",
			RootCause: "MySQL query or result exceeds max_allowed_packet size",
			Reasoning: []string{
				"Default max_allowed_packet is 64MB; large BLOBs or batch inserts can exceed this",
				"Replication also uses packets — if the primary has a larger setting, replication breaks",
				"This is a configuration issue, not a data corruption issue",
			},
			Impact:          "The specific query fails; large inserts or reads are rejected",
			ResolutionSteps: []string{"Check current value: SHOW VARIABLES LIKE 'max_allowed_packet'", "Increase: SET GLOBAL max_allowed_packet = 256*1024*1024", "Set in my.cnf: max_allowed_packet = 256M", "Ensure primary and replica have the same setting", "Consider using LOAD DATA INFILE for large batch inserts"},
			Prevention:      "Set max_allowed_packet to 256M for all servers; keep primary/replica settings in sync",
			BaseConfidence: 70, BaseRiskScore: 40,
		},
		{
			ID: "mysql-host-blocked", Category: "database", SubCategory: "mysql",
			Keywords: []string{"host is blocked", "max_connect_errors", "blocked mysql"},
			Severity: "high",
			RootCause: "MySQL blocked a host because it exceeded max_connect_errors (too many failed connection attempts)",
			Reasoning: []string{
				"After max_connect_errors (default 100) failed connections, MySQL blocks the host entirely",
				"This can happen from application connection errors, not just malicious attempts",
				"The block persists until FLUSH HOSTS is run or mysqld is restarted",
			},
			Impact:          "All connections from the blocked host are rejected; application on that host has complete DB outage",
			ResolutionSteps: []string{"Unblock the host: FLUSH HOSTS", "Increase limit: SET GLOBAL max_connect_errors = 10000", "Check why connections were failing in the first place (auth errors, network issues)", "Set in my.cnf: max_connect_errors = 10000", "Fix the root cause of connection failures"},
			Prevention:      "Set max_connect_errors high (10000+); fix authentication issues promptly; use connection pooling",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "mysql-replication-lag", Category: "database", SubCategory: "mysql",
			Keywords: []string{"replication lag mysql", "seconds behind master", "slave lag mysql"},
			Severity: "high",
			RootCause: "MySQL replication slave/replica is lagging behind the primary",
			Reasoning: []string{
				"The replica is applying changes slower than the primary generates them",
				"Common causes: heavy write load, slow replica disk, or single-threaded replication",
				"Reads from the replica return stale data proportional to the lag",
			},
			Impact:          "Stale data served from replica; failover would lose recent writes equal to the lag",
			ResolutionSteps: []string{"Check lag: SHOW SLAVE STATUS\\G (look at Seconds_Behind_Master)", "Enable parallel replication: SET GLOBAL slave_parallel_workers = 8", "Check replica disk I/O: iostat -x 1 5", "Optimize large transactions on the primary", "Upgrade replica disk to SSD/NVMe for faster relay log replay"},
			Prevention:      "Monitor Seconds_Behind_Master; use parallel replication; provision fast storage on replicas",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "mysql-buffer-pool-small", Category: "database", SubCategory: "mysql",
			Keywords: []string{"innodb buffer pool", "buffer pool too small", "buffer pool hit rate mysql"},
			Severity: "medium",
			RootCause: "InnoDB buffer pool is too small, causing excessive disk reads",
			Reasoning: []string{
				"A low buffer pool hit rate means most data reads go to disk instead of cache",
				"Recommended buffer pool size is 70-80% of available RAM on dedicated DB servers",
				"An undersized buffer pool causes high I/O load and slow queries",
			},
			Impact:          "Slow queries; high disk I/O; increased query latency; reduced throughput",
			ResolutionSteps: []string{"Check hit rate: SHOW STATUS LIKE 'Innodb_buffer_pool_read_requests'; SHOW STATUS LIKE 'Innodb_buffer_pool_reads'", "Current size: SHOW VARIABLES LIKE 'innodb_buffer_pool_size'", "Increase: SET GLOBAL innodb_buffer_pool_size = <70% of RAM>", "Set in my.cnf: innodb_buffer_pool_size = 12G", "After change: monitor hit rate improvement"},
			Prevention:      "Set buffer pool to 70-80% of RAM on dedicated DB servers; monitor buffer pool hit rate",
			BaseConfidence: 65, BaseRiskScore: 50,
		},
		{
			ID: "mysql-binlog-disk-full", Category: "database", SubCategory: "mysql",
			Keywords: []string{"binary log disk full", "binlog full mysql", "binlog disk space"},
			Severity: "critical",
			RootCause: "MySQL binary log directory disk is full — replication and PITR are at risk",
			Reasoning: []string{
				"Binary logs grow continuously with write activity",
				"Without expire_logs_days or binlog_expire_logs_seconds, old logs accumulate forever",
				"A full binlog disk prevents new transactions from being written",
			},
			Impact:          "Write operations fail; replication breaks; cannot create backups",
			ResolutionSteps: []string{"Free space: PURGE BINARY LOGS BEFORE DATE(NOW() - INTERVAL 3 DAY)", "Set automatic expiry: SET GLOBAL binlog_expire_logs_seconds = 604800 (7 days)", "Check disk: df -h $(SHOW VARIABLES LIKE 'log_bin_basename')", "Move binlog to larger volume: stop MySQL, move files, update my.cnf log_bin path", "If urgent: RESET MASTER (WARNING: breaks replication — only if no replicas)"},
			Prevention:      "Set binlog_expire_logs_seconds=604800; monitor binlog disk space; use a dedicated binlog volume",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "mysql-fk-constraint", Category: "database", SubCategory: "mysql",
			Keywords: []string{"foreign key constraint fails", "cannot add or update", "foreign key mysql"},
			Severity: "medium",
			RootCause: "MySQL foreign key constraint violation — referenced row does not exist or cannot be deleted",
			Reasoning: []string{
				"An INSERT/UPDATE references a parent row that does not exist",
				"Or a DELETE/UPDATE on a parent row would orphan child rows",
				"This is data integrity enforcement working correctly",
			},
			Impact:          "The specific write operation fails; application must handle the constraint error",
			ResolutionSteps: []string{"Check which constraint failed from the error message", "Verify the parent row exists before inserting child rows", "Use ON DELETE CASCADE or ON DELETE SET NULL if child rows should follow parent", "For bulk operations: SET FOREIGN_KEY_CHECKS = 0 (only temporarily and with caution)", "Fix application logic to handle the dependency correctly"},
			Prevention:      "Validate referential integrity in application code before writes; use proper CASCADE rules; test with realistic data",
			BaseConfidence: 65, BaseRiskScore: 35,
		},
	}
}

func buildRedisEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "redis-conn-refused", Category: "database", SubCategory: "redis",
			Keywords: []string{"connection refused 6379", "redis connection refused", "redis connect refused"},
			Severity: "critical",
			RootCause: "Redis is not accepting connections — the Redis process may be down",
			Reasoning: []string{
				"Nothing is listening on port 6379, meaning the Redis server process is not running",
				"Redis may have crashed due to memory limits, disk full, or a bug",
				"All caching and session data is lost if Redis was not configured for persistence",
			},
			Impact:          "All Redis-dependent operations fail; cache misses increase database load; sessions may be lost",
			ResolutionSteps: []string{"Check Redis status: systemctl status redis-server (or redis)", "Check for crash: tail -50 /var/log/redis/redis-server.log", "Restart Redis: systemctl restart redis-server", "Check memory: redis-cli INFO memory (after restart)", "If OOM killed: increase maxmemory and configure eviction policy"},
			Prevention:      "Monitor Redis process health; configure maxmemory with appropriate eviction policy; use Redis Sentinel for HA",
			BaseConfidence: 90, BaseRiskScore: 85,
		},
		{
			ID: "redis-maxmemory", Category: "database", SubCategory: "redis",
			Keywords: []string{"maxmemory", "redis out of memory", "redis oom", "oom command not allowed"},
			Severity: "critical",
			RootCause: "Redis has reached its maxmemory limit and cannot accept new write commands",
			Reasoning: []string{
				"When maxmemory is reached, Redis behavior depends on the eviction policy",
				"With noeviction policy, all write commands are rejected with OOM error",
				"With allkeys-lru, older keys are evicted to make room but writes still succeed",
			},
			Impact:          "Write operations rejected (noeviction) or data evicted (lru); cache data loss; application errors",
			ResolutionSteps: []string{"Check memory: redis-cli INFO memory", "Check eviction policy: redis-cli CONFIG GET maxmemory-policy", "Set eviction policy: redis-cli CONFIG SET maxmemory-policy allkeys-lru", "Increase maxmemory: redis-cli CONFIG SET maxmemory 2gb", "Find large keys: redis-cli --bigkeys", "Clean up: redis-cli FLUSHDB (only in non-production)"},
			Prevention:      "Set maxmemory with a buffer; use allkeys-lru for caches; monitor memory usage with alerts at 80%",
			BaseConfidence: 85, BaseRiskScore: 80,
		},
		{
			ID: "redis-loading", Category: "database", SubCategory: "redis",
			Keywords: []string{"redis is loading", "loading the dataset", "redis loading"},
			Severity: "high",
			RootCause: "Redis is loading its RDB/AOF dataset into memory — not yet ready to serve",
			Reasoning: []string{
				"Redis loads the entire dataset from disk at startup before accepting commands",
				"Large datasets (>10GB) can take minutes to load",
				"During loading, all commands except INFO and SUBSCRIBE are rejected",
			},
			Impact:          "Redis is temporarily unavailable; all dependent services get errors until loading completes",
			ResolutionSteps: []string{"Check loading progress: redis-cli INFO persistence (look at loading_eta_seconds)", "Wait for loading to complete — this is normal after a restart", "If too slow: check disk I/O speed: iostat -x 1 5", "Consider reducing dataset size if loading takes too long", "Use Redis replication: keep a replica ready so primary restarts are faster"},
			Prevention:      "Use Redis replication with automatic failover (Sentinel); keep dataset size manageable; use fast disks",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "redis-readonly-replica", Category: "database", SubCategory: "redis",
			Keywords: []string{"readonly", "read only replica", "can't write against", "redis readonly"},
			Severity: "high",
			RootCause: "Application is trying to write to a Redis replica, which is read-only by default",
			Reasoning: []string{
				"Redis replicas are read-only to prevent data conflicts with the primary",
				"The application may be connecting to a replica instead of the primary",
				"After a failover, the old primary may have become a replica",
			},
			Impact:          "All write operations fail; application cannot update cache or session data",
			ResolutionSteps: []string{"Check role: redis-cli INFO replication (look for role:master vs role:slave)", "Point application to the primary: update REDIS_URL in config", "If using Sentinel: ensure application uses Sentinel-aware client", "Check if a failover occurred: redis-cli SENTINEL get-master-addr-by-name <master-name>", "If intentional replica: enable writes: CONFIG SET slave-read-only no (not recommended)"},
			Prevention:      "Use Sentinel-aware Redis clients; verify connection targets in config; monitor Redis role changes",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "redis-cluster-down", Category: "database", SubCategory: "redis",
			Keywords: []string{"clusterdown", "cluster is down", "cluster_state:fail"},
			Severity: "critical",
			RootCause: "Redis cluster has entered a failed state — one or more hash slots are not covered",
			Reasoning: []string{
				"A cluster fails when a primary node and all its replicas are down",
				"The hash slots owned by that node are unassigned — keys in those slots are inaccessible",
				"With cluster-require-full-coverage=yes (default), the entire cluster refuses commands",
			},
			Impact:          "Entire Redis cluster is unavailable; all cache/session operations fail across all applications",
			ResolutionSteps: []string{"Check cluster state: redis-cli CLUSTER INFO", "Find failed nodes: redis-cli CLUSTER NODES | grep fail", "If node is recoverable: restart it and let it rejoin", "If node is lost: add a new node and reassign slots: redis-cli CLUSTER ADDSLOTS <slot>", "Temporary fix: redis-cli CONFIG SET cluster-require-full-coverage no"},
			Prevention:      "Run at least 1 replica per primary; use 3+ primary nodes; monitor cluster health; set up alerts on cluster_state",
			BaseConfidence: 90, BaseRiskScore: 90,
		},
		{
			ID: "redis-sentinel-failover", Category: "database", SubCategory: "redis",
			Keywords: []string{"sentinel failover", "sentinel promoted", "failover triggered redis"},
			Severity: "high",
			RootCause: "Redis Sentinel triggered a failover — the primary has changed",
			Reasoning: []string{
				"Sentinel promoted a replica to primary because the old primary was unreachable",
				"Applications using the old primary address will get connection errors",
				"Data written between the last replication sync and the failover may be lost",
			},
			Impact:          "Brief disruption during failover; applications not using Sentinel-aware clients lose connectivity",
			ResolutionSteps: []string{"Check new primary: redis-cli -p 26379 SENTINEL get-master-addr-by-name <master-name>", "Verify all replicas are syncing to new primary: redis-cli INFO replication on the new primary", "Update application config if not using Sentinel-aware client", "Investigate why the old primary failed: check its logs", "Verify data integrity: compare key counts between old primary (if recovered) and new"},
			Prevention:      "Use Sentinel-aware Redis clients (e.g., redis-py with Sentinel); run 3+ Sentinel instances; monitor failover events",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "redis-slow-query", Category: "database", SubCategory: "redis",
			Keywords: []string{"redis slow", "slowlog", "redis latency spike"},
			Severity: "medium",
			RootCause: "Redis slow queries detected — commands are taking longer than expected",
			Reasoning: []string{
				"Redis is single-threaded; one slow command blocks all other commands",
				"KEYS, SORT, and operations on large data structures are common offenders",
				"Background operations (RDB save, AOF rewrite) can also cause latency spikes",
			},
			Impact:          "All Redis operations are delayed while slow command runs; tail latency increases",
			ResolutionSteps: []string{"Check slow log: redis-cli SLOWLOG GET 25", "Find large keys: redis-cli --bigkeys", "Replace KEYS with SCAN: use SCAN cursor instead of KEYS pattern", "Break large operations into smaller batches: use pipelines", "Check for background save causing latency: redis-cli INFO persistence"},
			Prevention:      "Never use KEYS in production; use SCAN instead; monitor SLOWLOG; avoid large single-key operations",
			BaseConfidence: 65, BaseRiskScore: 50,
		},
		{
			ID: "redis-persistence-failure", Category: "database", SubCategory: "redis",
			Keywords: []string{"rdb save failed", "aof rewrite failed", "redis persistence error", "bgsave error"},
			Severity: "high",
			RootCause: "Redis persistence (RDB snapshot or AOF rewrite) failed — data durability at risk",
			Reasoning: []string{
				"If persistence fails, Redis data exists only in memory — a crash means total data loss",
				"Common causes: disk full, insufficient memory for fork(), or filesystem errors",
				"BGSAVE/BGREWRITEAOF fork the Redis process, requiring extra memory",
			},
			Impact:          "Data is not persisted to disk; crash would cause complete data loss",
			ResolutionSteps: []string{"Check last save status: redis-cli LASTSAVE && redis-cli INFO persistence", "Check disk space: df -h", "Check memory for fork: Redis needs ~2x memory for BGSAVE fork", "Set overcommit: sysctl -w vm.overcommit_memory=1", "Trigger manual save after fixing: redis-cli BGSAVE"},
			Prevention:      "Set vm.overcommit_memory=1; monitor persistence status; ensure adequate disk space and memory",
			BaseConfidence: 75, BaseRiskScore: 70,
		},
		{
			ID: "redis-client-limit", Category: "database", SubCategory: "redis",
			Keywords: []string{"max clients reached", "redis clients limit", "too many redis clients"},
			Severity: "high",
			RootCause: "Redis has reached its maxclients limit — no new connections can be established",
			Reasoning: []string{
				"Default maxclients is 10,000 but may be limited by system file descriptor limits",
				"Connection leaks in applications gradually consume client slots",
				"Each connected client uses memory even when idle",
			},
			Impact:          "New connections rejected; applications cannot connect to Redis; errors cascade",
			ResolutionSteps: []string{"Check connected clients: redis-cli INFO clients", "Check limit: redis-cli CONFIG GET maxclients", "Find clients consuming slots: redis-cli CLIENT LIST | wc -l", "Increase maxclients: redis-cli CONFIG SET maxclients 20000", "Kill idle clients: redis-cli CLIENT KILL ID <id> (for old idle connections)"},
			Prevention:      "Set maxclients appropriately; configure client timeout for idle connections; fix connection leaks; use connection pooling",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "redis-latency-spike", Category: "database", SubCategory: "redis",
			Keywords: []string{"redis latency", "redis response time", "intrinsic latency redis"},
			Severity: "high",
			RootCause: "Redis latency has spiked significantly above baseline",
			Reasoning: []string{
				"Redis should respond in < 1ms for most operations; spikes indicate a problem",
				"Causes: slow commands, background persistence, system-level issues (swap, CPU contention)",
				"Network latency between client and Redis can also manifest as Redis latency",
			},
			Impact:          "All Redis-dependent operations slow down; cache misses increase; application latency rises",
			ResolutionSteps: []string{"Check latency history: redis-cli --latency-history", "Check slow log: redis-cli SLOWLOG GET 25", "Check for background operations: redis-cli INFO persistence (rdb_last_bgsave_status)", "Check swap usage: redis-cli INFO memory (look for used_memory_rss vs used_memory)", "Check if Transparent Huge Pages is enabled: cat /sys/kernel/mm/transparent_hugepage/enabled"},
			Prevention:      "Disable THP: echo never > /sys/kernel/mm/transparent_hugepage/enabled; monitor latency; avoid slow commands",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "redis-fragmentation", Category: "database", SubCategory: "redis",
			Keywords: []string{"memory fragmentation", "fragmentation ratio", "redis fragmentation"},
			Severity: "medium",
			RootCause: "Redis memory fragmentation ratio is high (>1.5), wasting memory",
			Reasoning: []string{
				"High fragmentation means Redis allocated more memory from the OS than it actually uses",
				"Caused by frequent creation and deletion of variable-size keys",
				"The ratio used_memory_rss / used_memory should be close to 1.0",
			},
			Impact:          "Wasted memory; may hit maxmemory or OOM earlier than expected",
			ResolutionSteps: []string{"Check fragmentation: redis-cli INFO memory | grep fragmentation", "Enable active defrag: redis-cli CONFIG SET activedefrag yes", "Set defrag thresholds: CONFIG SET active-defrag-threshold-lower 10", "Restart Redis to reset fragmentation (if maintenance window available)", "Switch to jemalloc allocator if not already using it"},
			Prevention:      "Enable active-defrag; use jemalloc allocator; monitor fragmentation ratio",
			BaseConfidence: 60, BaseRiskScore: 40,
		},
		{
			ID: "redis-auth-failure", Category: "database", SubCategory: "redis",
			Keywords: []string{"redis auth failed", "noauth", "redis wrong password", "authentication required redis"},
			Severity: "high",
			RootCause: "Redis authentication failed — wrong password or authentication not provided",
			Reasoning: []string{
				"Redis requirepass is set but the client is using the wrong password or no password",
				"May occur after a password rotation that was not propagated to all clients",
				"Redis 6+ supports ACL with per-user authentication which adds complexity",
			},
			Impact:          "Application cannot connect to Redis; all cache/session operations fail",
			ResolutionSteps: []string{"Verify password: redis-cli AUTH <password>", "Check redis.conf for requirepass setting", "Update REDIS_PASSWORD in application environment variables", "For Redis 6+ ACL: redis-cli ACL LIST to check user configuration", "Test connection: redis-cli -a <password> PING"},
			Prevention:      "Use secrets manager for Redis passwords; synchronize rotation across all services; test auth before cutover",
			BaseConfidence: 80, BaseRiskScore: 60,
		},
		{
			ID: "redis-eviction-rate-high", Category: "database", SubCategory: "redis",
			Keywords: []string{"keys evicted", "evicted_keys", "redis eviction", "high eviction"},
			Severity: "medium",
			RootCause: "Redis is actively evicting keys at a high rate to stay under maxmemory",
			Reasoning: []string{
				"High eviction rate means the dataset is larger than the allocated memory",
				"Evicted keys cause cache misses, increasing load on the backend database",
				"If eviction outpaces ingestion, the cache becomes ineffective",
			},
			Impact:          "Increased cache miss rate; higher database load; degraded application performance",
			ResolutionSteps: []string{"Check eviction stats: redis-cli INFO stats | grep evicted_keys", "Check memory usage: redis-cli INFO memory", "Increase maxmemory: redis-cli CONFIG SET maxmemory 4gb", "Audit key TTLs: look for keys with no expiry that could be time-limited", "Find large keys to optimize: redis-cli --bigkeys"},
			Prevention:      "Size Redis memory for the working set; set TTLs on all cache keys; monitor eviction rate",
			BaseConfidence: 65, BaseRiskScore: 50,
		},
		{
			ID: "redis-keyspace-miss-rate", Category: "database", SubCategory: "redis",
			Keywords: []string{"keyspace miss", "cache miss rate", "miss rate high redis"},
			Severity: "medium",
			RootCause: "High keyspace miss rate in Redis — many lookups are finding no data",
			Reasoning: []string{
				"High miss rate means applications are looking for keys that do not exist in Redis",
				"Could indicate cache warming issues, wrong key names, or eviction happening too fast",
				"Each miss typically results in a backend database query, increasing database load",
			},
			Impact:          "Degraded cache effectiveness; increased database load; higher application latency",
			ResolutionSteps: []string{"Check hit/miss ratio: redis-cli INFO stats | grep keyspace", "Review cache key naming conventions in application code", "Implement cache warming on startup for frequently accessed data", "Check TTL settings: keys expiring too quickly cause misses", "Add negative caching: cache the absence of data to prevent repeated DB lookups"},
			Prevention:      "Monitor hit/miss ratio; implement cache warming; use appropriate TTLs; add negative caching",
			BaseConfidence: 60, BaseRiskScore: 40,
		},
	}
}

func buildMongoEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "mongo-pool-exhausted", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"connection pool exhausted mongodb", "mongo pool exhausted", "mongo connection pool"},
			Severity: "high",
			RootCause: "MongoDB connection pool is exhausted — all connections are in use",
			Reasoning: []string{
				"All connections in the MongoDB driver pool are occupied by active operations",
				"Slow queries or operations hold connections longer, reducing effective pool size",
				"The application cannot create new database operations until a connection is freed",
			},
			Impact:          "New database operations are queued or fail; application response times increase dramatically",
			ResolutionSteps: []string{"Check active connections: db.serverStatus().connections", "Increase pool size in connection string: ?maxPoolSize=100", "Kill long-running operations: db.currentOp({secs_running: {$gt: 10}})", "Optimize slow queries: check explain() output", "Add connection timeout: ?waitQueueTimeoutMS=5000"},
			Prevention:      "Size connection pool based on workload; optimize slow queries; monitor pool utilization",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "mongo-write-concern-timeout", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"write concern timeout", "writeconcernerror", "write concern mongodb"},
			Severity: "high",
			RootCause: "MongoDB write concern timeout — the write was not acknowledged by enough replicas",
			Reasoning: []string{
				"The write was committed to the primary but could not be replicated to enough nodes within the timeout",
				"If the primary fails before replication completes, the write may be lost (rollback)",
				"Common causes: replica lag, network issues between primary and replicas",
			},
			Impact:          "Writes may not be durable; data could be lost on primary failure; application sees timeout errors",
			ResolutionSteps: []string{"Check replica status: rs.status()", "Check replication lag: rs.printSecondaryReplicationInfo()", "Increase write concern timeout: {w: 'majority', wtimeout: 10000}", "Check network between primary and replicas: ping and bandwidth", "If chronic: investigate slow disk on replicas"},
			Prevention:      "Monitor replication lag; use w:'majority' with appropriate timeout; provision fast disks on all replicas",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "mongo-replication-lag", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"replication lag mongodb", "mongo replica lag", "oplog lag"},
			Severity: "high",
			RootCause: "MongoDB replica is lagging behind the primary — reads from secondaries return stale data",
			Reasoning: []string{
				"The oplog is being written faster than the secondary can apply operations",
				"Slow disk I/O on the secondary is the most common cause",
				"Large write volumes (bulk imports, migrations) cause temporary lag spikes",
			},
			Impact:          "Stale reads from secondaries; failover would lose recent writes; risk of oplog window closing",
			ResolutionSteps: []string{"Check lag: rs.printSecondaryReplicationInfo()", "Check replica status: rs.status()", "Check secondary disk I/O: iostat -x 1 5 on the secondary", "If oplog window is closing: increase oplog size", "Optimize large write operations on the primary"},
			Prevention:      "Monitor replication lag; provision SSDs for all replicas; size oplog for 24h+ of operations",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "mongo-wiredtiger-cache", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"wiredtiger cache", "cache pressure mongodb", "cache full mongodb"},
			Severity: "high",
			RootCause: "WiredTiger internal cache is under pressure — eviction rate is high",
			Reasoning: []string{
				"WiredTiger uses an internal cache (default: 50% of RAM - 1GB) for data and indexes",
				"High cache pressure means more data is being accessed than fits in cache",
				"Eviction threads spend too much CPU evicting pages, reducing query throughput",
			},
			Impact:          "Query latency increases; CPU usage rises from cache eviction; disk I/O increases",
			ResolutionSteps: []string{"Check cache stats: db.serverStatus().wiredTiger.cache", "Increase cache size: add --wiredTigerCacheSizeGB=4 to mongod", "Optimize queries to reduce working set: add indexes, limit result sets", "Check for table scans: db.currentOp() and check for COLLSCAN", "Add indexes for frequent queries: db.collection.createIndex({field: 1})"},
			Prevention:      "Size WiredTiger cache for your working set; add appropriate indexes; monitor cache hit rate",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "mongo-shard-migration", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"chunk migration", "moveChunk", "sharding migration", "balancer mongodb"},
			Severity: "medium",
			RootCause: "MongoDB chunk migration is in progress, causing increased I/O and latency",
			Reasoning: []string{
				"The balancer moves chunks between shards to equalize data distribution",
				"During migration, the affected range is temporarily served by both shards",
				"This increases network traffic, disk I/O, and CPU on both source and target shards",
			},
			Impact:          "Increased latency for queries hitting migrating chunks; higher I/O on affected shards",
			ResolutionSteps: []string{"Check balancer status: sh.getBalancerState()", "Check active migrations: db.adminCommand({currentOp: 1, $opsWaitingForLock: true})", "Stop the balancer during peak: sh.stopBalancer()", "Schedule balancer window: db.settings.update({_id: 'balancer'}, {$set: {activeWindow: {start: '02:00', stop: '06:00'}}})", "Check shard imbalance: sh.status()"},
			Prevention:      "Schedule balancer windows during off-peak; choose a good shard key to minimize migrations; monitor chunk distribution",
			BaseConfidence: 60, BaseRiskScore: 45,
		},
		{
			ID: "mongo-oplog-window", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"oplog window", "oplog shrinking", "oplog too small mongodb"},
			Severity: "high",
			RootCause: "MongoDB oplog window is shrinking — replicas may fall off the replication chain",
			Reasoning: []string{
				"The oplog is a capped collection; when it wraps, old entries are lost",
				"If a replica needs entries older than what the oplog holds, it must full resync",
				"Full resync of a large dataset can take hours and causes additional load",
			},
			Impact:          "Replica may need full resync (hours of downtime); reduced fault tolerance during resync",
			ResolutionSteps: []string{"Check oplog window: rs.printReplicationInfo()", "Increase oplog size (MongoDB 4.0+): db.adminCommand({replSetResizeOplog: 1, size: 51200})", "For older versions: stop secondary, drop local DB, restart to trigger initial sync with larger oplog", "Reduce write volume: defer bulk operations", "Fix any lagging replica before the oplog window closes"},
			Prevention:      "Size oplog for at least 24-72h of write operations; monitor oplog window size; alert at < 6h",
			BaseConfidence: 70, BaseRiskScore: 65,
		},
		{
			ID: "mongo-election", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"election in progress", "mongodb election", "stepping down", "primary election"},
			Severity: "high",
			RootCause: "MongoDB replica set election is in progress — temporary write unavailability",
			Reasoning: []string{
				"The primary has stepped down and an election is happening to choose a new primary",
				"During election (typically 10-30 seconds), no writes are possible",
				"Reads from secondaries continue to work during election",
			},
			Impact:          "Write operations fail for 10-30 seconds; applications without retry logic see errors",
			ResolutionSteps: []string{"Check election status: rs.status()", "Investigate why the primary stepped down: check mongod logs", "If deliberate: wait for election to complete", "If caused by network partition: check network between nodes", "Ensure application has retry logic for transient errors"},
			Prevention:      "Use retryWrites=true in connection string; monitor primary health; ensure stable network between nodes",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "mongo-cursor-timeout", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"cursor timeout", "cursor not found", "cursor expired mongodb"},
			Severity: "medium",
			RootCause: "MongoDB cursor timed out — client did not iterate results within the timeout period",
			Reasoning: []string{
				"Cursors expire after 10 minutes of inactivity by default",
				"If the application takes too long to process results between iterations, the cursor dies",
				"Large result sets with slow processing are common triggers",
			},
			Impact:          "Application loses its place in the result set; must restart the query from the beginning",
			ResolutionSteps: []string{"Use noCursorTimeout option: db.collection.find().noCursorTimeout()", "Process results faster in the application", "Use smaller batch sizes: db.collection.find().batchSize(100)", "Implement pagination instead of cursoring through large result sets", "Close cursors explicitly when done: cursor.close()"},
			Prevention:      "Use pagination for large result sets; set appropriate batch sizes; implement cursor retry logic",
			BaseConfidence: 60, BaseRiskScore: 35,
		},
		{
			ID: "mongo-index-build-failure", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"index build failed", "createIndex error", "index creation mongodb"},
			Severity: "high",
			RootCause: "MongoDB index build failed — commonly due to insufficient disk space or duplicate keys",
			Reasoning: []string{
				"Index builds require temporary disk space approximately equal to the index size",
				"Unique index builds fail if the collection contains duplicate values for the indexed field",
				"Background index builds can still impact read/write performance",
			},
			Impact:          "Index not created; queries remain slow; subsequent operations expecting the index may plan incorrectly",
			ResolutionSteps: []string{"Check disk space: df -h", "For unique index: find duplicates: db.collection.aggregate([{$group:{_id:'$field', count:{$sum:1}}},{$match:{count:{$gt:1}}}])", "Clean up duplicates before retrying unique index", "Retry index build: db.collection.createIndex({field: 1}, {background: true})", "For large collections: build index during maintenance window"},
			Prevention:      "Validate data uniqueness before creating unique indexes; ensure adequate disk space; build indexes during low-traffic periods",
			BaseConfidence: 65, BaseRiskScore: 50,
		},
		{
			ID: "mongo-storage-error", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"storage engine error", "wiredtiger error", "storage error mongodb"},
			Severity: "critical",
			RootCause: "MongoDB storage engine encountered an error — potential data corruption or disk failure",
			Reasoning: []string{
				"WiredTiger storage errors usually indicate disk-level problems",
				"The database may shut down to prevent further damage",
				"Data files on the affected volume may be corrupted",
			},
			Impact:          "Database may become unavailable; data integrity is at risk; potential data loss",
			ResolutionSteps: []string{"Check mongod logs for specific error details", "Check disk health: smartctl -a /dev/sda", "If disk is failing: do not restart on the same disk — restore from backup", "Run validate on affected collections: db.collection.validate()", "If data is corrupt: restore from backup and replay oplog"},
			Prevention:      "Monitor disk health; use ECC memory; maintain regular backups; test restore procedures",
			BaseConfidence: 85, BaseRiskScore: 90,
		},
	}
}
