package services

func buildExtraSystemEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "cpu-context-switch-high", Category: "system_metric", SubCategory: "cpu",
			Keywords:  []string{"context switch", "context switching", "cs high"},
			Severity:  "medium",
			RootCause: "Excessive context switching detected — the system is spending too much time switching between threads",
			Reasoning: []string{
				"High context switch rates (>100k/s) indicate too many threads competing for CPU",
				"Each context switch has overhead: saving/restoring registers, TLB flush",
				"Applications with thread-per-request architecture often suffer from this",
			},
			Impact:          "Reduced effective CPU throughput; increased system CPU time; higher latency",
			ResolutionSteps: []string{"Check context switches: vmstat 1 5 (cs column)", "Check per-process switches: pidstat -w 1 5", "Reduce thread count to match available cores", "Use async I/O or event-driven architecture instead of thread-per-request", "Check for excessive locking causing threads to yield frequently"},
			Prevention:      "Size thread pools to CPU core count; use non-blocking I/O; monitor context switch rates",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "cpu-interrupt-storm", Category: "system_metric", SubCategory: "cpu",
			Keywords:  []string{"interrupt storm", "high interrupts", "irq storm", "softirq"},
			Severity:  "high",
			RootCause: "Interrupt storm detected — excessive hardware or software interrupts consuming CPU",
			Reasoning: []string{
				"A malfunctioning network card, disk controller, or driver can generate excessive interrupts",
				"Each interrupt forces the CPU to stop current work and handle the interrupt",
				"Software interrupts (softirq) from high network traffic can also cause storms",
			},
			Impact:          "CPU consumed by interrupt handling instead of application work; high latency for all processes",
			ResolutionSteps: []string{"Check interrupt counts: cat /proc/interrupts", "Watch interrupt rate: watch -d cat /proc/interrupts", "Check softirq: cat /proc/softirqs", "If network-related: check NIC driver, enable interrupt coalescing: ethtool -C <iface> rx-usecs 100", "Identify the device generating excessive interrupts and check for hardware issues"},
			Prevention:      "Enable interrupt coalescing on NICs; use NAPI for network drivers; monitor interrupt rates",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "mem-numa-imbalance", Category: "system_metric", SubCategory: "memory",
			Keywords:  []string{"numa imbalance", "numa", "remote memory access", "numa node"},
			Severity:  "medium",
			RootCause: "NUMA memory imbalance — processes are accessing memory on remote NUMA nodes",
			Reasoning: []string{
				"Remote NUMA memory access is 40-100% slower than local access",
				"Processes migrating between NUMA nodes lose their local memory affinity",
				"This is common on multi-socket servers where memory is not evenly distributed",
			},
			Impact:          "Higher memory access latency; reduced throughput for memory-intensive workloads",
			ResolutionSteps: []string{"Check NUMA stats: numastat", "Check NUMA topology: numactl --hardware", "Pin process to a NUMA node: numactl --cpunodebind=0 --membind=0 <command>", "For databases: configure NUMA-aware memory allocation", "Set vm.zone_reclaim_mode=0 to allow cross-node allocation when needed"},
			Prevention:      "Use NUMA-aware scheduling; pin critical processes to NUMA nodes; monitor NUMA statistics",
			BaseConfidence: 60, BaseRiskScore: 40,
		},
		{
			ID: "network-half-open", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"half-open", "syn_sent", "syn_recv", "half open connections"},
			Severity:  "high",
			RootCause: "High number of half-open TCP connections detected — possible SYN flood or backend failure",
			Reasoning: []string{
				"Many connections in SYN_SENT state indicate the target is not responding to SYN",
				"Many connections in SYN_RECV state on the server indicate possible SYN flood attack",
				"Legitimate cause: backend service crashed and clients are retrying connections",
			},
			Impact:          "Connection resources consumed; new connections delayed; potential denial of service",
			ResolutionSteps: []string{"Check connection states: ss -s", "Check SYN queue: netstat -s | grep -i syn", "Enable SYN cookies: sysctl -w net.ipv4.tcp_syncookies=1", "Increase SYN backlog: sysctl -w net.ipv4.tcp_max_syn_backlog=65535", "If attack: configure firewall rate limiting for SYN packets"},
			Prevention:      "Enable SYN cookies; set appropriate SYN backlog; implement connection rate limiting; use DDoS protection",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "disk-io-throughput-limit", Category: "system_metric", SubCategory: "disk",
			Keywords:  []string{"disk throughput", "iops limit", "io throttled", "burst credits exhausted"},
			Severity:  "high",
			RootCause: "Disk I/O throughput or IOPS limit has been reached, throttling all disk operations",
			Reasoning: []string{
				"Cloud-provisioned disks have IOPS and throughput limits based on disk type and size",
				"Burst credits (AWS gp2/gp3) can be exhausted during sustained high I/O",
				"Once throttled, all disk operations experience dramatically increased latency",
			},
			Impact:          "All disk-dependent operations slow down; database queries take longer; writes queue up",
			ResolutionSteps: []string{"Check disk metrics: iostat -x 1 5 (look at %util near 100%)", "For AWS: check EBS burst balance in CloudWatch", "Upgrade disk type: gp2 -> gp3 or io1/io2 for guaranteed IOPS", "Reduce I/O: optimize queries, reduce logging, defer batch operations", "Split workload across multiple volumes"},
			Prevention:      "Use provisioned IOPS for I/O-intensive workloads; monitor burst balance; separate log and data volumes",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
	}
}

func buildExtraAppEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "java-thread-pool-exhausted", Category: "application", SubCategory: "java",
			Keywords: []string{"thread pool exhausted", "rejected execution", "threadpoolexecutor", "rejectedexecutionexception"},
			Severity: "critical",
			RootCause: "Java thread pool is exhausted — all threads are busy and the work queue is full",
			Reasoning: []string{
				"When all threads are occupied and the queue is full, new tasks are rejected",
				"Common in HTTP servers (Tomcat, Jetty) when too many slow requests are in-flight",
				"Thread pool exhaustion typically cascades: slow responses cause more waiting callers",
			},
			Impact:          "New requests are rejected with 503; service effectively offline for new requests",
			ResolutionSteps: []string{"Check thread pool status via JMX or actuator: /actuator/metrics/tomcat.threads.busy", "Increase max threads: server.tomcat.threads.max=400 (Spring Boot)", "Identify slow requests holding threads: take thread dump: jstack <PID>", "Fix slow downstream calls that are holding threads", "Implement async request processing for I/O-bound operations"},
			Prevention:      "Monitor thread pool utilization; implement circuit breakers for slow dependencies; use async/reactive for I/O",
			BaseConfidence: 85, BaseRiskScore: 80,
		},
		{
			ID: "py-asyncio-loop-closed", Category: "application", SubCategory: "python",
			Keywords: []string{"event loop is closed", "event loop closed python", "asyncio closed"},
			Severity: "high",
			RootCause: "Python asyncio event loop has been closed prematurely — async operations are failing",
			Reasoning: []string{
				"The event loop was closed while coroutines were still running",
				"Common when mixing sync and async code improperly",
				"Can happen during shutdown if cleanup coroutines are still pending",
			},
			Impact:          "All async operations fail; async framework (aiohttp, FastAPI) cannot handle requests",
			ResolutionSteps: []string{"Ensure the event loop is not closed prematurely: check asyncio.get_event_loop() usage", "Use asyncio.run() as the entry point instead of manual loop management", "For FastAPI/uvicorn: check lifespan event handlers for errors", "Handle shutdown signals properly: register signal handlers that await cleanup", "Upgrade to Python 3.10+ where event loop management is improved"},
			Prevention:      "Use asyncio.run() instead of manual loop management; implement proper shutdown handlers; test cleanup paths",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "node-worker-thread-crash", Category: "application", SubCategory: "nodejs",
			Keywords: []string{"worker thread crash", "worker_threads error", "worker terminated"},
			Severity: "high",
			RootCause: "Node.js worker thread crashed — background processing is interrupted",
			Reasoning: []string{
				"Worker threads handle CPU-intensive or isolated operations in Node.js",
				"A crash in a worker thread does not crash the main process but loses the work in progress",
				"Common causes: unhandled exceptions, OOM in the worker, or native code crashes",
			},
			Impact:          "Background processing tasks fail; work in progress is lost; may need retry",
			ResolutionSteps: []string{"Check worker thread error event: worker.on('error', (err) => ...)", "Check if the worker ran out of memory: add --max-old-space-size to worker options", "Add error handling in the worker: wrap code in try/catch", "Implement task retry logic in the main thread", "Monitor worker thread health with heartbeats"},
			Prevention:      "Add error handlers to all workers; implement task retry; monitor worker health; set memory limits",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "go-race-condition", Category: "application", SubCategory: "go",
			Keywords: []string{"data race", "race condition", "concurrent map writes", "concurrent map read and map write"},
			Severity: "high",
			RootCause: "Go race condition detected — concurrent access to shared data without synchronization",
			Reasoning: []string{
				"Multiple goroutines are reading and writing the same data without locks or channels",
				"Race conditions cause unpredictable behavior: wrong values, panics, or data corruption",
				"Go maps are not safe for concurrent read/write and will panic",
			},
			Impact:          "Unpredictable behavior; potential panics; data corruption; intermittent failures",
			ResolutionSteps: []string{"If 'concurrent map writes' panic: use sync.Map or protect map access with sync.RWMutex", "Run with race detector to find the race: go run -race ./...", "Add sync.Mutex or sync.RWMutex around shared state", "Use channels for goroutine communication instead of shared memory", "Review all goroutine access to shared variables"},
			Prevention:      "Run tests with -race flag in CI; use sync.RWMutex for shared state; prefer channels over shared memory",
			BaseConfidence: 80, BaseRiskScore: 65,
		},
		{
			ID: "app-circuit-breaker-open", Category: "application", SubCategory: "generic",
			Keywords: []string{"circuit breaker open", "circuit breaker tripped", "circuit open", "fallback"},
			Severity: "high",
			RootCause: "Circuit breaker has opened due to high failure rate to a downstream service",
			Reasoning: []string{
				"The circuit breaker detected too many failures to the downstream and is now blocking requests",
				"This is a protective mechanism — it prevents cascading failures by failing fast",
				"The circuit will attempt to close after a timeout period (half-open state)",
			},
			Impact:          "Requests to the downstream fail immediately (fast fail); affected functionality unavailable",
			ResolutionSteps: []string{"Check the downstream service health — the circuit opened for a reason", "Review circuit breaker metrics: failure count, timeout, current state", "Fix the downstream service issue first", "The circuit will auto-close after the reset timeout", "If urgent: manually close the circuit (implementation-specific)"},
			Prevention:      "Monitor circuit breaker state; set appropriate thresholds; implement fallback responses; alert on circuit open events",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "app-cors-error", Category: "application", SubCategory: "generic",
			Keywords: []string{"cors error", "cross-origin", "access-control-allow-origin", "cors policy"},
			Severity: "medium",
			RootCause: "CORS (Cross-Origin Resource Sharing) policy is blocking browser requests to the API",
			Reasoning: []string{
				"The browser blocks requests to a different origin unless the server sends proper CORS headers",
				"This only affects browser clients, not server-to-server calls",
				"Common after changing API domains, adding new frontend origins, or deploying to new environments",
			},
			Impact:          "Frontend application cannot call the API; users see errors in the browser",
			ResolutionSteps: []string{"Add the frontend origin to the allowed origins in the API CORS configuration", "Set Access-Control-Allow-Origin header: match the requesting origin", "For development: allow all origins temporarily (NOT for production)", "Check if preflight OPTIONS request is being handled", "Verify credentials mode matches: Access-Control-Allow-Credentials if using cookies"},
			Prevention:      "Configure allowed origins per environment; test CORS in CI; document required origins",
			BaseConfidence: 70, BaseRiskScore: 30,
		},
		{
			ID: "app-websocket-disconnect", Category: "application", SubCategory: "generic",
			Keywords: []string{"websocket disconnect", "websocket closed", "ws connection lost", "websocket error"},
			Severity: "medium",
			RootCause: "WebSocket connections are disconnecting unexpectedly",
			Reasoning: []string{
				"WebSocket connections can be dropped by load balancers with idle timeouts",
				"Network interruptions cause WebSocket connections to drop silently",
				"Server-side errors or memory pressure can cause the server to close connections",
			},
			Impact:          "Real-time features stop working; users lose live updates; reconnection required",
			ResolutionSteps: []string{"Check server-side WebSocket logs for close reason/code", "Implement client-side reconnection with exponential backoff", "Configure load balancer WebSocket timeout: increase idle timeout for WebSocket connections", "Add ping/pong heartbeat to keep connections alive", "Check server memory: WebSocket connections consume memory per connection"},
			Prevention:      "Implement automatic reconnection; use ping/pong heartbeats; configure LB for WebSocket; monitor connection counts",
			BaseConfidence: 65, BaseRiskScore: 40,
		},
		{
			ID: "app-memory-leak-container", Category: "application", SubCategory: "generic",
			Keywords: []string{"container memory leak", "memory growing container", "rss growing container"},
			Severity: "high",
			RootCause: "Container memory usage is steadily growing, indicating a memory leak",
			Reasoning: []string{
				"Container RSS keeps increasing over time without returning to a baseline",
				"The container will eventually hit its memory limit and be OOM-killed",
				"Time to OOM depends on the leak rate and the memory limit",
			},
			Impact:          "Periodic OOM kills and service restarts; growing instability; data loss during kills",
			ResolutionSteps: []string{"Monitor container memory: kubectl top pod <pod> (repeated over time)", "Check for the language-specific leak using appropriate profiler", "Take memory snapshots at two time points and compare", "Restart the container as temporary mitigation", "Reduce the restart interval to minimize impact while investigating"},
			Prevention:      "Profile memory in staging; set container memory limits; implement health checks that track memory trends",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "redis-pub-sub-overflow", Category: "database", SubCategory: "redis",
			Keywords: []string{"pubsub overflow", "output buffer limit", "subscriber disconnected redis"},
			Severity: "medium",
			RootCause: "Redis pub/sub subscriber was disconnected because its output buffer overflowed",
			Reasoning: []string{
				"Subscribers that cannot read messages fast enough have their output buffer fill up",
				"When the buffer exceeds the limit, Redis disconnects the slow subscriber",
				"The subscriber misses messages while disconnected",
			},
			Impact:          "Messages are lost for slow subscribers; real-time features may miss updates",
			ResolutionSteps: []string{"Check client output buffer limits: redis-cli CONFIG GET client-output-buffer-limit", "Increase buffer for pub/sub: CONFIG SET client-output-buffer-limit 'pubsub 256mb 128mb 60'", "Make subscribers process messages faster", "Reduce message rate from publishers", "Consider using Redis Streams instead of pub/sub for durable messaging"},
			Prevention:      "Set appropriate buffer limits; use Redis Streams for durability; monitor subscriber lag",
			BaseConfidence: 60, BaseRiskScore: 45,
		},
		{
			ID: "mongo-connection-string-error", Category: "database", SubCategory: "mongodb",
			Keywords: []string{"invalid connection string", "mongo uri error", "mongodb parse error", "invalid mongo uri"},
			Severity: "high",
			RootCause: "MongoDB connection string is malformed or contains incorrect parameters",
			Reasoning: []string{
				"The MongoDB driver cannot parse the connection string URI",
				"Common issues: missing protocol (mongodb://), wrong port, special characters not URL-encoded",
				"Password containing special characters (@, :, /) must be URL-encoded",
			},
			Impact:          "Application cannot connect to MongoDB; all database operations fail at startup",
			ResolutionSteps: []string{"Verify connection string format: mongodb://user:password@host:port/database", "URL-encode special characters in password: e.g., @ becomes %40", "Check that the host and port are correct", "Verify the database name exists", "Test connection with mongosh: mongosh '<connection-string>'"},
			Prevention:      "Store connection strings in secrets manager; validate format at startup; URL-encode all passwords",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "pg-vacuum-needed", Category: "database", SubCategory: "postgres",
			Keywords: []string{"autovacuum", "table bloat", "dead tuples", "vacuum needed"},
			Severity: "medium",
			RootCause: "PostgreSQL table has significant bloat from dead tuples that need to be vacuumed",
			Reasoning: []string{
				"PostgreSQL MVCC leaves dead tuples after UPDATE and DELETE operations",
				"Autovacuum may be unable to keep up with the rate of dead tuple creation",
				"Bloated tables use more disk space and cause slower sequential scans",
			},
			Impact:          "Table scans slower; disk space wasted; index efficiency reduced",
			ResolutionSteps: []string{"Check dead tuples: SELECT relname, n_dead_tup, last_autovacuum FROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 10", "Run manual vacuum: VACUUM ANALYZE <table>", "For severe bloat: VACUUM FULL <table> (requires exclusive lock)", "Tune autovacuum: ALTER TABLE <table> SET (autovacuum_vacuum_scale_factor = 0.01)", "Use pg_repack for online table rewriting without lock"},
			Prevention:      "Tune autovacuum per table; monitor dead tuple counts; schedule manual vacuums for high-churn tables",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "mysql-foreign-key-lock", Category: "database", SubCategory: "mysql",
			Keywords: []string{"foreign key lock mysql", "parent table lock", "fk deadlock mysql"},
			Severity: "medium",
			RootCause: "Foreign key constraint checking is causing lock contention in MySQL",
			Reasoning: []string{
				"InnoDB places shared locks on parent rows when inserting child rows",
				"High-concurrency inserts into child tables can cause lock waits on the parent",
				"This is especially problematic with hot parent rows referenced by many children",
			},
			Impact:          "Insert operations slow down; lock wait timeouts on high-concurrency workloads",
			ResolutionSteps: []string{"Identify the lock: SHOW ENGINE INNODB STATUS (look for FK LOCK)", "Reduce concurrent inserts to child tables: batch or queue them", "Consider removing the foreign key if application enforces integrity", "Use READ COMMITTED isolation: reduces lock scope", "Ensure parent rows are spread across many values to reduce hot spots"},
			Prevention:      "Minimize foreign keys in high-throughput tables; use application-level referential integrity; monitor lock waits",
			BaseConfidence: 60, BaseRiskScore: 45,
		},
		{
			ID: "app-graceful-shutdown-fail", Category: "application", SubCategory: "generic",
			Keywords: []string{"graceful shutdown", "sigterm", "sigkill", "shutdown timeout"},
			Severity: "medium",
			RootCause: "Application is not shutting down gracefully — in-flight requests are being dropped",
			Reasoning: []string{
				"The process receives SIGTERM but does not finish active requests before exiting",
				"Kubernetes sends SIGKILL after terminationGracePeriodSeconds (30s default)",
				"In-flight requests and database transactions are lost on ungraceful shutdown",
			},
			Impact:          "Dropped requests during deployments; potential data loss from incomplete transactions",
			ResolutionSteps: []string{"Add SIGTERM handler that stops accepting new requests but finishes existing ones", "Increase terminationGracePeriodSeconds if the app needs more time", "Add preStop hook with sleep to allow LB to drain: preStop: exec: command: ['sleep', '10']", "Check that the process PID 1 receives signals (use exec form in Dockerfile CMD)", "Implement connection draining in the application"},
			Prevention:      "Implement graceful shutdown handlers; use preStop hooks; test shutdown behavior; set appropriate grace periods",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "app-deadletter-queue-growing", Category: "application", SubCategory: "generic",
			Keywords: []string{"dead letter", "dead-letter", "dlq growing", "failed messages"},
			Severity: "high",
			RootCause: "Dead letter queue is growing — messages are permanently failing to be processed",
			Reasoning: []string{
				"Messages land in the DLQ after exhausting all retry attempts",
				"The consumer has a persistent bug or the message format has changed",
				"DLQ growth indicates a systematic issue, not just transient failures",
			},
			Impact:          "Business operations are not being processed; data loss if DLQ messages are not remediated",
			ResolutionSteps: []string{"Inspect DLQ messages to understand the failure pattern", "Fix the consumer bug that is causing processing failures", "Reprocess salvageable messages from the DLQ", "Increase retry count if failures are transient", "Add message validation to reject malformed messages before processing"},
			Prevention:      "Monitor DLQ depth; alert on DLQ growth; make consumers idempotent; validate message schemas",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "app-hot-restart-loop", Category: "application", SubCategory: "generic",
			Keywords: []string{"restart loop", "repeatedly restarting", "restart count high", "exit code 1"},
			Severity: "critical",
			RootCause: "Application is in a restart loop — it starts, fails quickly, and restarts repeatedly",
			Reasoning: []string{
				"The application encounters a fatal error during startup and exits",
				"The process manager restarts it, but the same error occurs again",
				"Common causes: missing config, database unreachable, or port conflict",
			},
			Impact:          "Service is effectively down; restart overhead consumes resources; no traffic served",
			ResolutionSteps: []string{"Check application exit logs: the last few lines before exit reveal the cause", "Check if dependencies (DB, Redis, config) are available", "Verify configuration files and environment variables are present and valid", "Check if the port is already in use by another process", "Roll back to the last working version"},
			Prevention:      "Validate dependencies at startup with clear error messages; use healthcheck-based deploy gates; keep rollback ready",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "app-slow-startup", Category: "application", SubCategory: "generic",
			Keywords: []string{"slow startup", "startup timeout", "initialization slow", "boot time"},
			Severity: "medium",
			RootCause: "Application is taking too long to start, failing liveness probes or deployment health checks",
			Reasoning: []string{
				"Slow startup can be caused by: database migrations, cache warming, or class loading",
				"Liveness probes configured with short initialDelaySeconds kill pods that are still starting",
				"Cold start in serverless or JVM-based apps can be significant",
			},
			Impact:          "Pods killed before ready; deployments fail; scaling operations take too long",
			ResolutionSteps: []string{"Increase initialDelaySeconds for liveness probe", "Profile startup: log timestamps at each initialization phase", "Defer non-critical initialization to after the service is listening", "Use startup probes (Kubernetes 1.16+) instead of liveness for slow starts", "Pre-warm caches asynchronously after the server starts"},
			Prevention:      "Use startup probes; lazy-initialize non-critical components; profile and optimize startup time",
			BaseConfidence: 65, BaseRiskScore: 40,
		},
		{
			ID: "app-dependency-version-conflict", Category: "application", SubCategory: "generic",
			Keywords: []string{"version conflict", "dependency conflict", "incompatible version", "version mismatch"},
			Severity: "high",
			RootCause: "Dependency version conflict — incompatible library versions are causing runtime errors",
			Reasoning: []string{
				"Two libraries require different versions of the same transitive dependency",
				"At runtime, only one version is loaded, causing method/class not found errors",
				"This is common in Java (classpath hell) and Node.js (nested node_modules)",
			},
			Impact:          "Runtime errors; specific functionality breaks; application may fail to start",
			ResolutionSteps: []string{"Check dependency tree: mvn dependency:tree (Java) or npm ls (Node.js) or pip show -f (Python)", "Resolve conflicts by aligning versions in the dependency management section", "Use dependency exclusions to remove the conflicting transitive dependency", "Upgrade the libraries to versions that share compatible dependencies", "For Node.js: npm dedupe to flatten the dependency tree"},
			Prevention:      "Pin dependency versions; use BOM/platform dependencies; run dependency checks in CI; keep dependencies updated",
			BaseConfidence: 70, BaseRiskScore: 50,
		},
		{
			ID: "app-env-var-missing", Category: "application", SubCategory: "generic",
			Keywords: []string{"environment variable missing", "env var not set", "undefined environment", "missing env var"},
			Severity: "high",
			RootCause: "Required environment variable is not set — application cannot read its configuration",
			Reasoning: []string{
				"The application expects an environment variable that is not present in the runtime",
				"Common after deploying to a new environment or changing secrets management",
				"The application may fail to start or behave incorrectly without the variable",
			},
			Impact:          "Application fails to start or operates with incorrect/default configuration",
			ResolutionSteps: []string{"Identify the missing variable from the error message or logs", "Set the variable in the deployment configuration (Kubernetes ConfigMap/Secret, .env, systemd)", "For Kubernetes: create the ConfigMap or Secret and reference it in the pod spec", "Verify the variable is available: kubectl exec <pod> -- env | grep <VAR>", "Check if the variable was renamed in a recent code change"},
			Prevention:      "Document all required environment variables; validate at startup; use .env.example files; test in staging",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "k8s-create-container-config-error", Category: "kubernetes", SubCategory: "pod",
			Keywords: []string{"createcontainerconfigerror", "container config error", "create container config"},
			Severity: "high",
			RootCause: "Kubernetes cannot create container due to missing ConfigMap, Secret, or invalid configuration",
			Reasoning: []string{
				"The pod spec references a ConfigMap, Secret, or ServiceAccount that does not exist",
				"The container cannot be created until all references are resolved",
				"This is different from CrashLoopBackOff — the container never starts at all",
			},
			Impact:          "Pod stays in Pending/CreateContainerConfigError state; service is unavailable",
			ResolutionSteps: []string{"Check events: kubectl describe pod <pod> | grep -A5 Events", "Look for missing Secret/ConfigMap references in the error", "Create missing resources: kubectl create secret/configmap as needed", "Check that the ServiceAccount exists: kubectl get sa -n <namespace>", "Verify volume mount references are correct"},
			Prevention:      "Validate all resource references before deploying; use admission controllers to check prerequisites",
			BaseConfidence: 80, BaseRiskScore: 65,
		},
		{
			ID: "k8s-limit-range-exceeded", Category: "kubernetes", SubCategory: "namespace",
			Keywords: []string{"limitrange exceeded", "limit range", "exceed container limits"},
			Severity: "medium",
			RootCause: "Pod resource requests or limits exceed the namespace LimitRange constraints",
			Reasoning: []string{
				"A LimitRange object defines min/max resource boundaries per container in the namespace",
				"Pods requesting resources outside these bounds are rejected at admission",
				"This is a governance mechanism to prevent resource hogging",
			},
			Impact:          "Pod creation is rejected; deployment cannot proceed",
			ResolutionSteps: []string{"Check LimitRange: kubectl describe limitrange -n <namespace>", "Adjust pod resource requests/limits to fit within the LimitRange", "Request LimitRange adjustment from the cluster admin", "Check both requests and limits — both must be within range", "For init containers: they have the same LimitRange constraints"},
			Prevention:      "Document namespace LimitRange constraints; validate resource specs in CI; align resource specs with limits",
			BaseConfidence: 70, BaseRiskScore: 45,
		},
		{
			ID: "infra-temperature-high", Category: "infrastructure", SubCategory: "hardware",
			Keywords: []string{"temperature high", "thermal throttle", "cpu temperature", "overheating"},
			Severity: "critical",
			RootCause: "Server hardware is overheating — CPU thermal throttling or shutdown risk",
			Reasoning: []string{
				"CPU temperature exceeding thresholds triggers thermal throttling to prevent damage",
				"Throttling reduces CPU frequency, degrading performance significantly",
				"If cooling fails completely, the server may shut down to prevent hardware damage",
			},
			Impact:          "Severe performance degradation from throttling; risk of emergency shutdown; potential hardware damage",
			ResolutionSteps: []string{"Check CPU temperature: sensors (requires lm-sensors package)", "Check IPMI sensors: ipmitool sdr type Temperature", "Verify fans are running: ipmitool sdr type Fan", "Check for blocked airflow in the server room", "For cloud: stop and start the instance to move to different hardware"},
			Prevention:      "Monitor temperatures; maintain HVAC in server rooms; clean dust from servers; monitor fan speeds",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "infra-power-supply-failure", Category: "infrastructure", SubCategory: "hardware",
			Keywords: []string{"power supply failure", "psu failure", "power redundancy lost"},
			Severity: "high",
			RootCause: "Server power supply has failed — running on redundant PSU only",
			Reasoning: []string{
				"One PSU has failed but the server continues on the redundant unit",
				"If the second PSU fails, the server will lose power immediately",
				"Power events may cause transient issues even with redundancy",
			},
			Impact:          "No power redundancy; server at risk of complete failure on second PSU loss",
			ResolutionSteps: []string{"Check PSU status: ipmitool sdr type 'Power Supply'", "Schedule immediate PSU replacement", "Prepare to migrate workloads if replacement will take time", "Check UPS status to ensure battery backup is available", "Monitor the remaining PSU for any degradation"},
			Prevention:      "Monitor PSU health via IPMI; maintain spare PSUs; use dual-corded power; implement UPS",
			BaseConfidence: 75, BaseRiskScore: 70,
		},
		{
			ID: "infra-certificate-chain-incomplete", Category: "infrastructure", SubCategory: "tls",
			Keywords: []string{"incomplete certificate chain", "missing intermediate", "chain incomplete", "unable to get local issuer"},
			Severity: "high",
			RootCause: "TLS certificate chain is incomplete — missing intermediate certificate(s)",
			Reasoning: []string{
				"The server is not sending the full certificate chain, only the leaf certificate",
				"Some clients can resolve the intermediate from their cache, others cannot",
				"This causes intermittent TLS failures depending on the client",
			},
			Impact:          "Some clients fail TLS handshake; mobile apps and curl may fail while browsers work; intermittent errors",
			ResolutionSteps: []string{"Check the certificate chain: openssl s_client -connect <host>:443 -showcerts", "Download the intermediate certificate from the CA's website", "Concatenate certificates: cat leaf.crt intermediate.crt > fullchain.crt", "Reconfigure the server to use the full chain file", "Verify: openssl verify -untrusted intermediate.crt leaf.crt"},
			Prevention:      "Always configure full certificate chains; test with openssl s_client; use Let's Encrypt fullchain.pem",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "infra-log-volume-full", Category: "infrastructure", SubCategory: "logging",
			Keywords: []string{"log volume full", "log disk full", "var log full", "logging full"},
			Severity: "high",
			RootCause: "Log volume or /var/log is full, preventing new log writes and potentially crashing services",
			Reasoning: []string{
				"Log files have grown to fill the volume, often from verbose logging or error storms",
				"When logs cannot be written, some services crash; others lose observability",
				"If /var/log is on the root filesystem, the entire system is affected",
			},
			Impact:          "Services may crash; cannot write new logs for debugging; system may become read-only",
			ResolutionSteps: []string{"Find large log files: du -sh /var/log/* | sort -hr | head -10", "Truncate large logs: truncate -s 0 /var/log/<large-file>", "Compress old logs: gzip /var/log/*.log.1", "Clean journal: journalctl --vacuum-size=500M", "Configure logrotate: verify /etc/logrotate.conf has proper rotation rules"},
			Prevention:      "Configure logrotate with size limits; use a separate /var/log volume; set max log retention; monitor log volume usage",
			BaseConfidence: 80, BaseRiskScore: 70,
		},
		{
			ID: "app-request-timeout-cascade", Category: "application", SubCategory: "generic",
			Keywords: []string{"cascading timeout", "timeout cascade", "chain timeout", "upstream timeout"},
			Severity: "critical",
			RootCause: "Cascading timeout failure — a slow downstream is causing timeouts to propagate upstream",
			Reasoning: []string{
				"One slow service causes callers to time out, which causes their callers to time out",
				"Each tier holds resources (threads, connections) while waiting, amplifying the problem",
				"The original slow service may have already recovered while the cascade continues",
			},
			Impact:          "Multiple services experience timeouts simultaneously; widespread user-facing errors",
			ResolutionSteps: []string{"Identify the original slow service at the bottom of the call chain", "Fix the root cause on the original slow service", "Implement circuit breakers to stop the cascade: fail fast instead of waiting", "Reduce timeout values to limit resource holding time", "Restart affected services if circuit breakers are not in place"},
			Prevention:      "Implement circuit breakers at every service boundary; set aggressive timeouts; use async communication where possible",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "app-database-migration-failed", Category: "application", SubCategory: "generic",
			Keywords: []string{"migration failed", "migrate error", "schema migration", "flyway error", "alembic error"},
			Severity: "high",
			RootCause: "Database migration failed during deployment — schema is in an inconsistent state",
			Reasoning: []string{
				"The migration SQL failed partway through, leaving the schema partially updated",
				"Some migration tools (Flyway, Alembic) mark the migration as failed and block future runs",
				"The new application code expects the new schema, but the migration did not complete",
			},
			Impact:          "Application cannot run with mismatched schema; deployment blocked; potential data issues",
			ResolutionSteps: []string{"Check migration status: flyway info / alembic current / rails db:migrate:status", "Check the specific migration that failed and its error", "Fix the migration SQL and retry: handle the partial state", "For Flyway: flyway repair to clean failed migration record", "Roll back the deployment to the version matching the current schema"},
			Prevention:      "Test migrations against production-like data; make migrations idempotent; use transactional DDL; back up before migrating",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "app-cache-stampede", Category: "application", SubCategory: "generic",
			Keywords: []string{"cache stampede", "thundering herd", "cache miss storm", "cache cold start"},
			Severity: "high",
			RootCause: "Cache stampede — many requests simultaneously hit the database when cached data expires",
			Reasoning: []string{
				"When a popular cached item expires, all concurrent requests miss cache and hit the database",
				"The database gets flooded with identical queries, potentially causing overload",
				"This is especially severe after a cache restart or deployment",
			},
			Impact:          "Database overloaded by simultaneous queries; response latency spikes; potential database failure",
			ResolutionSteps: []string{"Implement cache lock (singleflight pattern): only one request fetches from DB, others wait", "Add jitter to cache TTLs: randomize expiry to prevent simultaneous invalidation", "Use stale-while-revalidate: serve stale data while refreshing in the background", "Warm the cache before it expires: refresh at 80% of TTL", "Rate-limit database requests during cache miss storms"},
			Prevention:      "Implement singleflight/cache locks; add TTL jitter; use cache warming; implement stale-while-revalidate pattern",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "app-api-breaking-change", Category: "application", SubCategory: "generic",
			Keywords: []string{"breaking change", "api change", "contract broken", "backward incompatible"},
			Severity: "high",
			RootCause: "An API breaking change was deployed, causing consumers to fail",
			Reasoning: []string{
				"The API response format, required fields, or endpoints changed without consumer updates",
				"Consumers using the old format receive parsing errors or unexpected behavior",
				"This indicates insufficient API versioning or communication about changes",
			},
			Impact:          "All consumers using the old API format fail; integration errors across services",
			ResolutionSteps: []string{"Roll back the API change if consumers are not yet updated", "Communicate the breaking change to all consumers", "Implement API versioning: /v1/ and /v2/ endpoints", "Deploy backward-compatible changes: add new fields without removing old ones", "Update consumer applications to use the new API format"},
			Prevention:      "Use API versioning; deploy backward-compatible changes; communicate changes in advance; run contract tests",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "app-thread-starvation", Category: "application", SubCategory: "generic",
			Keywords: []string{"thread starvation", "no threads available", "all threads busy", "worker starvation"},
			Severity: "critical",
			RootCause: "All worker threads are occupied — no threads available to process new requests",
			Reasoning: []string{
				"All threads in the worker pool are blocked on slow I/O, locks, or computation",
				"New requests cannot be processed and queue up or are rejected",
				"This is functionally equivalent to an outage even though the process is running",
			},
			Impact:          "All new requests are rejected or queue indefinitely; service appears hung",
			ResolutionSteps: []string{"Take a thread dump to see what all threads are doing: jstack <PID> (Java) or kill -3 <PID>", "Identify the common blocking operation (slow DB query, external API call, lock)", "Fix the blocking operation or add a timeout to it", "Increase thread pool size as temporary mitigation", "Restart the service to clear the blocked threads immediately"},
			Prevention:      "Set timeouts on all I/O operations; use async processing for slow operations; monitor thread pool utilization; implement circuit breakers",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "app-connection-leak", Category: "application", SubCategory: "generic",
			Keywords: []string{"connection leak", "leaked connection", "connection not returned", "pool leak"},
			Severity: "high",
			RootCause: "Database or HTTP connections are being leaked — not returned to the pool after use",
			Reasoning: []string{
				"Code paths that open connections but do not close them in error/exception scenarios",
				"Each leaked connection permanently reduces the available pool size",
				"The pool gradually shrinks until no connections are available",
			},
			Impact:          "Gradual pool exhaustion; eventually all connections are leaked and the service fails",
			ResolutionSteps: []string{"Check connection pool metrics: active, idle, and total connections", "Enable leak detection: HikariCP leakDetectionThreshold, Django CONN_MAX_AGE", "Review code for missing connection.close() or try-with-resources blocks", "Restart the service to reset all connections as temporary fix", "Add connection idle timeout to automatically reclaim leaked connections"},
			Prevention:      "Use try-with-resources or defer for connection closing; enable pool leak detection; run connection audits in CI",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
	}
}
