package services

func buildInfraEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "infra-firewall-block", Category: "infrastructure", SubCategory: "firewall",
			Keywords: []string{"firewall block", "connection blocked", "iptables drop", "security group block"},
			Severity: "high",
			RootCause: "Firewall rule is blocking expected network traffic",
			Reasoning: []string{
				"A firewall rule (iptables, security group, or network ACL) is silently dropping packets",
				"Symptoms: connection timeouts (not connection refused) to specific ports",
				"May be caused by a security policy change or incorrect rule deployment",
			},
			Impact:          "Traffic to/from the affected service is blocked; connection timeouts from clients",
			ResolutionSteps: []string{"Check iptables rules: iptables -L -n -v | grep <port>", "For AWS: check security group rules in the EC2 console", "For GCP: check VPC firewall rules: gcloud compute firewall-rules list", "Test connectivity: nc -zv <host> <port>", "Add the required firewall rule to allow traffic"},
			Prevention:      "Manage firewall rules as code (Terraform/Pulumi); test connectivity after changes; document required ports",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "infra-lb-502-503", Category: "infrastructure", SubCategory: "load_balancer",
			Keywords: []string{"load balancer error", "backend unhealthy", "502 load balancer", "503 load balancer"},
			Severity: "critical",
			RootCause: "Load balancer is returning 502/503 errors — backends are unhealthy or not responding",
			Reasoning: []string{
				"The load balancer cannot forward requests to healthy backend instances",
				"502 means backend sent an invalid response; 503 means no healthy backends available",
				"All backend instances may have failed health checks simultaneously",
			},
			Impact:          "All user traffic through the load balancer fails; complete service outage from user perspective",
			ResolutionSteps: []string{"Check backend health: review load balancer target group health status", "Check if backend instances are running: systemctl status <service> or kubectl get pods", "Check LB access logs for error patterns", "Verify health check path returns 200: curl http://<backend>:<port><health-path>", "Add healthy instances or fix the failing ones"},
			Prevention:      "Configure proper health checks; ensure minimum healthy instances; use auto-scaling; monitor LB error rates",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "infra-ssl-cert-expiring", Category: "infrastructure", SubCategory: "tls",
			Keywords: []string{"certificate expiring", "ssl expiry", "tls expiry", "cert expires soon"},
			Severity: "critical",
			RootCause: "TLS/SSL certificate is expiring or has already expired",
			Reasoning: []string{
				"TLS certificates have a fixed validity period; when they expire, all TLS connections fail",
				"Browsers show security warnings; API clients reject the connection entirely",
				"Once expired, there is no grace period — all secure connections fail immediately",
			},
			Impact:          "All HTTPS connections fail after expiry; users see browser security warnings; API integrations break",
			ResolutionSteps: []string{"Check expiry: openssl s_client -connect <host>:443 2>/dev/null | openssl x509 -noout -dates", "Renew with certbot: certbot renew", "For AWS ACM: certificates auto-renew if DNS validation is configured", "Deploy new certificate to the web server/load balancer", "Reload the server after installing new cert: nginx -s reload"},
			Prevention:      "Use auto-renewing certificates (Let's Encrypt/ACM); monitor expiry 30+ days ahead; maintain certificate inventory",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "infra-dns-propagation", Category: "infrastructure", SubCategory: "dns",
			Keywords: []string{"dns propagation", "dns not resolving", "dns change not working"},
			Severity: "high",
			RootCause: "DNS change has not propagated to all resolvers yet",
			Reasoning: []string{
				"DNS changes can take up to 48 hours to propagate globally (depends on TTL)",
				"Cached entries at various resolver levels serve stale data until TTL expires",
				"Some resolvers may honor TTL while others cache more aggressively",
			},
			Impact:          "Some users/services resolve the old IP; inconsistent connectivity; partial outage",
			ResolutionSteps: []string{"Check propagation: dig <domain> @8.8.8.8 vs dig <domain> @1.1.1.1", "Lower TTL before making changes: set TTL to 60s at least 1 hour before the change", "Flush local DNS cache: systemd-resolve --flush-caches", "Wait for propagation (up to old TTL value)", "Use DNS propagation checker: https://dnschecker.org"},
			Prevention:      "Lower TTL well before DNS changes; plan for propagation delay; keep old endpoints alive during transition",
			BaseConfidence: 65, BaseRiskScore: 50,
		},
		{
			ID: "infra-vpn-down", Category: "infrastructure", SubCategory: "vpn",
			Keywords: []string{"vpn down", "vpn disconnected", "tunnel down", "ipsec down"},
			Severity: "high",
			RootCause: "VPN tunnel is down — private network connectivity between sites is lost",
			Reasoning: []string{
				"VPN tunnel failure breaks connectivity between VPC/datacenter sites",
				"Services that communicate across the tunnel will fail with connection timeouts",
				"May be caused by certificate expiry, peer IP change, or network device failure",
			},
			Impact:          "Cross-site service communication fails; databases in other sites unreachable",
			ResolutionSteps: []string{"Check VPN status: show vpn ipsec status (or cloud provider console)", "Check if the peer IP/endpoint has changed", "Verify VPN certificates have not expired", "Restart the VPN service: systemctl restart strongswan (or ipsec restart)", "For cloud: check VPN gateway status in the provider console"},
			Prevention:      "Monitor VPN tunnel status; set up redundant tunnels; automate certificate renewal; maintain backup connectivity",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "infra-ntp-sync", Category: "infrastructure", SubCategory: "system",
			Keywords: []string{"ntp failure", "time sync failure", "chronyd error", "ntpd not running"},
			Severity: "medium",
			RootCause: "NTP time synchronization has failed — system clock may be drifting",
			Reasoning: []string{
				"Without NTP, system clock drifts at the rate of the hardware oscillator",
				"Clock drift causes issues with TLS, Kerberos, distributed systems, and log correlation",
				"Virtual machines drift faster than physical hardware",
			},
			Impact:          "Time-sensitive operations may fail; log timestamps become unreliable; distributed consensus breaks",
			ResolutionSteps: []string{"Check NTP status: chronyc tracking (or ntpstat)", "Restart NTP service: systemctl restart chronyd (or ntpd)", "Force sync: chronyc makestep", "Check NTP servers are reachable: chronyc sources -v", "Verify firewall allows UDP 123: iptables -L -n | grep 123"},
			Prevention:      "Ensure NTP service is running on all hosts; monitor clock offset; use multiple NTP servers",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "infra-kernel-panic", Category: "infrastructure", SubCategory: "system",
			Keywords: []string{"kernel panic", "kernel oops", "system panic infra"},
			Severity: "critical",
			RootCause: "Kernel panic — the operating system crashed and the host requires reboot",
			Reasoning: []string{
				"Kernel panics indicate a critical bug in the kernel, a driver, or hardware failure",
				"The system halted immediately; all processes were terminated without cleanup",
				"Requires reboot and post-mortem analysis of /var/crash or kdump",
			},
			Impact:          "Complete host outage; all services on the host are down; potential data corruption",
			ResolutionSteps: []string{"Reboot the host (may have auto-rebooted if panic_on_oops is set)", "Check crash logs: dmesg | grep -B5 -A10 panic", "Check /var/crash for kdump crash dumps", "If hardware: run memtest86+, check disk SMART, check CPU temperature", "If driver: update or blacklist the offending kernel module"},
			Prevention:      "Keep kernel updated; test hardware with memtest86+; configure kdump; monitor for kernel warnings in dmesg",
			BaseConfidence: 85, BaseRiskScore: 95,
		},
		{
			ID: "infra-docker-daemon-crash", Category: "infrastructure", SubCategory: "container_runtime",
			Keywords: []string{"docker daemon", "docker error", "dockerd crash", "containerd error"},
			Severity: "critical",
			RootCause: "Docker daemon or containerd has crashed — containers cannot be managed",
			Reasoning: []string{
				"Without the container runtime, no containers can be started, stopped, or managed",
				"Running containers may continue to run but cannot be managed or health-checked",
				"Kubernetes kubelet will report the node as NotReady if the runtime is down",
			},
			Impact:          "Cannot manage containers; new pods cannot be scheduled; existing containers become unmanaged",
			ResolutionSteps: []string{"Check daemon status: systemctl status docker (or containerd)", "Check logs: journalctl -u docker --since '10 min ago'", "Restart daemon: systemctl restart docker", "Check disk space: docker can crash if disk is full", "Check for corrupted overlay filesystem: check dmesg for filesystem errors"},
			Prevention:      "Monitor container runtime health; ensure adequate disk space; keep docker/containerd updated; use systemd restart=always",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "infra-systemd-service-failure", Category: "infrastructure", SubCategory: "system",
			Keywords: []string{"systemd service failure", "service failed", "failed to start", "unit entered failed state"},
			Severity: "high",
			RootCause: "A systemd-managed service has failed to start or has crashed",
			Reasoning: []string{
				"The service process exited with a non-zero exit code",
				"Common causes: configuration error, dependency not available, or binary crash",
				"systemd may attempt automatic restarts depending on the Restart= directive",
			},
			Impact:          "The specific service is unavailable; dependent services may cascade-fail",
			ResolutionSteps: []string{"Check service status: systemctl status <service>", "Check logs: journalctl -u <service> --since '10 min ago'", "Check for configuration errors: <service> --check-config (if supported)", "Restart the service: systemctl restart <service>", "Check dependencies: systemctl list-dependencies <service>"},
			Prevention:      "Use Restart=on-failure in service units; validate config before deploy; monitor service health",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "infra-cgroup-memory-limit", Category: "infrastructure", SubCategory: "container",
			Keywords: []string{"cgroup memory", "memory cgroup", "memory limit container"},
			Severity: "high",
			RootCause: "Container hit its cgroup memory limit — OOM kill by the kernel cgroup controller",
			Reasoning: []string{
				"The container tried to allocate more memory than its cgroup limit allows",
				"This is different from system OOM: only the container is affected, not the host",
				"The container runtime (Docker/containerd) reports this as OOMKilled",
			},
			Impact:          "Container is killed; service restarts; in-flight requests are lost",
			ResolutionSteps: []string{"Check container memory limit: docker inspect <container> | grep Memory", "Check cgroup stats: cat /sys/fs/cgroup/memory/<cgroup>/memory.max_usage_in_bytes", "Increase memory limit in container spec or docker-compose", "Profile application memory usage to right-size the limit", "Check for memory leaks in the application"},
			Prevention:      "Right-size container memory limits; monitor memory usage trends; implement memory leak detection",
			BaseConfidence: 80, BaseRiskScore: 70,
		},
		{
			ID: "infra-inotify-limit", Category: "infrastructure", SubCategory: "system",
			Keywords: []string{"inotify watch limit", "too many inotify", "inotify limit exceeded"},
			Severity: "medium",
			RootCause: "System inotify watch limit exceeded — file watchers cannot be created",
			Reasoning: []string{
				"Applications that watch file changes (IDEs, webpack, containers) use inotify watches",
				"Default limit (8192) is too low for systems running many containers or dev tools",
				"When exhausted, new file watches fail silently or with ENOSPC",
			},
			Impact:          "File watching applications malfunction; live-reload stops working; some services fail to start",
			ResolutionSteps: []string{"Check current watches: cat /proc/sys/fs/inotify/max_user_watches", "Increase limit: sysctl -w fs.inotify.max_user_watches=524288", "Make persistent: echo 'fs.inotify.max_user_watches=524288' >> /etc/sysctl.conf", "Check which processes use most watches: find /proc/*/fd -lname anon_inode:inotify 2>/dev/null | cut -d/ -f3 | xargs -I{} sh -c 'echo $(wc -l < /proc/{}/fdinfo/$(ls /proc/{}/fd 2>/dev/null | head -1)) {}'"},
			Prevention:      "Set max_user_watches=524288 on all servers; include in server provisioning scripts",
			BaseConfidence: 65, BaseRiskScore: 40,
		},
		{
			ID: "infra-port-conflict", Category: "infrastructure", SubCategory: "network",
			Keywords: []string{"address already in use", "port already bound", "port conflict", "bind: address already in use"},
			Severity: "high",
			RootCause: "Port conflict — another process is already using the required port",
			Reasoning: []string{
				"Two processes cannot bind to the same port on the same address",
				"The previous instance may not have shut down cleanly, leaving the port in use",
				"TCP TIME_WAIT state can keep the port bound for up to 2 minutes after close",
			},
			Impact:          "Service fails to start; the port-bound service is unavailable until conflict is resolved",
			ResolutionSteps: []string{"Find process using the port: lsof -i :<port>", "Or: ss -tlnp | grep <port>", "Kill the conflicting process: kill <PID>", "Enable port reuse: sysctl -w net.ipv4.tcp_tw_reuse=1", "Use SO_REUSEADDR in application code"},
			Prevention:      "Implement graceful shutdown; use SO_REUSEADDR; assign unique ports per service",
			BaseConfidence: 80, BaseRiskScore: 55,
		},
		{
			ID: "infra-selinux-denial", Category: "infrastructure", SubCategory: "security",
			Keywords: []string{"selinux denial", "apparmor denied", "selinux avc denied", "permission denied selinux"},
			Severity: "medium",
			RootCause: "SELinux or AppArmor is blocking an operation that the application needs",
			Reasoning: []string{
				"Mandatory access control (MAC) is denying access beyond standard UNIX permissions",
				"The application may work on one system but fail on another with stricter MAC policies",
				"Denials are logged in audit log but may not produce a user-visible error message",
			},
			Impact:          "Specific file access or network operation fails; application may behave unexpectedly",
			ResolutionSteps: []string{"Check SELinux denials: ausearch -m avc -ts recent", "Check AppArmor: dmesg | grep apparmor", "Generate and apply a policy module: audit2allow -a -M mypolicy && semodule -i mypolicy.pp", "Temporarily set permissive: setenforce 0 (WARNING: reduces security)", "For containers: adjust the SELinux label: docker run --security-opt label=disable"},
			Prevention:      "Test with MAC enabled in staging; create custom policies for your applications; never run permissive in production",
			BaseConfidence: 65, BaseRiskScore: 40,
		},
		{
			ID: "infra-hardware-ecc-error", Category: "infrastructure", SubCategory: "hardware",
			Keywords: []string{"ecc error", "memory error hardware", "correctable error", "uncorrectable error"},
			Severity: "critical",
			RootCause: "Hardware ECC memory error detected — potential data corruption or system instability",
			Reasoning: []string{
				"Correctable ECC errors indicate a DIMM is degrading and may fail soon",
				"Uncorrectable errors cause immediate data corruption and often kernel panics",
				"The affected DIMM should be replaced before it fails completely",
			},
			Impact:          "Risk of data corruption; kernel panics; application crashes from corrupted data in memory",
			ResolutionSteps: []string{"Check ECC errors: edac-util -s (or mcelog --client)", "Check dmesg: dmesg | grep -i 'mce\\|edac\\|error'", "Identify failing DIMM: edac-util -r", "Schedule DIMM replacement with hardware vendor", "For cloud: stop and start instance to move to different hardware"},
			Prevention:      "Monitor ECC error counters; replace DIMMs proactively; use cloud instances with ECC memory",
			BaseConfidence: 80, BaseRiskScore: 85,
		},
		{
			ID: "infra-disk-smart-warning", Category: "infrastructure", SubCategory: "hardware",
			Keywords: []string{"smart warning", "smart error", "disk health warning", "reallocated sector"},
			Severity: "high",
			RootCause: "Disk SMART health check is reporting warnings — disk may be failing",
			Reasoning: []string{
				"SMART attributes like Reallocated_Sector_Ct and Current_Pending_Sector indicate disk degradation",
				"The disk is still functioning but reliability is decreasing",
				"Failure is likely within weeks to months; back up data immediately",
			},
			Impact:          "Risk of sudden disk failure; data loss without backup; increasing I/O errors",
			ResolutionSteps: []string{"Check SMART status: smartctl -a /dev/sda", "Check specific attributes: smartctl -A /dev/sda | grep -E 'Reallocated|Pending|Offline'", "Start backup immediately: rsync -av /data /backup/", "Order replacement disk", "Schedule disk replacement during maintenance window"},
			Prevention:      "Monitor SMART health weekly; use RAID for redundancy; maintain regular backups; schedule proactive disk replacement",
			BaseConfidence: 80, BaseRiskScore: 75,
		},
		{
			ID: "infra-tcp-backlog-overflow", Category: "infrastructure", SubCategory: "network",
			Keywords: []string{"tcp backlog", "syn backlog", "listen overflow", "connection backlog"},
			Severity: "high",
			RootCause: "TCP listen backlog is overflowing — new connections are being dropped",
			Reasoning: []string{
				"The application's listen backlog queue is full; new SYN packets are dropped",
				"This happens when connections arrive faster than the application can accept() them",
				"The kernel has its own backlog limit (somaxconn) which may also be too low",
			},
			Impact:          "New connections are silently dropped; clients see connection timeouts",
			ResolutionSteps: []string{"Check overflow: netstat -s | grep 'listen queue'", "Increase kernel limit: sysctl -w net.core.somaxconn=65535", "Increase SYN backlog: sysctl -w net.ipv4.tcp_max_syn_backlog=65535", "Increase application listen backlog: e.g., server.listen(port, backlog=4096)", "Scale the application to accept connections faster"},
			Prevention:      "Set somaxconn=65535 on all servers; match application backlog to somaxconn; monitor listen overflows",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "infra-swap-thrashing", Category: "infrastructure", SubCategory: "memory",
			Keywords: []string{"swap thrashing", "swapping heavily", "swap in/out"},
			Severity: "critical",
			RootCause: "System is swap thrashing — pages are constantly moving between RAM and disk",
			Reasoning: []string{
				"The working set exceeds physical memory, causing constant page faults",
				"Each page fault adds milliseconds of latency as pages are read from disk",
				"The system becomes effectively unusable even though it has not OOM-killed",
			},
			Impact:          "System nearly unresponsive; all processes slow to a crawl; SSH may time out",
			ResolutionSteps: []string{"Check swap activity: vmstat 1 5 (si/so columns)", "Kill the largest memory consumer to break the cycle", "Disable swap: swapoff -a (warning: may trigger OOM)", "Add physical memory to the system", "Set swappiness to minimum: sysctl -w vm.swappiness=1"},
			Prevention:      "Size memory for the workload; disable swap for latency-sensitive services; set vm.swappiness=1",
			BaseConfidence: 80, BaseRiskScore: 85,
		},
		{
			ID: "infra-process-core-dump", Category: "infrastructure", SubCategory: "system",
			Keywords: []string{"core dump", "core dumped", "segmentation fault core"},
			Severity: "critical",
			RootCause: "A process generated a core dump — it crashed due to a memory access violation",
			Reasoning: []string{
				"Core dumps are generated on SIGSEGV, SIGABRT, or SIGFPE signals",
				"The crash is typically in native code (C/C++, CGo, JNI, native Python extensions)",
				"The core file contains the process memory state at the time of crash for debugging",
			},
			Impact:          "Process crash; service outage until restart; potential data corruption",
			ResolutionSteps: []string{"Find the core dump: find / -name 'core.*' -mmin -60 2>/dev/null", "Analyze with gdb: gdb <program> <core_file>", "Get backtrace in gdb: bt full", "Check dmesg for fault details: dmesg | grep -i segfault", "Update the crashed program or library to latest version"},
			Prevention:      "Run memory sanitizers in testing; keep libraries updated; monitor for segfaults in dmesg",
			BaseConfidence: 80, BaseRiskScore: 75,
		},
		{
			ID: "infra-watchdog-expired", Category: "infrastructure", SubCategory: "system",
			Keywords: []string{"watchdog timer", "watchdog expired", "watchdog timeout"},
			Severity: "critical",
			RootCause: "Hardware or software watchdog timer expired — the system may have been rebooted",
			Reasoning: []string{
				"Watchdog timers detect system hangs by requiring periodic heartbeat resets",
				"If the system is so hung that it cannot reset the watchdog, the watchdog triggers a reboot",
				"This indicates the kernel or critical system process was completely stuck",
			},
			Impact:          "System was forcefully rebooted; all processes were terminated without cleanup",
			ResolutionSteps: []string{"Check dmesg for watchdog trigger: dmesg | grep -i watchdog", "Check system logs before the reboot: journalctl -b -1 --since '10 min ago'", "Look for the root cause: kernel hang, I/O stall, or interrupt storm", "Check hardware: CPU temperature, memory errors, disk health", "If software issue: analyze the hang cause from logs"},
			Prevention:      "Configure watchdog with appropriate timeout; monitor for kernel warnings; investigate any hang events",
			BaseConfidence: 75, BaseRiskScore: 80,
		},
		{
			ID: "infra-raid-degraded", Category: "infrastructure", SubCategory: "storage",
			Keywords: []string{"raid degraded", "raid rebuild", "disk array degraded", "mdadm degraded"},
			Severity: "high",
			RootCause: "RAID array is operating in degraded mode after a disk failure",
			Reasoning: []string{
				"One or more disks in the RAID array have failed",
				"The array has lost redundancy — another failure means data loss",
				"I/O performance may be reduced during rebuild",
			},
			Impact:          "No fault tolerance; data loss risk on next disk failure; possible performance degradation",
			ResolutionSteps: []string{"Check RAID status: cat /proc/mdstat (Linux software RAID)", "Identify failed disk: mdadm --detail /dev/md0", "Replace failed disk and add to array: mdadm --add /dev/md0 /dev/sd<x>", "Monitor rebuild: watch cat /proc/mdstat", "Do NOT reboot during rebuild"},
			Prevention:      "Monitor RAID health; keep hot spares; schedule proactive disk replacement on SMART warnings",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "infra-deployment-failed", Category: "infrastructure", SubCategory: "deploy",
			Keywords: []string{"deployment failed", "deploy failed", "rollout failed", "release failed"},
			Severity: "critical",
			RootCause: "Service deployment failed — the new version could not be successfully rolled out",
			Reasoning: []string{
				"The deployment process encountered an error during rollout",
				"Common causes: failing health checks, missing configuration, or incompatible changes",
				"The previous version may still be running (rolling update) or may have been stopped (blue-green)",
			},
			Impact:          "New features not delivered; old version may still be running; if old version was stopped, service outage",
			ResolutionSteps: []string{"Check deployment logs for the specific failure reason", "Roll back to previous version immediately if service is impacted", "For Kubernetes: kubectl rollout undo deployment/<name>", "Check health check endpoints for the new version", "Fix the issue and redeploy through the CI/CD pipeline"},
			Prevention:      "Use canary deployments; validate health checks before full rollout; implement automatic rollback; test in staging",
			BaseConfidence: 80, BaseRiskScore: 75,
		},
		{
			ID: "infra-backup-failed", Category: "infrastructure", SubCategory: "backup",
			Keywords: []string{"backup failed", "backup error", "snapshot failed"},
			Severity: "high",
			RootCause: "Backup job failed — data is not being backed up",
			Reasoning: []string{
				"The backup process failed due to storage, connectivity, or permission issues",
				"Without successful backups, recovery point objective (RPO) is at risk",
				"Multiple consecutive failures indicate a persistent infrastructure issue",
			},
			Impact:          "Data not protected; disaster recovery capability compromised; compliance risk",
			ResolutionSteps: []string{"Check backup job logs for specific error", "Verify backup storage/destination is accessible and has space", "Check backup tool credentials and permissions", "Run backup manually to test: trigger the backup job manually", "Alert if backup hasn't succeeded in > 24 hours"},
			Prevention:      "Monitor backup success/failure; test restore procedures regularly; alert on backup failures immediately",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "infra-ssh-failure", Category: "infrastructure", SubCategory: "access",
			Keywords: []string{"ssh connection refused", "ssh timeout", "permission denied publickey", "ssh failed"},
			Severity: "high",
			RootCause: "SSH access to the server has failed — cannot remotely manage the host",
			Reasoning: []string{
				"SSH may be refused due to: service not running, firewall blocking port 22, or key authentication failure",
				"If the host is otherwise running, this is an access issue, not a service issue",
				"Failed SSH means no remote management capability for troubleshooting",
			},
			Impact:          "Cannot remotely access the server; troubleshooting and management are blocked",
			ResolutionSteps: []string{"Check if SSH service is running: systemctl status sshd (from console)", "Check firewall: iptables -L -n | grep 22", "Verify SSH key: ssh-keygen -l -f ~/.ssh/authorized_keys", "Try alternative access: console, IPMI/iLO, cloud serial console", "Check /var/log/auth.log for authentication failure details"},
			Prevention:      "Monitor SSH service health; use multiple access methods (SSH + console); rotate keys regularly; keep sshd updated",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "infra-queue-backlog", Category: "infrastructure", SubCategory: "messaging",
			Keywords: []string{"queue depth", "message queue full", "backlog growing", "queue backlog"},
			Severity: "high",
			RootCause: "Message queue backlog is growing — consumers are not keeping up with producers",
			Reasoning: []string{
				"Messages are accumulating faster than consumers can process them",
				"Consumers may be slow, failing, or insufficient in number",
				"Old messages may expire if TTL is configured, causing data loss",
			},
			Impact:          "Processing delay grows; downstream systems receive stale data; messages may expire",
			ResolutionSteps: []string{"Check queue depth: rabbitmqctl list_queues name messages (or equivalent for your broker)", "Scale up consumer instances", "Check consumer logs for processing errors or slow processing", "Purge old messages if they are no longer relevant", "Investigate why consumers slowed down (dependency issue, resource exhaustion)"},
			Prevention:      "Monitor queue depth; auto-scale consumers based on backlog; set dead-letter queues; implement backpressure",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "infra-gc-pause", Category: "infrastructure", SubCategory: "runtime",
			Keywords: []string{"gc pause", "garbage collection pause", "stop the world", "gc latency"},
			Severity: "medium",
			RootCause: "Long garbage collection pauses are causing application latency spikes",
			Reasoning: []string{
				"Stop-the-world GC pauses freeze all application threads",
				"Long pauses (> 200ms) are visible to users as latency spikes",
				"Causes: large heap, high allocation rate, or using a non-concurrent GC",
			},
			Impact:          "Periodic latency spikes; health check failures during long pauses; timeout errors from callers",
			ResolutionSteps: []string{"Check GC logs: -Xlog:gc*:file=gc.log (Java) or GODEBUG=gctrace=1 (Go)", "Switch to a low-latency GC: -XX:+UseZGC or -XX:+UseShenandoahGC (Java)", "Reduce heap pressure: optimize object allocation in hot paths", "Increase heap size to reduce GC frequency: -Xmx4g", "For Go: set GOMEMLIMIT to reduce GC frequency"},
			Prevention:      "Use low-latency GCs for latency-sensitive services; monitor GC pause times; optimize allocation rates",
			BaseConfidence: 65, BaseRiskScore: 50,
		},
		{
			ID: "infra-open-files-limit", Category: "infrastructure", SubCategory: "system",
			Keywords: []string{"too many open files infra", "file descriptor limit infra", "ulimit reached"},
			Severity: "high",
			RootCause: "System or process file descriptor limit reached — cannot open new files or connections",
			Reasoning: []string{
				"Every file, socket, and pipe uses a file descriptor",
				"Default limits (1024) are too low for server processes",
				"Leaked connections or file handles gradually exhaust the limit",
			},
			Impact:          "Cannot open new files or network connections; service fails to handle new requests",
			ResolutionSteps: []string{"Check limits: cat /proc/<PID>/limits | grep 'Max open files'", "Check usage: ls /proc/<PID>/fd | wc -l", "Increase limit: ulimit -n 65536 or set in /etc/security/limits.conf", "For systemd: add LimitNOFILE=65536 to the service unit", "Find leaked file descriptors: lsof -p <PID> | wc -l"},
			Prevention:      "Set high ulimit for server processes; audit code for resource leaks; monitor FD count",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "infra-health-check-fail", Category: "infrastructure", SubCategory: "monitoring",
			Keywords: []string{"health check failed", "healthcheck failing", "health endpoint error"},
			Severity: "high",
			RootCause: "Service health check endpoint is returning errors or not responding",
			Reasoning: []string{
				"The health check may be checking dependencies that are down",
				"The service itself may be in a degraded state",
				"Load balancers use health checks to route traffic — failing checks remove the instance",
			},
			Impact:          "Instance removed from load balancer rotation; reduced capacity; potential service degradation",
			ResolutionSteps: []string{"Test health endpoint directly: curl -v http://localhost:<port>/health", "Check which dependency is causing the health check to fail", "Check application logs for errors around the health check time", "Verify the health check path and port are configured correctly", "If the service is healthy but the check is wrong: fix the health check configuration"},
			Prevention:      "Make health checks lightweight; separate liveness from readiness checks; do not check all dependencies in health endpoint",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "infra-config-error", Category: "infrastructure", SubCategory: "config",
			Keywords: []string{"configuration error", "invalid config", "config parse error", "config syntax error"},
			Severity: "high",
			RootCause: "Service configuration is invalid — the service cannot start or is misconfigured",
			Reasoning: []string{
				"Configuration file has syntax errors, missing required fields, or invalid values",
				"This typically prevents the service from starting entirely",
				"May be caused by a recent configuration change or deployment",
			},
			Impact:          "Service fails to start; functionality breaks due to misconfiguration",
			ResolutionSteps: []string{"Check configuration syntax: <service> --check-config or validate against the schema", "Compare with the last known working configuration", "Check for environment variable substitution failures", "Roll back the configuration change", "Validate configuration in CI before deploying to production"},
			Prevention:      "Validate configuration in CI/CD pipeline; use config schemas; test config changes in staging; version control all configs",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "infra-api-gateway-error", Category: "infrastructure", SubCategory: "gateway",
			Keywords: []string{"api gateway error", "api gateway timeout", "gateway 504", "gateway 502"},
			Severity: "high",
			RootCause: "API gateway is returning errors — backend service is unreachable or timing out",
			Reasoning: []string{
				"The gateway cannot forward requests to the backend service successfully",
				"502/504 from the gateway indicates backend connectivity or timeout issues",
				"Rate limiting at the gateway level may also be rejecting requests",
			},
			Impact:          "API requests fail; external consumers receive error responses; integrations break",
			ResolutionSteps: []string{"Check gateway logs for backend connection errors", "Check backend service health directly (bypass gateway)", "Verify gateway route configuration points to correct backend", "Increase gateway timeout if backend is legitimately slow", "Check rate limit configuration: adjust if legitimate traffic is being rejected"},
			Prevention:      "Monitor gateway error rates; configure appropriate timeouts; implement circuit breakers at gateway level",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
	}
}

func buildAWSEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "aws-ec2-unreachable", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"ec2 unreachable", "ec2 instance unreachable", "instance not reachable aws"},
			Severity: "critical",
			RootCause: "AWS EC2 instance is unreachable — the instance may have failed or lost network",
			Reasoning: []string{
				"The instance may have crashed, hit a hardware failure, or lost its network interface",
				"AWS may have retired the underlying hardware without automatic recovery",
				"Security group or network ACL changes may have blocked access",
			},
			Impact:          "Service on the instance is completely unavailable; no SSH access possible",
			ResolutionSteps: []string{"Check instance status: aws ec2 describe-instance-status --instance-id <id>", "Check system and instance status checks in AWS Console", "Try stopping and starting the instance (moves to new hardware): aws ec2 stop-instances --instance-ids <id> && aws ec2 start-instances --instance-ids <id>", "Check VPC flow logs for rejected traffic", "Check security groups: aws ec2 describe-security-groups --group-ids <sg-id>"},
			Prevention:      "Use auto-scaling groups; enable detailed monitoring; configure instance recovery alarms; use multiple AZs",
			BaseConfidence: 80, BaseRiskScore: 85,
		},
		{
			ID: "aws-rds-connection-limit", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"rds connection limit", "rds too many connections", "rds max connections"},
			Severity: "critical",
			RootCause: "AWS RDS instance has reached its maximum connection limit",
			Reasoning: []string{
				"RDS max_connections is determined by the instance class memory",
				"Without connection pooling, each application instance opens its own connections",
				"Connection leaks or slow queries exacerbate the problem",
			},
			Impact:          "New database connections are rejected; applications fail to connect; user-facing errors",
			ResolutionSteps: []string{"Check connections: SELECT count(*) FROM pg_stat_activity (PostgreSQL) or SHOW STATUS LIKE 'Threads_connected' (MySQL)", "Use RDS Proxy for connection pooling: aws rds create-db-proxy", "Kill idle connections on the database", "Scale up to a larger instance class (more connections)", "Deploy application-level connection pooling (PgBouncer, ProxySQL)"},
			Prevention:      "Use RDS Proxy or PgBouncer; right-size instance class; monitor connection count; set connection timeouts",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "aws-s3-access-denied", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"s3 access denied", "s3 403", "bucket policy denied"},
			Severity: "high",
			RootCause: "AWS S3 access denied — IAM policy or bucket policy is blocking the operation",
			Reasoning: []string{
				"The IAM role/user does not have the required S3 permissions",
				"The bucket policy may explicitly deny the operation",
				"S3 Block Public Access settings may be blocking the request",
			},
			Impact:          "Cannot read/write to S3; file uploads/downloads fail; application functionality breaks",
			ResolutionSteps: []string{"Check IAM policy: aws iam get-role-policy --role-name <role> --policy-name <policy>", "Check bucket policy: aws s3api get-bucket-policy --bucket <name>", "Check Block Public Access: aws s3api get-public-access-block --bucket <name>", "Test with AWS CLI: aws s3 ls s3://<bucket>/", "Grant required permissions: add s3:GetObject, s3:PutObject to the IAM policy"},
			Prevention:      "Use infrastructure-as-code for IAM policies; test permissions before deploy; use least-privilege principle",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "aws-lambda-timeout", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"lambda timeout", "task timed out lambda", "lambda duration exceeded"},
			Severity: "high",
			RootCause: "AWS Lambda function exceeded its configured timeout",
			Reasoning: []string{
				"Lambda has a maximum timeout of 15 minutes (default is often 3 seconds)",
				"The function is taking longer than expected due to slow dependencies or cold start",
				"Cold starts add 100ms-10s of latency depending on runtime and VPC configuration",
			},
			Impact:          "Function invocation fails; downstream systems do not receive the result",
			ResolutionSteps: []string{"Increase timeout: aws lambda update-function-configuration --function-name <name> --timeout 30", "Check CloudWatch logs for where time is spent", "Optimize cold start: use provisioned concurrency for critical functions", "Move long operations to Step Functions or ECS tasks", "Check if the function is waiting on a VPC resource (common cold start cause)"},
			Prevention:      "Set appropriate timeouts; use provisioned concurrency; optimize function code; avoid VPC when not needed",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "aws-elb-5xx", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"elb 5xx", "alb 502", "alb 503", "elb errors aws"},
			Severity: "high",
			RootCause: "AWS ELB/ALB is returning 5xx errors — backend targets are unhealthy or not responding",
			Reasoning: []string{
				"502 means the target sent an invalid response; 503 means no healthy targets",
				"504 means the target did not respond within the idle timeout",
				"All target instances may have failed health checks",
			},
			Impact:          "User traffic receives error responses; service degraded or unavailable",
			ResolutionSteps: []string{"Check target health: aws elbv2 describe-target-health --target-group-arn <arn>", "Check ALB access logs in S3 for error details", "Verify target instances are running and healthy", "Check security groups between ALB and targets", "Increase deregistration delay to allow in-flight requests to complete"},
			Prevention:      "Configure proper health checks; use auto-scaling; monitor target health; set appropriate timeouts",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "aws-sqs-visibility-timeout", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"sqs visibility timeout", "message reprocessed", "sqs duplicate"},
			Severity: "medium",
			RootCause: "SQS message visibility timeout expired — messages are being reprocessed",
			Reasoning: []string{
				"When a consumer takes longer than the visibility timeout, the message becomes visible again",
				"Another consumer picks it up, leading to duplicate processing",
				"Default visibility timeout is 30 seconds, which may be too short",
			},
			Impact:          "Messages processed multiple times; duplicate actions; data inconsistency",
			ResolutionSteps: []string{"Increase visibility timeout: aws sqs set-queue-attributes --queue-url <url> --attributes VisibilityTimeout=300", "Make message processing idempotent", "Use SQS FIFO queues with exactly-once processing for critical messages", "Monitor ApproximateNumberOfMessagesNotVisible metric", "Delete messages immediately after successful processing"},
			Prevention:      "Set visibility timeout to 6x average processing time; make consumers idempotent; use dead-letter queues",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "aws-dynamodb-throttling", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"dynamodb throttling", "provisioned throughput exceeded", "dynamodb capacity"},
			Severity: "high",
			RootCause: "DynamoDB is throttling requests — provisioned capacity or on-demand limits exceeded",
			Reasoning: []string{
				"Requests exceed the provisioned read/write capacity units (RCU/WCU)",
				"Hot partition keys cause throttling even when total capacity is sufficient",
				"Burst capacity may have been exhausted by sustained high traffic",
			},
			Impact:          "Read/write requests are rejected; application sees throttling errors; data operations slow down",
			ResolutionSteps: []string{"Check throttling: CloudWatch ThrottledRequests metric", "Switch to on-demand capacity: aws dynamodb update-table --billing-mode PAY_PER_REQUEST", "Or increase provisioned capacity: aws dynamodb update-table --provisioned-throughput ReadCapacityUnits=100,WriteCapacityUnits=100", "Check for hot keys: enable CloudWatch Contributor Insights", "Distribute load across partition keys"},
			Prevention:      "Use on-demand for unpredictable workloads; implement exponential backoff; design for uniform key distribution",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "aws-iam-permission-denied", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"iam permission denied", "access denied aws", "not authorized aws", "iam policy"},
			Severity: "high",
			RootCause: "AWS IAM permission denied — the role/user lacks required permissions for the API call",
			Reasoning: []string{
				"The IAM policy attached to the role/user does not include the required AWS action",
				"Service Control Policies (SCPs) may be blocking the action at the organization level",
				"Resource-based policies may explicitly deny the action",
			},
			Impact:          "The specific AWS API call fails; functionality depending on that AWS service breaks",
			ResolutionSteps: []string{"Check which action was denied from the error message", "Check IAM policies: aws iam list-attached-role-policies --role-name <role>", "Use IAM Access Analyzer to identify missing permissions", "Add the required permission to the IAM policy", "Check SCPs if in AWS Organizations: aws organizations list-policies --filter SERVICE_CONTROL_POLICY"},
			Prevention:      "Use IAM Access Analyzer; manage policies as code (Terraform/CDK); test permissions in staging",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "aws-route53-health-check", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"route53 health check failed", "route53 unhealthy", "health check failed aws"},
			Severity: "high",
			RootCause: "AWS Route53 health check is failing — DNS failover may have triggered",
			Reasoning: []string{
				"Route53 health checks monitor endpoint availability from multiple regions",
				"A failing health check can trigger DNS failover to a secondary endpoint",
				"The endpoint may be down, returning errors, or network path is blocked",
			},
			Impact:          "DNS may failover to secondary; if no failover configured, users are routed to unhealthy endpoint",
			ResolutionSteps: []string{"Check health check status: aws route53 get-health-check-status --health-check-id <id>", "Verify the endpoint is accessible from the internet", "Check if the health check path returns 200: curl -v https://<endpoint>/<path>", "Check security groups allow Route53 health check IPs", "Fix the endpoint issue or update the health check configuration"},
			Prevention:      "Configure failover routing with health checks; monitor health check status; ensure health check endpoints are lightweight",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "aws-cloudwatch-alarm", Category: "cloud", SubCategory: "aws",
			Keywords: []string{"cloudwatch alarm", "alarm triggered aws", "alarm state aws"},
			Severity: "high",
			RootCause: "AWS CloudWatch alarm has triggered — a monitored metric exceeded its threshold",
			Reasoning: []string{
				"A metric crossed the alarm threshold for the required number of evaluation periods",
				"This is an early warning system — the underlying issue needs investigation",
				"The alarm may trigger SNS notifications, Auto Scaling actions, or Lambda functions",
			},
			Impact:          "Depends on the metric that triggered; may indicate resource exhaustion, errors, or performance degradation",
			ResolutionSteps: []string{"Check alarm details: aws cloudwatch describe-alarms --alarm-names <name>", "Check the metric: aws cloudwatch get-metric-statistics (for the triggering metric)", "Identify the resource and metric from the alarm configuration", "Investigate the underlying cause based on the metric type", "Acknowledge and resolve the issue; set alarm back to OK after fix"},
			Prevention:      "Set appropriate alarm thresholds; configure actions (SNS, Auto Scaling); review alarm history regularly",
			BaseConfidence: 65, BaseRiskScore: 55,
		},
	}
}

func buildGCPEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "gcp-compute-preemption", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"preempted", "compute preemption", "preemptible vm gcp", "spot instance gcp"},
			Severity: "high",
			RootCause: "GCP preemptible/spot VM was preempted — instance was terminated by Google",
			Reasoning: []string{
				"Preemptible VMs can be stopped by Google at any time with 30 seconds notice",
				"This is expected behavior for cost savings but requires fault-tolerant architecture",
				"Preemption typically happens when GCP needs capacity back",
			},
			Impact:          "Instance terminated; service on that instance goes down; workload must be rescheduled",
			ResolutionSteps: []string{"Check preemption: gcloud compute operations list --filter='operationType=compute.instances.preempted'", "Verify new instances were created by the managed instance group", "Use managed instance groups with auto-healing for automatic replacement", "Mix preemptible and on-demand instances in the group", "Implement graceful shutdown handling for the 30s warning"},
			Prevention:      "Use managed instance groups; mix preemptible with on-demand; implement graceful shutdown; use GKE Spot pods",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "gcp-cloud-sql-connection-limit", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"cloud sql connection limit", "cloud sql too many connections", "cloud sql max connections"},
			Severity: "critical",
			RootCause: "GCP Cloud SQL has reached its maximum connection limit",
			Reasoning: []string{
				"Cloud SQL max_connections is set based on the instance tier/memory",
				"Without connection pooling, each application instance opens its own connections",
				"Connection leaks in application code gradually exhaust the pool",
			},
			Impact:          "New connections rejected; applications fail; user-facing errors",
			ResolutionSteps: []string{"Check connections via Cloud SQL Admin API or Cloud Console", "Use Cloud SQL Auth Proxy for connection management", "Deploy PgBouncer or ProxySQL as a connection pooler", "Scale up the Cloud SQL instance tier for more connections", "Fix connection leaks in application code"},
			Prevention:      "Use Cloud SQL Auth Proxy; implement connection pooling; monitor connection count; set connection timeouts",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "gcp-gke-node-pool-exhausted", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"gke node pool exhausted", "no nodes available gke", "insufficient resources gke"},
			Severity: "high",
			RootCause: "GKE node pool has no capacity for new pods — all nodes are fully allocated",
			Reasoning: []string{
				"All nodes in the pool have fully committed CPU and memory resources",
				"The cluster autoscaler may have hit its maximum node count",
				"The GCP project may have hit its compute engine quota",
			},
			Impact:          "New pods remain Pending; deployments cannot scale; services cannot grow",
			ResolutionSteps: []string{"Check pending pods: kubectl get pods --field-selector=status.phase=Pending", "Check cluster autoscaler: kubectl describe configmap cluster-autoscaler-status -n kube-system", "Increase max nodes: gcloud container node-pools update <pool> --max-nodes=10", "Check GCP quotas: gcloud compute project-info describe", "Add a new node pool with larger machines"},
			Prevention:      "Configure cluster autoscaler with appropriate max nodes; monitor resource utilization; set GCP quota alerts",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "gcp-cloud-functions-timeout", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"cloud functions timeout", "function timeout gcp", "function exceeded deadline"},
			Severity: "high",
			RootCause: "GCP Cloud Function exceeded its configured timeout (max 540s for 1st gen, 3600s for 2nd gen)",
			Reasoning: []string{
				"The function took longer than its timeout to complete",
				"Common causes: slow external API calls, large data processing, or cold start",
				"2nd gen functions support up to 60 minutes; 1st gen is limited to 9 minutes",
			},
			Impact:          "Function invocation fails; dependent systems do not receive results; event may be retried",
			ResolutionSteps: []string{"Increase timeout: gcloud functions deploy <name> --timeout=300s", "Check Cloud Logging for function execution details", "Optimize function code: reduce API calls, use caching", "Use Cloud Run for long-running workloads (up to 60 minutes)", "Consider using Pub/Sub + Cloud Run for async processing"},
			Prevention:      "Set appropriate timeouts; optimize function performance; use Cloud Run for long tasks; monitor execution duration",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "gcp-lb-5xx", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"cloud load balancing 5xx", "gcp lb error", "backend service unhealthy gcp"},
			Severity: "high",
			RootCause: "GCP Cloud Load Balancing is returning 5xx errors — backends are unhealthy",
			Reasoning: []string{
				"Backend instances or NEGs are failing health checks",
				"502 indicates backend sent invalid response; 503 means no healthy backends",
				"Firewall rules may be blocking health check probes from GCP ranges",
			},
			Impact:          "User-facing traffic receives error responses; service availability degraded",
			ResolutionSteps: []string{"Check backend health: gcloud compute backend-services get-health <name>", "Check health check configuration: gcloud compute health-checks describe <name>", "Verify firewall allows GCP health check ranges (130.211.0.0/22, 35.191.0.0/16)", "Check backend instance/pod health directly", "Review load balancer logs in Cloud Logging"},
			Prevention:      "Allow GCP health check IP ranges in firewall; configure proper health checks; monitor backend health",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "gcp-pubsub-backlog", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"pubsub backlog", "message backlog gcp", "pubsub undelivered"},
			Severity: "high",
			RootCause: "GCP Pub/Sub subscription has a growing message backlog — consumers are not keeping up",
			Reasoning: []string{
				"Messages are being published faster than subscribers can process them",
				"Subscribers may be failing, slow, or insufficient in number",
				"Old messages may expire (default retention is 7 days)",
			},
			Impact:          "Message processing delay grows; downstream systems receive stale data; messages may expire",
			ResolutionSteps: []string{"Check backlog: gcloud pubsub subscriptions describe <name> (look at backlog_message_count)", "Scale up consumer instances", "Check consumer logs for processing errors", "Increase ack deadline: gcloud pubsub subscriptions update <name> --ack-deadline=60", "Purge old messages if needed: gcloud pubsub subscriptions seek <name> --time=now"},
			Prevention:      "Monitor subscription backlog; auto-scale consumers based on backlog; set appropriate ack deadlines",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "gcp-bigquery-quota", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"bigquery quota", "bigquery rate limit", "exceeded quota bigquery"},
			Severity: "medium",
			RootCause: "GCP BigQuery quota exceeded — queries or API calls are being rate limited",
			Reasoning: []string{
				"BigQuery has quotas on concurrent queries, bytes scanned, and API calls",
				"Concurrent query limit is typically 100 per project",
				"Streaming insert quota can also be exceeded with high-throughput applications",
			},
			Impact:          "Queries fail or are queued; analytics pipelines are delayed",
			ResolutionSteps: []string{"Check quotas: gcloud alpha bq quotas list", "Reduce concurrent queries by batching or scheduling", "Request quota increase: GCP Console > IAM > Quotas", "Use BigQuery reservations for guaranteed capacity", "Optimize queries to scan less data (use partitioned tables)"},
			Prevention:      "Monitor quota usage; use reservations for production workloads; partition and cluster tables; batch queries",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "gcp-iam-denied", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"iam permission denied gcp", "access denied gcp", "not authorized gcp"},
			Severity: "high",
			RootCause: "GCP IAM permission denied — the service account lacks required permissions",
			Reasoning: []string{
				"The service account does not have the required IAM role for the operation",
				"Organization policies may restrict certain operations",
				"IAM permission changes can take up to 60 seconds to propagate",
			},
			Impact:          "The specific GCP API call fails; application functionality depending on that API breaks",
			ResolutionSteps: []string{"Check error details for which permission is needed", "Check current roles: gcloud projects get-iam-policy <project>", "Grant required role: gcloud projects add-iam-policy-binding <project> --member=<sa> --role=<role>", "Use IAM recommender: gcloud recommender recommendations list --recommender=google.iam.policy.Recommender", "Check organization policies: gcloud resource-manager org-policies list"},
			Prevention:      "Use infrastructure-as-code for IAM; test permissions in staging; follow least-privilege principle",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "gcp-dns-failure", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"cloud dns failure", "gcp dns error", "dns resolution gcp"},
			Severity: "critical",
			RootCause: "GCP Cloud DNS resolution failure — managed zone records are not resolving",
			Reasoning: []string{
				"Cloud DNS managed zones may have misconfigured records",
				"DNS propagation for new records takes time",
				"NS delegation to Cloud DNS may not be properly configured at the registrar",
			},
			Impact:          "DNS resolution fails; services cannot be reached by hostname; user traffic affected",
			ResolutionSteps: []string{"Check records: gcloud dns record-sets list --zone=<zone>", "Test resolution: dig <domain> @ns-cloud-a1.googledomains.com", "Verify NS delegation at registrar matches Cloud DNS nameservers", "Check managed zone status: gcloud dns managed-zones describe <zone>", "Wait for propagation if records were recently changed"},
			Prevention:      "Lower TTL before DNS changes; verify NS delegation; monitor DNS resolution; use multiple zones for redundancy",
			BaseConfidence: 75, BaseRiskScore: 70,
		},
		{
			ID: "gcp-gcs-access-denied", Category: "cloud", SubCategory: "gcp",
			Keywords: []string{"gcs access denied", "gcs 403", "bucket access denied gcp", "storage access denied"},
			Severity: "high",
			RootCause: "GCP Cloud Storage access denied — insufficient permissions on the bucket or object",
			Reasoning: []string{
				"The service account or user lacks the required storage IAM role",
				"Bucket-level ACLs may be overriding IAM policies",
				"Uniform bucket-level access may prevent object-level ACLs from working",
			},
			Impact:          "Cannot read/write to Cloud Storage; file operations fail; application functionality broken",
			ResolutionSteps: []string{"Check bucket IAM: gsutil iam get gs://<bucket>", "Grant access: gsutil iam ch serviceAccount:<sa>:objectViewer gs://<bucket>", "Check uniform bucket-level access: gsutil ubla get gs://<bucket>", "Test access: gsutil ls gs://<bucket>/", "Verify the service account is attached to the workload"},
			Prevention:      "Use uniform bucket-level access; manage IAM with infrastructure-as-code; test permissions in staging",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
	}
}

func buildAzureEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "azure-vm-not-responding", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"azure vm not responding", "vm unresponsive azure", "azure instance unreachable"},
			Severity: "critical",
			RootCause: "Azure VM is not responding — the instance may have crashed or lost network",
			Reasoning: []string{
				"The VM may have experienced a host-level failure or guest OS crash",
				"Azure may have initiated maintenance that affected the VM",
				"Network Security Group rules may have been changed, blocking access",
			},
			Impact:          "Service on the VM is completely unavailable; cannot SSH/RDP to the VM",
			ResolutionSteps: []string{"Check VM status: az vm get-instance-view --resource-group <rg> --name <vm>", "Check boot diagnostics: az vm boot-diagnostics get-boot-log --resource-group <rg> --name <vm>", "Restart the VM: az vm restart --resource-group <rg> --name <vm>", "If unresponsive: redeploy to new host: az vm redeploy --resource-group <rg> --name <vm>", "Check NSG rules: az network nsg rule list --nsg-name <nsg> --resource-group <rg>"},
			Prevention:      "Use availability sets/zones; enable boot diagnostics; configure Azure Monitor alerts; use VMSS for auto-healing",
			BaseConfidence: 80, BaseRiskScore: 85,
		},
		{
			ID: "azure-sql-throttling", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"azure sql throttling", "dtu limit exceeded", "azure sql rate limit"},
			Severity: "high",
			RootCause: "Azure SQL Database is throttling requests — DTU or vCore limit exceeded",
			Reasoning: []string{
				"Azure SQL enforces resource limits based on the service tier (DTU or vCore)",
				"Exceeding these limits results in request throttling (wait/retry required)",
				"Common during traffic spikes or complex queries that consume excessive resources",
			},
			Impact:          "Database queries are delayed or rejected; application response times increase",
			ResolutionSteps: []string{"Check DTU usage: Azure Portal > SQL Database > Metrics > DTU percentage", "Scale up: az sql db update --resource-group <rg> --server <server> --name <db> --service-objective S3", "Optimize queries consuming excessive DTUs", "Implement retry logic with exponential backoff", "Consider elastic pools for variable workloads"},
			Prevention:      "Monitor DTU/vCore usage; set alerts at 80%; use auto-scaling; optimize query performance",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "azure-aks-node-not-ready", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"aks node not ready", "azure kubernetes node", "aks node issue"},
			Severity: "critical",
			RootCause: "AKS node is in NotReady state — kubelet is not healthy on the node",
			Reasoning: []string{
				"The Azure node may have disk pressure, memory pressure, or kubelet crash",
				"Azure may be performing node maintenance or OS updates",
				"Virtual machine scale set instance may have failed",
			},
			Impact:          "Pods on the node are evicted; scheduling capacity reduced; potential service degradation",
			ResolutionSteps: []string{"Check node status: kubectl describe node <node>", "Check AKS health: az aks show --resource-group <rg> --name <cluster>", "Cordon and drain the unhealthy node: kubectl cordon <node> && kubectl drain <node>", "Restart the node: restart the VMSS instance via Azure Portal", "If persistent: delete the node and let AKS auto-scale a replacement"},
			Prevention:      "Use cluster autoscaler; enable node auto-repair; monitor node health; use multiple node pools",
			BaseConfidence: 80, BaseRiskScore: 75,
		},
		{
			ID: "azure-functions-timeout", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"azure functions timeout", "function timeout azure", "function exceeded timeout"},
			Severity: "high",
			RootCause: "Azure Function exceeded its timeout limit (5 min consumption, 30 min premium/dedicated)",
			Reasoning: []string{
				"The function took longer than the maximum allowed execution time",
				"Cold starts in consumption plan can add seconds to startup",
				"The function may be waiting on a slow external dependency",
			},
			Impact:          "Function invocation fails; dependent systems do not receive the result",
			ResolutionSteps: []string{"Increase timeout in host.json: functionTimeout setting", "Use Premium plan for longer timeouts and no cold starts", "Optimize function execution time: reduce external calls, use caching", "Use Durable Functions for long-running workflows", "Move to Azure Container Apps for workloads requiring > 30 min"},
			Prevention:      "Set appropriate timeouts; use Premium plan for production; optimize function code; use Durable Functions for orchestration",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "azure-app-gateway-5xx", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"application gateway 5xx", "app gateway error azure", "app gateway backend unhealthy"},
			Severity: "high",
			RootCause: "Azure Application Gateway is returning 5xx errors — backend pool is unhealthy",
			Reasoning: []string{
				"Backend instances are failing the Application Gateway health probe",
				"502 means backend returned invalid response; 503 means no healthy backends",
				"NSG rules may be blocking health probe traffic from the gateway subnet",
			},
			Impact:          "External traffic receives errors; users cannot access the application",
			ResolutionSteps: []string{"Check backend health: az network application-gateway show-backend-health --name <gw> --resource-group <rg>", "Check health probe configuration: az network application-gateway probe list --gateway-name <gw> --resource-group <rg>", "Verify NSG allows traffic from the Application Gateway subnet", "Check backend instance health directly", "Review Application Gateway access logs for error details"},
			Prevention:      "Configure proper health probes; allow health probe traffic in NSGs; monitor backend health; use auto-scaling for backends",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "azure-service-bus-dead-letter", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"service bus dead letter", "dead letter queue azure", "dlq azure"},
			Severity: "medium",
			RootCause: "Messages are accumulating in Azure Service Bus dead-letter queue",
			Reasoning: []string{
				"Messages land in DLQ after exceeding MaxDeliveryCount (default 10) or TTL expiry",
				"The consumer is failing to process certain messages, causing repeated retries",
				"DLQ messages require manual inspection and remediation",
			},
			Impact:          "Some messages are not being processed; business operations depending on those messages are delayed",
			ResolutionSteps: []string{"Check DLQ: az servicebus queue show --name <queue>$DeadLetterQueue --namespace-name <ns> --resource-group <rg>", "Peek at DLQ messages to understand failure reasons", "Fix the processing issue in the consumer", "Resubmit salvageable messages from DLQ to the main queue", "Increase MaxDeliveryCount if failures are transient"},
			Prevention:      "Monitor DLQ depth; make consumers idempotent; handle poison messages gracefully; set alerts on DLQ growth",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "azure-cosmos-rate-limited", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"cosmos db rate limited", "cosmos 429", "cosmos throttled", "request rate large"},
			Severity: "high",
			RootCause: "Azure Cosmos DB is rate limiting requests — provisioned RU/s exceeded",
			Reasoning: []string{
				"The request consumed more RU/s than the provisioned throughput allows",
				"Hot partitions can cause throttling even when total RU/s is sufficient",
				"Large queries or cross-partition queries consume more RUs",
			},
			Impact:          "Read/write operations are throttled; application latency increases; requests fail with 429",
			ResolutionSteps: []string{"Check RU consumption: Azure Portal > Cosmos DB > Metrics > Total Request Units", "Increase provisioned throughput: az cosmosdb sql container throughput update --throughput <RUs>", "Use autoscale throughput for variable workloads", "Optimize queries: use point reads instead of queries; filter by partition key", "Distribute data evenly across partitions"},
			Prevention:      "Use autoscale throughput; design for even partition distribution; monitor RU consumption; optimize query RU cost",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "azure-key-vault-denied", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"key vault access denied", "key vault 403", "azure key vault forbidden"},
			Severity: "high",
			RootCause: "Azure Key Vault access denied — identity lacks required access policy or RBAC role",
			Reasoning: []string{
				"The managed identity or service principal does not have a Key Vault access policy",
				"If using RBAC: the required Key Vault role (Secret User, Crypto User) is not assigned",
				"Key Vault firewall may be blocking the request if network rules are configured",
			},
			Impact:          "Application cannot read secrets, keys, or certificates; startup may fail; encryption/decryption fails",
			ResolutionSteps: []string{"Check access policies: az keyvault show --name <vault>", "Add access policy: az keyvault set-policy --name <vault> --object-id <identity> --secret-permissions get list", "Or grant RBAC: az role assignment create --role 'Key Vault Secrets User' --assignee <identity> --scope <vault-id>", "Check network rules: az keyvault network-rule list --name <vault>", "Verify managed identity is enabled on the compute resource"},
			Prevention:      "Use managed identities for authentication; manage access policies as code; monitor Key Vault access logs",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "azure-dns-failure", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"azure dns failure", "azure dns error", "private dns zone azure"},
			Severity: "critical",
			RootCause: "Azure DNS zone resolution failure — DNS records are not resolving correctly",
			Reasoning: []string{
				"Azure DNS zone may have incorrect records or the zone may not be linked to the VNet",
				"Private DNS zones must be linked to VNets to resolve within those networks",
				"DNS propagation may not be complete for recent changes",
			},
			Impact:          "Services cannot resolve hostnames; connectivity breaks; application errors",
			ResolutionSteps: []string{"Check DNS zone records: az network dns record-set list --zone-name <zone> --resource-group <rg>", "For private DNS: verify VNet link: az network private-dns link vnet list --zone-name <zone> --resource-group <rg>", "Test resolution: nslookup <record> from within the VNet", "Check if the zone is properly delegated (for public zones)", "Create missing records or fix incorrect ones"},
			Prevention:      "Automate DNS management with infrastructure-as-code; monitor DNS resolution; verify VNet links after changes",
			BaseConfidence: 75, BaseRiskScore: 70,
		},
		{
			ID: "azure-blob-access-denied", Category: "cloud", SubCategory: "azure",
			Keywords: []string{"blob storage access denied", "azure storage 403", "blob access denied"},
			Severity: "high",
			RootCause: "Azure Blob Storage access denied — insufficient permissions or incorrect credentials",
			Reasoning: []string{
				"The identity does not have the required RBAC role (Storage Blob Data Reader/Contributor)",
				"The shared access signature (SAS) may have expired",
				"The storage account firewall may be blocking the request",
			},
			Impact:          "Cannot read/write to Blob Storage; file operations fail; application functionality broken",
			ResolutionSteps: []string{"Check RBAC: az role assignment list --scope <storage-account-id>", "Grant access: az role assignment create --role 'Storage Blob Data Contributor' --assignee <identity> --scope <id>", "Check SAS token expiry if using SAS authentication", "Check firewall rules: az storage account show --name <account> --query networkRuleSet", "Use managed identity instead of connection strings for authentication"},
			Prevention:      "Use managed identities; manage RBAC as code; monitor access denied events; set firewall rules appropriately",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
	}
}
