package services

func buildKubernetesEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "k8s-crashloopbackoff", Category: "kubernetes", SubCategory: "pod",
			Keywords: []string{"crashloopbackoff", "crash loop", "back-off restarting"},
			Severity: "critical",
			RootCause: "Pod is crash-looping — the container starts, crashes, and restarts repeatedly",
			Reasoning: []string{
				"The container exits almost immediately after starting, triggering Kubernetes restart",
				"Kubernetes applies exponential backoff between restarts (10s, 20s, 40s...)",
				"Common causes: missing config/secrets, unresolvable dependencies, application bugs",
			},
			Impact:          "Service is effectively down; pods never reach Ready state; no traffic is served",
			ResolutionSteps: []string{"Check crash logs: kubectl logs <pod> --previous", "Check events: kubectl describe pod <pod>", "Check if configmap/secret is missing: kubectl get configmap,secret -n <namespace>", "Check if the image exists and is pullable: docker pull <image>", "Fix the application error, rebuild and redeploy"},
			Prevention:      "Test container startup in CI; validate all required env vars/secrets exist; use readiness/liveness probes",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "k8s-oomkilled", Category: "kubernetes", SubCategory: "pod",
			Keywords: []string{"oomkilled", "oom killed", "out of memory killed kubernetes"},
			Severity: "critical",
			RootCause: "Pod was killed by Kubernetes OOM killer because it exceeded its memory limit",
			Reasoning: []string{
				"The container tried to use more memory than its resources.limits.memory allows",
				"Kubernetes kills the container immediately — no graceful shutdown",
				"The pod will be restarted, but may OOM-kill again if the limit is too low",
			},
			Impact:          "Service interruption during restart; in-flight requests lost; may repeat if limit is wrong",
			ResolutionSteps: []string{"Check OOM details: kubectl describe pod <pod> | grep -A5 'Last State'", "Increase memory limit: resources.limits.memory in the pod spec", "Profile memory: check application metrics for heap/RSS growth", "Check for memory leaks in the application", "Set resources.requests.memory close to resources.limits.memory for predictable behavior"},
			Prevention:      "Right-size memory limits based on profiling; set memory requests = limits; implement memory leak detection",
			BaseConfidence: 85, BaseRiskScore: 80,
		},
		{
			ID: "k8s-imagepullbackoff", Category: "kubernetes", SubCategory: "pod",
			Keywords: []string{"imagepullbackoff", "errimagepull", "failed to pull image"},
			Severity: "high",
			RootCause: "Pod cannot pull its container image — image does not exist or registry auth failed",
			Reasoning: []string{
				"The container image tag does not exist in the registry, or the registry is unreachable",
				"ImagePullSecrets may be missing or contain wrong credentials",
				"Private registries require authentication that may have expired",
			},
			Impact:          "Pod cannot start; service is unavailable; deployment is stuck",
			ResolutionSteps: []string{"Check error detail: kubectl describe pod <pod> | grep -A3 Events", "Verify image exists: docker pull <image> (from a machine with access)", "Check imagePullSecrets: kubectl get pod <pod> -o jsonpath='{.spec.imagePullSecrets}'", "Create/update pull secret: kubectl create secret docker-registry regcred --docker-server=<url> --docker-username=<user> --docker-password=<pass>", "Verify image tag is correct in the deployment spec"},
			Prevention:      "Use immutable image tags (SHA digests); validate image existence in CI before deploy; automate registry credentials",
			BaseConfidence: 80, BaseRiskScore: 65,
		},
		{
			ID: "k8s-node-not-ready", Category: "kubernetes", SubCategory: "node",
			Keywords: []string{"node not ready", "nodenotready", "node condition"},
			Severity: "critical",
			RootCause: "Kubernetes node is in NotReady state — kubelet is not reporting healthy status",
			Reasoning: []string{
				"The kubelet on the node stopped heartbeating to the API server",
				"Common causes: kubelet crash, disk pressure, memory pressure, or network partition",
				"Pods on the NotReady node will be evicted after the pod-eviction-timeout (5 min default)",
			},
			Impact:          "Pods on the node will be evicted; scheduling capacity reduced; potential service degradation",
			ResolutionSteps: []string{"Check node status: kubectl describe node <node>", "SSH to node and check kubelet: systemctl status kubelet", "Check kubelet logs: journalctl -u kubelet --since '10 min ago'", "Check disk pressure: df -h on the node", "Check memory pressure: free -h on the node"},
			Prevention:      "Monitor node health; run node problem detector; set up automatic node repair; use cluster autoscaler",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "k8s-pvc-pending", Category: "kubernetes", SubCategory: "storage",
			Keywords: []string{"pvc pending", "persistentvolumeclaim pending", "no persistent volumes available"},
			Severity: "high",
			RootCause: "PersistentVolumeClaim is stuck in Pending — no matching PersistentVolume available",
			Reasoning: []string{
				"No PV matches the PVC's storage class, size, or access mode requirements",
				"The StorageClass provisioner may be failing to create new volumes",
				"Cloud provider quota for the volume type may be exceeded",
			},
			Impact:          "Pod cannot start because its volume is not available; data-dependent service is down",
			ResolutionSteps: []string{"Check PVC events: kubectl describe pvc <name>", "Check if StorageClass exists: kubectl get storageclass", "Check provisioner pods: kubectl get pods -n kube-system | grep csi", "Check cloud provider quotas for volumes", "Manually create a PV if dynamic provisioning is not working"},
			Prevention:      "Validate StorageClass before deployment; monitor cloud provider quotas; test PVC binding in staging",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "k8s-resource-quota", Category: "kubernetes", SubCategory: "namespace",
			Keywords: []string{"exceeded quota", "resource quota", "namespace quota exceeded"},
			Severity: "high",
			RootCause: "Namespace resource quota is exceeded — cannot create new pods or increase resource usage",
			Reasoning: []string{
				"The namespace has a ResourceQuota that limits total CPU, memory, or pod count",
				"New deployments or scaling operations are blocked when the quota is hit",
				"This is a governance mechanism — the quota may need adjustment for the workload",
			},
			Impact:          "Cannot deploy new pods; scaling operations fail; deployments stuck",
			ResolutionSteps: []string{"Check quota usage: kubectl describe resourcequota -n <namespace>", "Reduce resource requests on existing pods", "Request quota increase: kubectl edit resourcequota <name> -n <namespace>", "Delete unused pods/deployments to free quota", "Optimize resource requests to be more accurate (not over-provisioned)"},
			Prevention:      "Right-size resource requests; monitor quota utilization; set up alerts at 80% quota usage",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "k8s-readiness-probe-fail", Category: "kubernetes", SubCategory: "pod",
			Keywords: []string{"readiness probe failed", "not ready", "unhealthy: readiness"},
			Severity: "high",
			RootCause: "Readiness probe is failing — pod is removed from service endpoints and receives no traffic",
			Reasoning: []string{
				"The readiness probe endpoint is not responding with a success status",
				"Common causes: application not fully started, dependency unavailable, or health endpoint bug",
				"Unlike liveness probe failure, readiness failure does not restart the pod",
			},
			Impact:          "Pod receives no traffic; if all pods fail readiness, service has zero capacity",
			ResolutionSteps: []string{"Check probe details: kubectl describe pod <pod>", "Test the health endpoint: kubectl exec <pod> -- curl -v http://localhost:<port><path>", "Check application logs: kubectl logs <pod>", "Increase initialDelaySeconds if app starts slowly", "Check if a dependency (DB, Redis) is down, causing health check to fail"},
			Prevention:      "Set appropriate initialDelaySeconds; make health endpoints lightweight; do not check all dependencies in readiness probe",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "k8s-liveness-probe-fail", Category: "kubernetes", SubCategory: "pod",
			Keywords: []string{"liveness probe failed", "unhealthy: liveness", "restarting due to liveness"},
			Severity: "high",
			RootCause: "Liveness probe is failing — Kubernetes is restarting the pod repeatedly",
			Reasoning: []string{
				"Liveness probe failures cause Kubernetes to kill and restart the container",
				"If the underlying issue persists, this creates a restart loop similar to CrashLoopBackOff",
				"Common causes: application hang/deadlock, resource exhaustion, or aggressive probe settings",
			},
			Impact:          "Pod is repeatedly restarted; service availability is degraded; in-flight requests are dropped",
			ResolutionSteps: []string{"Check probe config: kubectl describe pod <pod> | grep -A5 Liveness", "Test liveness endpoint: kubectl exec <pod> -- curl -v http://localhost:<port><path>", "Increase timeoutSeconds and failureThreshold if the probe is too aggressive", "Check for application deadlocks or thread starvation", "Increase initialDelaySeconds for slow-starting applications"},
			Prevention:      "Use generous liveness probe settings; do not check dependencies in liveness probe; start with readiness probe only",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "k8s-hpa-max-replicas", Category: "kubernetes", SubCategory: "autoscaling",
			Keywords: []string{"hpa max replicas", "maxreplicas reached", "horizontal pod autoscaler maximum"},
			Severity: "high",
			RootCause: "HPA has scaled to maximum replicas but load is still increasing",
			Reasoning: []string{
				"The autoscaler has reached its configured maximum and cannot add more pods",
				"CPU/memory utilization remains above the target despite maximum replicas",
				"Either the maxReplicas is too low or the application cannot handle the current load",
			},
			Impact:          "Service is at capacity ceiling; response times increase; potential SLA violation",
			ResolutionSteps: []string{"Check HPA status: kubectl describe hpa <name>", "Increase maxReplicas: kubectl patch hpa <name> -p '{\"spec\":{\"maxReplicas\":20}}'", "Check if node capacity allows more pods: kubectl describe nodes | grep -A5 Allocatable", "Optimize application to handle more requests per pod", "Add more nodes to the cluster if scheduling capacity is the limit"},
			Prevention:      "Set maxReplicas with headroom above expected peak; monitor HPA scaling events; load test to validate capacity",
			BaseConfidence: 75, BaseRiskScore: 70,
		},
		{
			ID: "k8s-dns-failure", Category: "kubernetes", SubCategory: "networking",
			Keywords: []string{"dns resolution failed kubernetes", "coredns error", "nxdomain kubernetes"},
			Severity: "critical",
			RootCause: "Kubernetes cluster DNS (CoreDNS) is failing — service discovery is broken",
			Reasoning: []string{
				"CoreDNS is the central DNS service for all in-cluster service discovery",
				"If CoreDNS fails, pods cannot resolve service names like 'my-service.namespace.svc.cluster.local'",
				"All inter-service communication using DNS breaks simultaneously",
			},
			Impact:          "All service-to-service communication fails; cluster-wide outage",
			ResolutionSteps: []string{"Check CoreDNS pods: kubectl get pods -n kube-system -l k8s-app=kube-dns", "Check CoreDNS logs: kubectl logs -n kube-system -l k8s-app=kube-dns --tail=50", "Restart CoreDNS: kubectl rollout restart deployment coredns -n kube-system", "Test DNS from a pod: kubectl exec <pod> -- nslookup kubernetes.default", "Check CoreDNS config: kubectl get configmap coredns -n kube-system -o yaml"},
			Prevention:      "Monitor CoreDNS health and latency; run CoreDNS with at least 2 replicas; implement DNS caching in pods",
			BaseConfidence: 85, BaseRiskScore: 90,
		},
		{
			ID: "k8s-rbac-denied", Category: "kubernetes", SubCategory: "security",
			Keywords: []string{"forbidden", "rbac denied", "cannot get", "cannot list", "unauthorized kubernetes"},
			Severity: "high",
			RootCause: "RBAC permission denied — the service account lacks required permissions",
			Reasoning: []string{
				"The pod's service account does not have a ClusterRole/Role granting the required verb on the resource",
				"Common after changes to RBAC policies, namespace migration, or new API usage",
				"Kubernetes RBAC is deny-by-default — if no rule grants access, it is denied",
			},
			Impact:          "The specific Kubernetes API operation fails; application cannot manage resources",
			ResolutionSteps: []string{"Check which permission is needed from the error message", "Check service account: kubectl get pod <pod> -o jsonpath='{.spec.serviceAccountName}'", "Check roles: kubectl get rolebinding,clusterrolebinding --all-namespaces -o wide | grep <sa_name>", "Create a role: kubectl create role <name> --verb=get,list --resource=configmaps -n <ns>", "Bind it: kubectl create rolebinding <name> --role=<role> --serviceaccount=<ns>:<sa>"},
			Prevention:      "Define RBAC policies in version-controlled YAML; test permissions in staging; use least-privilege principle",
			BaseConfidence: 75, BaseRiskScore: 55,
		},
		{
			ID: "k8s-secret-not-found", Category: "kubernetes", SubCategory: "config",
			Keywords: []string{"secret not found", "secret does not exist", "failed to get secret"},
			Severity: "critical",
			RootCause: "Required Kubernetes Secret is missing — pod cannot mount or reference the secret",
			Reasoning: []string{
				"The pod spec references a Secret that does not exist in the namespace",
				"This prevents the pod from starting entirely (CreateContainerConfigError)",
				"May happen when deploying to a new namespace without creating prerequisites",
			},
			Impact:          "Pod cannot start; service is down until the secret is created",
			ResolutionSteps: []string{"Check events: kubectl describe pod <pod>", "List secrets: kubectl get secrets -n <namespace>", "Create the secret: kubectl create secret generic <name> --from-literal=<key>=<value>", "Or from file: kubectl create secret generic <name> --from-file=<path>", "Verify the secret name matches what the pod spec references"},
			Prevention:      "Include secrets in deployment pipeline; use sealed-secrets or external-secrets-operator; validate before deploy",
			BaseConfidence: 80, BaseRiskScore: 70,
		},
		{
			ID: "k8s-configmap-not-found", Category: "kubernetes", SubCategory: "config",
			Keywords: []string{"configmap not found", "configmap does not exist", "failed to get configmap"},
			Severity: "high",
			RootCause: "Required ConfigMap is missing — pod cannot mount or reference the config",
			Reasoning: []string{
				"The pod spec references a ConfigMap that does not exist in the namespace",
				"This prevents the pod from starting or injecting the expected environment variables",
				"Common when deploying to a new namespace or after config cleanup",
			},
			Impact:          "Pod cannot start or runs with missing configuration; application may behave incorrectly",
			ResolutionSteps: []string{"Check events: kubectl describe pod <pod>", "List configmaps: kubectl get configmaps -n <namespace>", "Create the ConfigMap: kubectl create configmap <name> --from-literal=<key>=<value>", "Or from file: kubectl create configmap <name> --from-file=<path>", "Make the ConfigMap optional if appropriate: optional: true in the volume source"},
			Prevention:      "Include ConfigMaps in deployment pipeline; validate prerequisites before pod creation",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "k8s-network-policy-blocking", Category: "kubernetes", SubCategory: "networking",
			Keywords: []string{"network policy blocking", "networkpolicy", "traffic dropped kubernetes"},
			Severity: "high",
			RootCause: "Kubernetes NetworkPolicy is blocking expected traffic between pods or namespaces",
			Reasoning: []string{
				"A NetworkPolicy with ingress/egress rules is preventing required communication",
				"When a NetworkPolicy is applied to a pod, all traffic not explicitly allowed is blocked",
				"Common after security hardening or namespace isolation changes",
			},
			Impact:          "Service-to-service communication fails; specific pods cannot reach dependencies",
			ResolutionSteps: []string{"Check network policies: kubectl get networkpolicy -n <namespace>", "Describe the policy: kubectl describe networkpolicy <name> -n <namespace>", "Test connectivity: kubectl exec <pod> -- nc -zv <target-service> <port>", "Add an allow rule for the required traffic", "Temporarily delete the policy to verify it is the cause: kubectl delete networkpolicy <name>"},
			Prevention:      "Test NetworkPolicies in staging; use network policy visualization tools; document required traffic flows",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "k8s-ingress-error", Category: "kubernetes", SubCategory: "networking",
			Keywords: []string{"ingress error", "nginx ingress error", "502 bad gateway ingress", "ingress controller error"},
			Severity: "high",
			RootCause: "Kubernetes Ingress controller is returning errors — backend service is unreachable",
			Reasoning: []string{
				"The Ingress controller cannot forward traffic to the backend service/pods",
				"Common causes: backend pods not ready, wrong service port, or no endpoints",
				"502 from ingress specifically means the backend returned an invalid response",
			},
			Impact:          "External traffic cannot reach the service; users see 502/503 errors",
			ResolutionSteps: []string{"Check ingress controller logs: kubectl logs -n <ingress-ns> -l app.kubernetes.io/name=ingress-nginx --tail=50", "Check backend endpoints: kubectl get endpoints <service-name>", "Verify service port matches pod port: kubectl describe svc <service-name>", "Check pod readiness: kubectl get pods -l <selector>", "Verify ingress spec: kubectl describe ingress <name>"},
			Prevention:      "Use readiness probes; monitor endpoint count; validate ingress config in CI",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "k8s-pod-eviction", Category: "kubernetes", SubCategory: "pod",
			Keywords: []string{"pod evicted", "eviction kubernetes", "low disk space kubernetes"},
			Severity: "high",
			RootCause: "Pod was evicted due to node resource pressure (disk, memory, or PID)",
			Reasoning: []string{
				"The kubelet evicts pods when the node is under resource pressure",
				"Pods without resource limits or with BestEffort QoS are evicted first",
				"Evicted pods are rescheduled on other nodes if capacity allows",
			},
			Impact:          "Service disruption during rescheduling; data loss if using emptyDir volumes",
			ResolutionSteps: []string{"Check eviction reason: kubectl describe pod <pod> | grep -A3 Status", "Check node conditions: kubectl describe node <node> | grep -A5 Conditions", "If disk pressure: clean up on the node (docker prune, log cleanup)", "If memory pressure: add memory or reduce workload on the node", "Set resource requests and limits to get Guaranteed QoS class"},
			Prevention:      "Set resource requests and limits; monitor node resource usage; use PodDisruptionBudgets",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "k8s-webhook-denied", Category: "kubernetes", SubCategory: "config",
			Keywords: []string{"admission webhook", "webhook denied", "validating webhook", "mutating webhook denied"},
			Severity: "high",
			RootCause: "Admission webhook is blocking resource creation or modification",
			Reasoning: []string{
				"A ValidatingWebhookConfiguration or MutatingWebhookConfiguration is rejecting the request",
				"The webhook enforces a policy (security, naming, resource limits) that the resource violates",
				"If the webhook server is down, requests may also be blocked (failurePolicy: Fail)",
			},
			Impact:          "Cannot create or update Kubernetes resources; deployments are blocked",
			ResolutionSteps: []string{"Check error message for which webhook and why it denied", "Check webhook configurations: kubectl get validatingwebhookconfigurations,mutatingwebhookconfigurations", "Check webhook server health: kubectl get pods in the webhook namespace", "Fix the resource to comply with webhook policy", "If webhook server is down: set failurePolicy to Ignore temporarily"},
			Prevention:      "Test resources against webhook policies in CI; monitor webhook server health; set failurePolicy wisely",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "k8s-etcd-error", Category: "kubernetes", SubCategory: "control-plane",
			Keywords: []string{"etcd error", "etcd cluster", "etcdserver", "etcd unavailable"},
			Severity: "critical",
			RootCause: "etcd cluster error — Kubernetes control plane data store is degraded or unavailable",
			Reasoning: []string{
				"etcd stores all Kubernetes cluster state — without it, the API server cannot function",
				"etcd requires a quorum (majority of nodes); losing quorum halts all write operations",
				"Common causes: disk full on etcd volume, slow disk I/O, or network partition between etcd members",
			},
			Impact:          "All Kubernetes API operations may fail; cannot create, update, or delete any resources; existing workloads continue running",
			ResolutionSteps: []string{"Check etcd pod health: kubectl get pods -n kube-system -l component=etcd", "Check etcd member status: kubectl exec -n kube-system etcd-<node> -- etcdctl member list", "Check etcd disk latency: kubectl exec -n kube-system etcd-<node> -- etcdctl endpoint status", "Free disk space on etcd data volume if full", "If quorum lost: follow etcd disaster recovery documentation"},
			Prevention:      "Use SSD/NVMe for etcd storage; monitor etcd disk latency; run 3 or 5 etcd members; regular etcd backups",
			BaseConfidence: 90, BaseRiskScore: 95,
		},
		{
			ID: "k8s-api-server-unavailable", Category: "kubernetes", SubCategory: "control-plane",
			Keywords: []string{"unable to connect to server", "api server unreachable", "kube-apiserver unavailable"},
			Severity: "critical",
			RootCause: "Kubernetes API server is unreachable — cluster management operations are impossible",
			Reasoning: []string{
				"The API server is the gateway for all cluster operations (kubectl, controllers, kubelets)",
				"If the API server is down, no new pods can be scheduled and no changes can be made",
				"Existing running pods continue to function but cannot be managed",
			},
			Impact:          "All kubectl commands fail; controllers cannot reconcile; auto-scaling and self-healing stop",
			ResolutionSteps: []string{"Check if API server pod is running (access control plane node directly)", "Check API server logs on the control plane node: journalctl -u kube-apiserver or docker logs", "Verify etcd is healthy (API server depends on etcd)", "Check API server certificates: they may have expired", "Restart API server: systemctl restart kube-apiserver (or re-create the static pod)"},
			Prevention:      "Run HA control plane (3+ masters); monitor API server health externally; automate certificate renewal",
			BaseConfidence: 90, BaseRiskScore: 95,
		},
		{
			ID: "k8s-init-container-fail", Category: "kubernetes", SubCategory: "pod",
			Keywords: []string{"init container failed", "init:error", "init container error"},
			Severity: "high",
			RootCause: "Init container failed, preventing the main container from starting",
			Reasoning: []string{
				"Init containers run before main containers and must complete successfully",
				"Common uses: database migration, config download, or dependency waiting",
				"If the init container fails, the main application never starts",
			},
			Impact:          "Pod cannot start; service remains unavailable until init container succeeds",
			ResolutionSteps: []string{"Check init container logs: kubectl logs <pod> -c <init-container-name>", "Check init container status: kubectl describe pod <pod>", "Verify what the init container does and fix its failure", "If waiting for a dependency: check if the dependency is available", "Increase init container timeout or add retry logic"},
			Prevention:      "Test init containers independently; make them idempotent; add timeout and retry logic",
			BaseConfidence: 75, BaseRiskScore: 60,
		},
		{
			ID: "k8s-volume-mount-fail", Category: "kubernetes", SubCategory: "storage",
			Keywords: []string{"volume mount error", "failed to mount volume", "volumemount error"},
			Severity: "high",
			RootCause: "Pod cannot mount a volume — the volume path, permissions, or driver is failing",
			Reasoning: []string{
				"Volume mount failures prevent the pod from starting if the volume is required",
				"Common causes: PVC not bound, CSI driver error, NFS server unreachable, or wrong subpath",
				"Permissions on the mounted path may not match the pod's security context",
			},
			Impact:          "Pod cannot start; service is unavailable; data access is blocked",
			ResolutionSteps: []string{"Check pod events: kubectl describe pod <pod>", "Check PVC status: kubectl get pvc", "Check CSI driver pods: kubectl get pods -n kube-system | grep csi", "Verify NFS/storage backend is accessible from the node", "Check fsGroup and runAsUser in securityContext for permission issues"},
			Prevention:      "Test volume mounts in staging; validate PVCs before deployment; monitor storage backend health",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "k8s-cronjob-missed", Category: "kubernetes", SubCategory: "workload",
			Keywords: []string{"cronjob missed", "startingdeadlineseconds", "cronjob failed to schedule"},
			Severity: "medium",
			RootCause: "Kubernetes CronJob missed its scheduled execution window",
			Reasoning: []string{
				"If the CronJob controller cannot schedule the job within startingDeadlineSeconds, it is missed",
				"Common causes: controller overloaded, node scheduling pressure, or too short deadline",
				"Missed jobs are not retried unless concurrencyPolicy allows it",
			},
			Impact:          "Scheduled task did not run; data may not be processed; reports may be delayed",
			ResolutionSteps: []string{"Check CronJob events: kubectl describe cronjob <name>", "Increase startingDeadlineSeconds: 200 (default is 100)", "Check controller manager health: kubectl get pods -n kube-system | grep controller-manager", "Manually trigger: kubectl create job --from=cronjob/<name> manual-<timestamp>", "Check if node scheduling capacity is available"},
			Prevention:      "Set startingDeadlineSeconds generously; monitor CronJob execution; alert on missed schedules",
			BaseConfidence: 65, BaseRiskScore: 45,
		},
		{
			ID: "k8s-cert-expired", Category: "kubernetes", SubCategory: "security",
			Keywords: []string{"certificate expired kubernetes", "tls certificate expired k8s", "x509: certificate has expired"},
			Severity: "critical",
			RootCause: "TLS certificate in Kubernetes has expired — secure communication is broken",
			Reasoning: []string{
				"Kubernetes uses TLS certificates for API server, kubelet, and inter-component communication",
				"Expired certificates cause all authenticated communication to fail",
				"cert-manager managed certificates should auto-renew but can fail silently",
			},
			Impact:          "Cluster components cannot communicate; kubectl fails; nodes disconnect from control plane",
			ResolutionSteps: []string{"Check certificate expiry: kubeadm certs check-expiration", "Renew certificates: kubeadm certs renew all", "For cert-manager: kubectl describe certificate <name> to check status", "Restart affected components after renewal: systemctl restart kubelet", "For managed Kubernetes: contact cloud provider if control plane certs expired"},
			Prevention:      "Monitor certificate expiry 30 days in advance; use cert-manager with auto-renewal; set up expiry alerts",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "k8s-cni-error", Category: "kubernetes", SubCategory: "networking",
			Keywords: []string{"cni error", "network plugin", "failed to set up pod network", "calico error", "flannel error", "cilium error"},
			Severity: "critical",
			RootCause: "Container Network Interface (CNI) plugin error — pod networking is broken",
			Reasoning: []string{
				"The CNI plugin is responsible for assigning IP addresses and setting up network for pods",
				"If CNI fails, new pods cannot get network connectivity",
				"Common causes: CNI pod crashed, IP address exhaustion, or configuration error",
			},
			Impact:          "New pods cannot get network; existing pods may lose connectivity; cluster networking degraded",
			ResolutionSteps: []string{"Check CNI pods: kubectl get pods -n kube-system | grep -E 'calico|flannel|cilium|weave'", "Check CNI pod logs: kubectl logs -n kube-system <cni-pod>", "Check if IP pool is exhausted: for Calico: calicoctl ipam show", "Restart CNI pods: kubectl delete pods -n kube-system -l k8s-app=<cni-app>", "Check node network configuration: ip addr show on affected nodes"},
			Prevention:      "Monitor CNI pod health; size IP pools for growth; keep CNI plugin updated; run redundant CNI pods",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "k8s-service-no-endpoints", Category: "kubernetes", SubCategory: "networking",
			Keywords: []string{"no endpoints", "endpoints not ready", "service unavailable kubernetes"},
			Severity: "critical",
			RootCause: "Kubernetes Service has no ready endpoints — no pods are serving traffic",
			Reasoning: []string{
				"No pods match the service selector, or all matching pods have failed readiness probes",
				"Traffic sent to the service gets connection refused or timeout",
				"This effectively means the service is down even though the Service object exists",
			},
			Impact:          "All traffic to the service fails; dependent services experience connection errors",
			ResolutionSteps: []string{"Check endpoints: kubectl get endpoints <service-name>", "Check if pods match the selector: kubectl get pods -l <selector-from-service>", "Check pod readiness: kubectl get pods -l <selector> -o wide", "Check readiness probe results: kubectl describe pod <pod>", "Fix readiness probe or the underlying issue causing pods to be not ready"},
			Prevention:      "Monitor endpoint count per service; set up alerts when endpoints drop to zero; use PodDisruptionBudgets",
			BaseConfidence: 80, BaseRiskScore: 80,
		},
		{
			ID: "k8s-deployment-stuck", Category: "kubernetes", SubCategory: "workload",
			Keywords: []string{"deployment stuck", "rollout stuck", "deployment not progressing"},
			Severity: "high",
			RootCause: "Kubernetes Deployment rollout is stuck and not making progress",
			Reasoning: []string{
				"New pods from the Deployment cannot reach Ready state",
				"Common causes: image pull errors, readiness probe failures, or resource exhaustion",
				"Old ReplicaSet pods continue serving while new ones fail to start",
			},
			Impact:          "New version is not deployed; old version continues running; rollback may be needed",
			ResolutionSteps: []string{"Check rollout status: kubectl rollout status deployment/<name>", "Check new ReplicaSet pods: kubectl get pods -l app=<name> --sort-by=.metadata.creationTimestamp", "Describe failing pods: kubectl describe pod <new-pod>", "Roll back if needed: kubectl rollout undo deployment/<name>", "Fix the issue (image, config, resources) and redeploy"},
			Prevention:      "Use canary deployments; set progressDeadlineSeconds; validate images before deploy; use CI/CD pipelines",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "k8s-statefulset-stuck", Category: "kubernetes", SubCategory: "workload",
			Keywords: []string{"statefulset stuck", "statefulset not ready", "statefulset rollout"},
			Severity: "high",
			RootCause: "StatefulSet rollout is stuck — pods are not reaching Ready state in order",
			Reasoning: []string{
				"StatefulSets update pods one at a time in order; if one pod fails, the rollout stops",
				"PVC binding issues are common because each pod needs its own PVC",
				"The pod may be waiting for a volume or failing its readiness check",
			},
			Impact:          "StatefulSet update stalled; older pods continue running; data services may be partially updated",
			ResolutionSteps: []string{"Check StatefulSet status: kubectl describe statefulset <name>", "Check stuck pod: kubectl describe pod <name>-<ordinal>", "Check PVC: kubectl get pvc | grep <statefulset-name>", "Delete the stuck pod to retry: kubectl delete pod <name>-<ordinal>", "Roll back: kubectl rollout undo statefulset/<name>"},
			Prevention:      "Test StatefulSet updates in staging; use partition-based rolling updates; validate PVCs before rollout",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "k8s-daemonset-not-scheduled", Category: "kubernetes", SubCategory: "workload",
			Keywords: []string{"daemonset not scheduled", "daemonset pod failed", "daemonset error"},
			Severity: "high",
			RootCause: "DaemonSet pods are not being scheduled on all expected nodes",
			Reasoning: []string{
				"DaemonSet pods must run on every node (or selected nodes via nodeSelector/tolerations)",
				"Missing tolerations cause pods to not schedule on tainted nodes",
				"Resource constraints (insufficient CPU/memory) can prevent scheduling",
			},
			Impact:          "Infrastructure agent or logging daemon not running on some nodes; monitoring blind spots",
			ResolutionSteps: []string{"Check DaemonSet status: kubectl describe daemonset <name>", "Check which nodes are missing pods: kubectl get pods -l <selector> -o wide", "Check node taints: kubectl describe node <node> | grep Taint", "Add required tolerations to the DaemonSet spec", "Check resource requests: reduce if nodes cannot accommodate"},
			Prevention:      "Add tolerations for all expected taints; set low resource requests for infrastructure DaemonSets; monitor pod count",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "k8s-job-failed", Category: "kubernetes", SubCategory: "workload",
			Keywords: []string{"job failed", "backofflimitexceeded", "job pod failed"},
			Severity: "high",
			RootCause: "Kubernetes Job exceeded its backoff limit — the job has permanently failed",
			Reasoning: []string{
				"The Job's pods failed on every retry attempt up to the backoffLimit",
				"Common causes: wrong command, missing config, or dependent service unavailable",
				"The Job will not be retried automatically after exceeding the limit",
			},
			Impact:          "Batch processing did not complete; data may not be processed; dependent workflows blocked",
			ResolutionSteps: []string{"Check job status: kubectl describe job <name>", "Check failed pod logs: kubectl logs job/<name>", "Fix the underlying issue (config, dependencies)", "Delete the failed job and create a new one", "Increase backoffLimit if failures are transient: spec.backoffLimit: 6"},
			Prevention:      "Test jobs in staging; increase backoffLimit for flaky operations; implement dead-letter handling",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "k8s-kubelet-error", Category: "kubernetes", SubCategory: "node",
			Keywords: []string{"kubelet error", "kubelet exited", "failed to run kubelet"},
			Severity: "critical",
			RootCause: "Kubelet process on the node has crashed or is not running",
			Reasoning: []string{
				"Without kubelet, the node cannot manage pods or report health to the API server",
				"The node will be marked NotReady after the node-monitor-grace-period (40s default)",
				"Pods on this node may be evicted and rescheduled elsewhere",
			},
			Impact:          "Node becomes NotReady; all pods on the node are at risk; scheduling capacity reduced",
			ResolutionSteps: []string{"SSH to the node and check kubelet: systemctl status kubelet", "Check kubelet logs: journalctl -u kubelet --since '10 min ago'", "Restart kubelet: systemctl restart kubelet", "Check disk space on the node: df -h", "Check if certificates expired: kubelet certificate check"},
			Prevention:      "Monitor kubelet health on all nodes; use node auto-repair in managed Kubernetes; keep kubelet updated",
			BaseConfidence: 85, BaseRiskScore: 85,
		},
		{
			ID: "k8s-affinity-conflict", Category: "kubernetes", SubCategory: "scheduling",
			Keywords: []string{"pod affinity", "anti-affinity", "no nodes match", "affinity conflict"},
			Severity: "high",
			RootCause: "Pod cannot be scheduled because no nodes satisfy its affinity/anti-affinity rules",
			Reasoning: []string{
				"The pod specifies nodeAffinity, podAffinity, or podAntiAffinity rules that no node can satisfy",
				"Anti-affinity rules may prevent co-location with existing pods",
				"Node labels may have changed, invalidating the affinity rules",
			},
			Impact:          "Pod remains Pending indefinitely; service capacity reduced",
			ResolutionSteps: []string{"Check pod events: kubectl describe pod <pod> | grep -A5 Events", "Check node labels: kubectl get nodes --show-labels", "Relax affinity rules: change requiredDuringScheduling to preferredDuringScheduling", "Add required labels to nodes: kubectl label node <node> <key>=<value>", "Add more nodes with the required labels"},
			Prevention:      "Use preferredDuringScheduling when possible; validate node labels; test scheduling in staging",
			BaseConfidence: 70, BaseRiskScore: 55,
		},
		{
			ID: "k8s-hpa-thrashing", Category: "kubernetes", SubCategory: "autoscaling",
			Keywords: []string{"hpa thrashing", "hpa scaling", "hpa flapping", "autoscaler oscillating"},
			Severity: "medium",
			RootCause: "HPA is oscillating between scaling up and scaling down (thrashing)",
			Reasoning: []string{
				"Rapid scale-up followed by scale-down indicates the metric is bouncing around the target",
				"New pods need time to warm up and take load, causing the metric to temporarily drop",
				"The stabilization window may be too short for the workload characteristics",
			},
			Impact:          "Constant pod churn; wasted resources during scale-up; potential brief degradation during scale-down",
			ResolutionSteps: []string{"Check HPA events: kubectl describe hpa <name>", "Increase stabilization window: behavior.scaleDown.stabilizationWindowSeconds: 300", "Increase scaleDown policies to be less aggressive", "Adjust target CPU/memory percentage (try 70% instead of 50%)", "Use custom metrics that are less volatile"},
			Prevention:      "Set stabilization windows; use moderate target values; tune HPA behavior policies; test with load simulation",
			BaseConfidence: 65, BaseRiskScore: 40,
		},
		{
			ID: "k8s-scheduler-failure", Category: "kubernetes", SubCategory: "control-plane",
			Keywords: []string{"scheduler failure", "scheduler error", "kube-scheduler"},
			Severity: "critical",
			RootCause: "Kubernetes scheduler is failing — new pods cannot be assigned to nodes",
			Reasoning: []string{
				"Without the scheduler, Pending pods stay Pending forever",
				"Existing running pods are not affected but new deployments cannot proceed",
				"The scheduler may have crashed or lost leadership in HA setup",
			},
			Impact:          "No new pods can be scheduled; scaling and deployments are blocked",
			ResolutionSteps: []string{"Check scheduler pods: kubectl get pods -n kube-system -l component=kube-scheduler", "Check scheduler logs: kubectl logs -n kube-system <scheduler-pod>", "Restart scheduler: delete the pod if running as static pod", "Check if leader election is working in HA setup", "Manually assign pods if urgent: spec.nodeName in pod spec (temporary workaround)"},
			Prevention:      "Run HA scheduler (multiple replicas); monitor scheduler health; set up alerts on unschedulable pods",
			BaseConfidence: 85, BaseRiskScore: 90,
		},
		{
			ID: "k8s-vpa-oom", Category: "kubernetes", SubCategory: "autoscaling",
			Keywords: []string{"vertical pod autoscaler", "vpa oom", "vpa recommendation"},
			Severity: "high",
			RootCause: "VPA is unable to prevent OOM kills — recommendations may be lagging behind actual usage",
			Reasoning: []string{
				"VPA adjusts resource requests based on historical usage, which may lag behind sudden spikes",
				"In UpdateMode, VPA restarts pods to apply new limits, causing brief disruption",
				"If memory spikes faster than VPA can react, OOM kills still occur",
			},
			Impact:          "Pods are OOM-killed despite VPA; brief service disruption during VPA-triggered restarts",
			ResolutionSteps: []string{"Check VPA recommendations: kubectl describe vpa <name>", "Set a minimum resource bound: minAllowed in VPA spec", "Switch to Off mode and apply recommendations manually", "Increase memory limits manually as immediate fix", "Check if the application has a memory leak (VPA cannot fix leaks)"},
			Prevention:      "Set VPA minAllowed to prevent under-provisioning; combine VPA with HPA carefully; fix memory leaks",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "k8s-istio-sidecar-crash", Category: "kubernetes", SubCategory: "service-mesh",
			Keywords: []string{"istio sidecar", "envoy crash", "sidecar crash", "istio-proxy error"},
			Severity: "high",
			RootCause: "Istio/Envoy sidecar proxy is crashing, disrupting service mesh traffic",
			Reasoning: []string{
				"The Envoy sidecar handles all network traffic for the pod in a service mesh",
				"If the sidecar crashes, the pod may lose network connectivity entirely",
				"Common causes: invalid Istio configuration, resource limits too low, or Envoy bug",
			},
			Impact:          "Pod loses mesh connectivity; requests to/from the pod fail; mTLS breaks",
			ResolutionSteps: []string{"Check sidecar logs: kubectl logs <pod> -c istio-proxy", "Check Istio configuration: istioctl analyze -n <namespace>", "Increase sidecar resources: add proxy resource annotations to the pod", "Check for invalid VirtualService or DestinationRule resources", "Restart the pod: kubectl delete pod <pod>"},
			Prevention:      "Validate Istio config with istioctl analyze; set appropriate sidecar resource limits; monitor sidecar health",
			BaseConfidence: 70, BaseRiskScore: 60,
		},
		{
			ID: "k8s-kube-proxy-error", Category: "kubernetes", SubCategory: "networking",
			Keywords: []string{"kube-proxy error", "kube-proxy iptables", "service routing error"},
			Severity: "high",
			RootCause: "kube-proxy is failing to maintain service routing rules on the node",
			Reasoning: []string{
				"kube-proxy programs iptables/ipvs rules to route Service traffic to pods",
				"If kube-proxy fails, new Services or endpoint changes are not reflected in routing",
				"Existing rules continue to work but stale rules may route to dead pods",
			},
			Impact:          "Service discovery may route to wrong or dead pods; intermittent connectivity failures",
			ResolutionSteps: []string{"Check kube-proxy pods: kubectl get pods -n kube-system -l k8s-app=kube-proxy", "Check kube-proxy logs: kubectl logs -n kube-system <kube-proxy-pod>", "Restart kube-proxy: kubectl delete pod -n kube-system <kube-proxy-pod>", "Check iptables rules: iptables -t nat -L KUBE-SERVICES (on the node)", "Verify kube-proxy mode (iptables vs ipvs): kubectl get configmap kube-proxy -n kube-system -o yaml"},
			Prevention:      "Monitor kube-proxy health; keep Kubernetes updated; consider ipvs mode for large clusters",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "k8s-csi-driver-failure", Category: "kubernetes", SubCategory: "storage",
			Keywords: []string{"csi driver failure", "csi error", "csi volume", "csi plugin"},
			Severity: "high",
			RootCause: "CSI (Container Storage Interface) driver is failing — volumes cannot be attached or mounted",
			Reasoning: []string{
				"The CSI driver is responsible for provisioning, attaching, and mounting storage volumes",
				"If the CSI driver pods are unhealthy, PVCs cannot be bound and pods cannot start",
				"Common causes: driver pod crash, storage backend unreachable, or permission issues",
			},
			Impact:          "New volumes cannot be created or attached; pods waiting for volumes remain Pending",
			ResolutionSteps: []string{"Check CSI driver pods: kubectl get pods -n kube-system | grep csi", "Check CSI driver logs: kubectl logs -n kube-system <csi-pod>", "Check VolumeAttachment objects: kubectl get volumeattachments", "Verify storage backend connectivity and credentials", "Restart CSI driver pods: kubectl delete pods -n kube-system -l app=<csi-driver>"},
			Prevention:      "Monitor CSI driver health; keep drivers updated; maintain storage backend connectivity; test volume operations regularly",
			BaseConfidence: 75, BaseRiskScore: 65,
		},
		{
			ID: "k8s-pod-disruption-budget", Category: "kubernetes", SubCategory: "workload",
			Keywords: []string{"pod disruption budget", "pdb violated", "cannot evict", "disruption budget"},
			Severity: "medium",
			RootCause: "PodDisruptionBudget is preventing node drain or voluntary pod eviction",
			Reasoning: []string{
				"PDB ensures a minimum number of pods remain available during voluntary disruptions",
				"Node drain, rolling updates, or cluster upgrades are blocked by strict PDBs",
				"This is working as intended — PDB is protecting service availability",
			},
			Impact:          "Node maintenance or cluster upgrades are blocked; drain operations hang",
			ResolutionSteps: []string{"Check PDB status: kubectl get pdb -n <namespace>", "Check which PDB is blocking: kubectl describe pdb <name>", "Scale up the deployment to meet PDB requirements before draining", "Temporarily adjust PDB if safe: kubectl edit pdb <name>", "Use --disable-eviction flag with kubectl drain (forces eviction, use cautiously)"},
			Prevention:      "Set PDB minAvailable to n-1 (not n); ensure enough replicas before maintenance; test drain procedures",
			BaseConfidence: 65, BaseRiskScore: 40,
		},
		{
			ID: "k8s-topology-spread", Category: "kubernetes", SubCategory: "scheduling",
			Keywords: []string{"topology spread", "topologykey", "spread constraint"},
			Severity: "medium",
			RootCause: "Pod topology spread constraint cannot be satisfied — not enough topology domains",
			Reasoning: []string{
				"The pod requires spreading across zones or nodes, but not enough domains are available",
				"Common when cluster has fewer zones/nodes than the maxSkew allows",
				"The constraint prevents uneven distribution which could cause outage if a zone fails",
			},
			Impact:          "Pod remains Pending; deployment cannot reach desired replica count",
			ResolutionSteps: []string{"Check constraint: kubectl describe pod <pod> | grep -A5 TopologySpreadConstraint", "Check available topology domains: kubectl get nodes -L topology.kubernetes.io/zone", "Relax the constraint: increase maxSkew or change whenUnsatisfiable to ScheduleAnyway", "Add nodes in additional topology domains", "Remove the constraint temporarily if not critical"},
			Prevention:      "Use whenUnsatisfiable: ScheduleAnyway for non-critical workloads; ensure cluster spans enough zones",
			BaseConfidence: 65, BaseRiskScore: 40,
		},
	}
}
