package services

func buildCPUEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "cpu-high-85", Category: "system_metric", SubCategory: "cpu",
			Keywords:   []string{"cpu", "high cpu", "cpu usage", "cpu used"},
			AntiWords:  []string{"steal", "iowait", "nice"},
			MetricName: "system.cpu.used.percent", Severity: "high",
			RootCause: "CPU utilization has exceeded 85%, indicating the host is under heavy compute load",
			Reasoning: []string{
				"CPU usage above 85% leaves insufficient headroom for traffic spikes or background tasks",
				"Sustained high CPU causes increased request latency and can trigger upstream timeouts",
				"Common triggers include traffic surges, inefficient code paths, or runaway processes",
			},
			Impact:          "Service response times degrade; upstream callers may time out; user-facing latency increases",
			ResolutionSteps: []string{"Identify top CPU consumers: top -o %CPU -b -n 1 | head -20", "Check for recently deployed services: systemctl list-units --type=service --state=running", "Profile the hot process: perf top -p <PID> (Linux) or use async-profiler for Java", "Scale horizontally if load is legitimate: add more replicas behind the load balancer", "Check for cron jobs or batch processes that should be scheduled off-peak"},
			Prevention:      "Set up CPU usage alerts at 75% warning and 85% critical thresholds; implement auto-scaling policies",
			BaseConfidence:  75, BaseRiskScore: 65,
		},
		{
			ID: "cpu-critical-95", Category: "system_metric", SubCategory: "cpu",
			Keywords:   []string{"cpu 95", "cpu 96", "cpu 97", "cpu 98", "cpu 99", "cpu 100", "critical cpu"},
			MetricName: "system.cpu.used.percent", Severity: "critical",
			RootCause: "CPU utilization has reached critical levels above 95%, host is nearly saturated",
			Reasoning: []string{
				"At 95%+ CPU the OS scheduler cannot allocate cycles for new work",
				"Context switching overhead increases dramatically at saturation",
				"Processes start queueing, load average climbs, and cascading failures begin",
			},
			Impact:          "Services become unresponsive; health checks fail; cascading failures to dependent services",
			ResolutionSteps: []string{"Immediately identify the runaway process: ps aux --sort=-%cpu | head -10", "Kill runaway process if safe: kill -9 <PID>", "Check if a crypto miner or fork bomb is present: pstree -p | head -50", "Restart the offending service after taking a thread dump: kill -3 <PID> (Java)", "Add emergency compute capacity or redirect traffic to healthy nodes"},
			Prevention:      "Implement resource limits (cgroups/containers); deploy CPU-based auto-scaling with a 75% target",
			BaseConfidence:  85, BaseRiskScore: 90,
		},
		{
			ID: "cpu-spike-sudden", Category: "system_metric", SubCategory: "cpu",
			Keywords:  []string{"cpu spike", "sudden cpu", "cpu jump", "cpu surge"},
			Severity:  "high",
			RootCause: "Sudden CPU spike detected, likely caused by a new deployment, batch job, or runaway process",
			Reasoning: []string{
				"A sudden jump in CPU (more than 30% increase within minutes) indicates a new workload arrived",
				"Common causes: bad deployment with infinite loop, crypto miner, fork bomb, or burst of traffic",
				"Correlate the spike timing with recent deploys or cron job schedules",
			},
			Impact:          "Latency spikes for all services on the host; potential cascading timeouts",
			ResolutionSteps: []string{"Correlate spike time with deploys: git log --since='1 hour ago' --oneline", "Find the new process consuming CPU: ps aux --sort=-%cpu | head -5", "Check for fork bomb: ps aux | wc -l (abnormally high count = fork bomb)", "Roll back recent deployment if it aligns with spike onset", "Apply CPU cgroup limits to contain the process: systemctl set-property <service> CPUQuota=50%"},
			Prevention:      "Use canary deployments; set CPU resource limits in container specs; monitor process count",
			BaseConfidence:  70, BaseRiskScore: 70,
		},
		{
			ID: "cpu-single-core-100", Category: "system_metric", SubCategory: "cpu",
			Keywords:  []string{"single core", "one core", "single thread", "single cpu 100"},
			Severity:  "medium",
			RootCause: "One CPU core pinned at 100% while others are idle, indicating a single-threaded bottleneck",
			Reasoning: []string{
				"A single core at 100% with others idle indicates the workload cannot parallelize",
				"Common in single-threaded runtimes (Node.js event loop, Python GIL, Ruby MRI)",
				"The overall CPU average may look normal but the service is fully saturated on its thread",
			},
			Impact:          "The single-threaded service hits throughput ceiling; requests queue behind the bottleneck",
			ResolutionSteps: []string{"Identify the pinned process: mpstat -P ALL 1 5 (find core at 100%)", "Check if Node.js: consider using cluster module or worker_threads", "For Python: use multiprocessing instead of threading; consider gunicorn workers", "Profile the hot code path: perf record -p <PID> -g -- sleep 10 && perf report", "Scale out to multiple process instances behind a load balancer"},
			Prevention:      "Use multi-process architectures for CPU-bound workloads; monitor per-core utilization",
			BaseConfidence:  70, BaseRiskScore: 55,
		},
		{
			ID: "cpu-steal-high", Category: "system_metric", SubCategory: "cpu",
			Keywords:  []string{"cpu steal", "steal time", "noisy neighbor", "steal percent"},
			Severity:  "high",
			RootCause: "High CPU steal time indicates the hypervisor is taking cycles away from this VM (noisy neighbor)",
			Reasoning: []string{
				"CPU steal > 10% means the physical host is overcommitted and your VM is being throttled",
				"This is outside your control — the hypervisor prioritizes other VMs on the same host",
				"Performance degradation is real but no amount of application tuning will fix it",
			},
			Impact:          "Unpredictable latency spikes; CPU-bound operations take longer; SLA violations",
			ResolutionSteps: []string{"Confirm steal time: vmstat 1 5 (check 'st' column)", "Contact cloud provider to migrate VM to a less loaded host", "For AWS: stop and start the instance (NOT reboot) to move to new hardware", "Consider dedicated/reserved instances to avoid noisy neighbor issues", "Monitor steal time trend: sar -u 1 10"},
			Prevention:      "Use dedicated instances for production workloads; monitor steal time with alerts at 5%",
			BaseConfidence:  80, BaseRiskScore: 60,
		},
		{
			ID: "cpu-iowait-high", Category: "system_metric", SubCategory: "cpu",
			Keywords:  []string{"iowait", "io wait", "cpu io", "waiting for io"},
			Severity:  "high",
			RootCause: "High CPU iowait indicates processes are blocked waiting for disk I/O to complete",
			Reasoning: []string{
				"iowait > 30% means CPUs are idle but processes cannot proceed because disk is slow",
				"Common causes: slow disk, RAID rebuild, heavy logging, database checkpoint, or swap thrashing",
				"This manifests as high load average but low CPU user/system time",
			},
			Impact:          "All I/O-dependent operations slow down; database queries lag; log writes block",
			ResolutionSteps: []string{"Identify I/O-heavy processes: iotop -o (or pidstat -d 1 5)", "Check disk throughput and latency: iostat -x 1 5 (look for high await, low throughput)", "Check if swap is being used heavily: swapon --show && free -h", "Reduce logging verbosity if logs are the culprit: check /var/log sizes", "Move database or logs to faster storage (SSD/NVMe)"},
			Prevention:      "Use SSDs for write-heavy workloads; separate log volume from data volume; disable swap for databases",
			BaseConfidence:  75, BaseRiskScore: 65,
		},
		{
			ID: "cpu-system-high", Category: "system_metric", SubCategory: "cpu",
			Keywords:  []string{"cpu system", "system time", "kernel cpu", "syscall overhead"},
			Severity:  "medium",
			RootCause: "High system CPU time indicates excessive kernel overhead from system calls or context switching",
			Reasoning: []string{
				"System CPU > 50% means the kernel is doing more work than user applications",
				"Common causes: excessive logging, network packet processing, many small I/O operations",
				"Too many context switches from high thread/process counts amplify kernel overhead",
			},
			Impact:          "Reduced application throughput; higher latency; wasted compute resources",
			ResolutionSteps: []string{"Check context switch rate: vmstat 1 5 (look at 'cs' column)", "Profile system calls: strace -c -p <PID> (find which syscalls dominate)", "Reduce number of threads/processes if context switching is high", "Batch small I/O operations; use buffered writes instead of sync writes", "Check for network interrupt storms: cat /proc/interrupts | head -20"},
			Prevention:      "Use async I/O; batch small operations; tune thread pool sizes to match core count",
			BaseConfidence:  65, BaseRiskScore: 50,
		},
		{
			ID: "cpu-nice-high", Category: "system_metric", SubCategory: "cpu",
			Keywords:  []string{"cpu nice", "nice priority", "low priority cpu"},
			Severity:  "low",
			RootCause: "Low-priority (nice) processes are consuming significant CPU, starving normal-priority work",
			Reasoning: []string{
				"High nice CPU usage means background tasks (backups, batch jobs) are using available cycles",
				"While nice processes yield to normal priority, at high levels they still consume resources",
				"This is usually benign but can indicate runaway background jobs",
			},
			Impact:          "Background tasks compete with production workloads during load spikes",
			ResolutionSteps: []string{"Identify nice processes: ps -eo pid,ni,%cpu,comm --sort=-%cpu | head -20", "Reschedule background jobs to off-peak hours", "Lower the priority further: renice +19 -p <PID>", "Set CPU quotas for background services via cgroups"},
			Prevention:      "Schedule batch jobs during maintenance windows; use cgroup CPU quotas for background work",
			BaseConfidence:  60, BaseRiskScore: 30,
		},
		{
			ID: "load-avg-high", Category: "system_metric", SubCategory: "cpu",
			Keywords:   []string{"load average", "high load", "system load", "load critical"},
			MetricName: "system.load.1", Severity: "high",
			RootCause: "System load average exceeds 2x the CPU core count, indicating severe resource contention",
			Reasoning: []string{
				"Load average counts processes in the run queue plus those waiting for I/O",
				"When load exceeds 2x cores, processes spend more time waiting than executing",
				"High load with low CPU may indicate I/O bottleneck; high load with high CPU indicates compute saturation",
			},
			Impact:          "All processes on the host experience scheduling delays; SSH becomes slow; monitoring may lag",
			ResolutionSteps: []string{"Check load vs CPU count: nproc && uptime", "If CPU-bound: top -o %CPU -b -n 1 | head -10 to find culprit", "If I/O-bound: iotop -o to find disk-heavy processes", "Check for process storms: ps aux | wc -l (normal is < 300)", "Shed non-essential workload or scale horizontally"},
			Prevention:      "Set load average alerts relative to core count (warn at 1.5x, critical at 2x cores)",
			BaseConfidence:  75, BaseRiskScore: 70,
		},
		{
			ID: "load-avg-critical", Category: "system_metric", SubCategory: "cpu",
			Keywords:   []string{"load average", "load 4x", "extreme load", "overloaded"},
			MetricName: "system.load.1", Severity: "critical",
			RootCause: "System load average exceeds 4x the CPU core count, the host is critically overloaded",
			Reasoning: []string{
				"At 4x core count load, the OS run queue is severely backed up",
				"New processes may fail to start; SSH connections may time out",
				"This level typically indicates a fork bomb, runaway job, or complete resource exhaustion",
			},
			Impact:          "Host is effectively unusable; services are unresponsive; monitoring agents may fail to report",
			ResolutionSteps: []string{"If SSH works: immediately check for fork bomb: ps aux | wc -l", "Kill all processes from the offending user: pkill -u <username>", "If SSH fails: use out-of-band management (IPMI/iLO/cloud console) to restart", "After recovery: check /var/log/syslog for OOM killer or kernel messages", "Implement process limits: /etc/security/limits.conf set nproc limits"},
			Prevention:      "Set nproc limits per user; use cgroups to limit process spawning; alert on load > 3x cores",
			BaseConfidence:  85, BaseRiskScore: 90,
		},
		{
			ID: "cpu-throttled", Category: "system_metric", SubCategory: "cpu",
			Keywords:  []string{"cpu throttled", "throttling", "cpu limit", "cgroup throttle", "nr_throttled"},
			Severity:  "medium",
			RootCause: "Container or process is being CPU-throttled by cgroup resource limits",
			Reasoning: []string{
				"Throttling occurs when the process exceeds its allocated CPU quota within the cgroup period",
				"The process is forced to wait even though physical CPU is available",
				"This causes tail latency spikes at periodic intervals matching the cgroup period (usually 100ms)",
			},
			Impact:          "Periodic latency spikes; P99 latency much higher than P50; intermittent timeouts",
			ResolutionSteps: []string{"Check throttling stats: cat /sys/fs/cgroup/cpu/*/cpu.stat | grep throttled", "Increase CPU limit in container spec or cgroup configuration", "For Kubernetes: increase resources.limits.cpu in the pod spec", "Profile to reduce CPU usage: optimize hot code paths", "Consider using burstable CPU classes if supported by your orchestrator"},
			Prevention:      "Set CPU limits 20% above average usage; monitor nr_throttled counter; use CPU requests = limits for latency-sensitive services",
			BaseConfidence:  70, BaseRiskScore: 55,
		},
	}
}

func buildMemoryEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "mem-high-90", Category: "system_metric", SubCategory: "memory",
			Keywords:   []string{"memory", "high memory", "memory usage", "memory used"},
			AntiWords:  []string{"swap", "oom", "killed"},
			MetricName: "system.memory.used.percent", Severity: "high",
			RootCause: "Memory utilization has exceeded 90%, leaving little headroom for allocation spikes",
			Reasoning: []string{
				"At 90%+ memory, the kernel starts reclaiming page cache aggressively",
				"Any new allocation spike (deploy, traffic burst) can push the system into OOM",
				"Application performance degrades as the kernel spends time in memory reclamation",
			},
			Impact:          "Risk of OOM kills; degraded I/O performance from reduced page cache; potential service restarts",
			ResolutionSteps: []string{"Check memory breakdown: free -h (look at available, not free)", "Find memory-hungry processes: ps aux --sort=-%mem | head -10", "Check for memory leaks: monitor RSS growth over time for top processes", "Clear page cache if temporary relief needed: sync && echo 3 > /proc/sys/vm/drop_caches", "Add memory or migrate workloads to reduce pressure"},
			Prevention:      "Set memory alerts at 80% warning; right-size container memory limits; implement memory leak detection",
			BaseConfidence:  75, BaseRiskScore: 70,
		},
		{
			ID: "mem-critical-95", Category: "system_metric", SubCategory: "memory",
			Keywords:   []string{"memory 95", "memory 96", "memory 97", "memory 98", "memory 99", "critical memory"},
			MetricName: "system.memory.used.percent", Severity: "critical",
			RootCause: "Memory utilization is critically high above 95%, OOM kill is imminent",
			Reasoning: []string{
				"At 95%+ the OOM killer is likely to activate on the next allocation",
				"The kernel has exhausted all page cache and buffer reclamation options",
				"Any new process or memory allocation will fail or trigger OOM kill",
			},
			Impact:          "Imminent process kills by OOM killer; critical services may be terminated unexpectedly",
			ResolutionSteps: []string{"Identify and restart the leaking process: smem -t -k -s rss | tail -10", "Restart the largest non-critical process to free memory immediately", "Check for runaway cache: slabtop to see kernel slab allocations", "If container: increase memory limit and restart pod", "Emergency: add swap temporarily: fallocate -l 2G /swapfile && mkswap /swapfile && swapon /swapfile"},
			Prevention:      "Implement memory limits per service; use memory-based auto-scaling; run leak detection in CI",
			BaseConfidence:  85, BaseRiskScore: 90,
		},
		{
			ID: "oom-killed", Category: "system_metric", SubCategory: "memory",
			Keywords:  []string{"oom", "out of memory", "oom killer", "killed process", "oom-kill", "oomkilled"},
			Severity:  "critical",
			RootCause: "The Linux OOM killer terminated a process because the system ran out of available memory",
			Reasoning: []string{
				"The kernel OOM killer selects processes with the highest oom_score to free memory",
				"The killed process may not be the one causing the leak — it is the one easiest to kill",
				"After OOM kill, remaining processes may be in inconsistent state",
			},
			Impact:          "Service outage for the killed process; data loss if writes were in-flight; cascading failures",
			ResolutionSteps: []string{"Check which process was killed: dmesg | grep -i 'oom\\|killed process'", "Check OOM scores: cat /proc/*/oom_score_adj for critical services set to -1000", "Find the actual memory hog: journalctl -k | grep -i oom", "Increase memory for the service or fix the memory leak", "Protect critical processes: echo -1000 > /proc/<PID>/oom_score_adj"},
			Prevention:      "Set oom_score_adj=-1000 for critical services; implement memory limits; monitor RSS growth trends",
			BaseConfidence:  90, BaseRiskScore: 90,
		},
		{
			ID: "swap-usage-50", Category: "system_metric", SubCategory: "memory",
			Keywords:  []string{"swap usage", "swap used", "swapping", "swap space"},
			AntiWords: []string{"swap 80", "swap 90", "thrashing"},
			Severity:  "medium",
			RootCause: "System is using swap space, indicating physical memory is insufficient for the current workload",
			Reasoning: []string{
				"Swap usage means pages are being moved to disk, which is 100-1000x slower than RAM",
				"Database and latency-sensitive services suffer severely from swap",
				"Swap can mask a memory leak — the process grows without being OOM-killed",
			},
			Impact:          "Performance degradation for all swapped processes; increased I/O load; unpredictable latency",
			ResolutionSteps: []string{"Check swap details: swapon --show && free -h", "Find swapped processes: for pid in /proc/[0-9]*; do echo \"$(cat $pid/status 2>/dev/null | grep VmSwap) PID=$(basename $pid)\"; done | sort -k2 -rn | head -10", "Set swappiness to minimum for servers: sysctl vm.swappiness=1", "Add physical memory or reduce workload", "For databases: disable swap entirely: swapoff -a"},
			Prevention:      "Set vm.swappiness=1 for servers; never run databases with swap enabled; alert on swap > 10%",
			BaseConfidence:  70, BaseRiskScore: 55,
		},
		{
			ID: "swap-thrashing", Category: "system_metric", SubCategory: "memory",
			Keywords:  []string{"swap thrashing", "swap 80", "swap 90", "heavy swap", "swap critical"},
			Severity:  "critical",
			RootCause: "System is swap thrashing — continuously moving pages between RAM and disk",
			Reasoning: []string{
				"Swap thrashing creates a feedback loop: pages swapped out are immediately needed again",
				"CPU spends most time on page fault handling instead of useful work",
				"The system becomes effectively unusable even though it has not OOM-killed anything",
			},
			Impact:          "System nearly unresponsive; all services experience extreme latency; SSH may time out",
			ResolutionSteps: []string{"Check swap I/O rate: vmstat 1 5 (look at si/so columns for high values)", "Kill the largest memory consumer to break the thrashing cycle", "Disable swap: swapoff -a (warning: may trigger OOM killer)", "Add memory urgently or migrate workloads off this host", "As last resort, reboot the host and increase memory before restarting services"},
			Prevention:      "Size memory at 120% of working set; disable swap for production servers; use memory-based OOM protection",
			BaseConfidence:  80, BaseRiskScore: 85,
		},
		{
			ID: "memory-leak", Category: "system_metric", SubCategory: "memory",
			Keywords:  []string{"memory leak", "rss growing", "memory growing", "heap growing"},
			Severity:  "high",
			RootCause: "A memory leak is detected — process RSS is growing steadily over time without release",
			Reasoning: []string{
				"Monotonically increasing RSS that never decreases indicates leaked allocations",
				"The process will eventually consume all available memory and be OOM-killed",
				"Memory leaks are typically caused by unclosed connections, growing caches, or reference cycles",
			},
			Impact:          "Gradual performance degradation leading to eventual OOM kill and service outage",
			ResolutionSteps: []string{"Track RSS over time: pidstat -r -p <PID> 60 (every minute)", "For Java: take heap dump: jmap -dump:live,format=b,file=heap.hprof <PID>", "For Python: use tracemalloc to identify allocation sites", "For Node.js: take heap snapshot via Chrome DevTools protocol", "Restart the process as temporary mitigation while investigating the leak"},
			Prevention:      "Run memory profiling in CI; implement periodic heap dump analysis; set RSS growth rate alerts",
			BaseConfidence:  75, BaseRiskScore: 70,
		},
		{
			ID: "buffer-cache-pressure", Category: "system_metric", SubCategory: "memory",
			Keywords:  []string{"buffer cache", "page cache", "cache pressure", "reclaiming cache"},
			Severity:  "medium",
			RootCause: "System page cache is being aggressively reclaimed, degrading I/O read performance",
			Reasoning: []string{
				"When memory is tight, the kernel reclaims page cache first — this is by design",
				"However, aggressive reclamation means repeated file reads go to disk instead of cache",
				"Applications that rely on warm file cache (databases, search) see performance regression",
			},
			Impact:          "Increased disk I/O; slower file reads; database query latency increases",
			ResolutionSteps: []string{"Check cache size: free -h (look at buff/cache column)", "Check reclaim rate: vmstat 1 5 (look at 'cache' column trend)", "Identify what is consuming memory besides cache: ps aux --sort=-%mem | head -10", "Add memory to increase cache capacity", "Move the cache-dependent workload to a dedicated host with more RAM"},
			Prevention:      "Size memory to allow 30%+ for page cache; separate cache-sensitive workloads from memory-heavy apps",
			BaseConfidence:  60, BaseRiskScore: 45,
		},
		{
			ID: "huge-pages-exhausted", Category: "system_metric", SubCategory: "memory",
			Keywords:  []string{"huge pages", "hugepages", "transparent huge", "thp", "hugetlb"},
			Severity:  "medium",
			RootCause: "Huge page allocation pool is exhausted, causing fallback to standard 4KB pages",
			Reasoning: []string{
				"Applications configured for huge pages (databases, JVMs) lose TLB efficiency without them",
				"Fallback to 4KB pages increases TLB misses and reduces memory access performance",
				"This often happens after other VMs or processes consume the pre-allocated huge page pool",
			},
			Impact:          "Database and JVM performance degradation; increased CPU usage for TLB miss handling",
			ResolutionSteps: []string{"Check huge page usage: cat /proc/meminfo | grep -i huge", "Allocate more huge pages: sysctl vm.nr_hugepages=<count>", "Verify the application is configured to use huge pages", "Disable THP if causing latency issues: echo never > /sys/kernel/mm/transparent_hugepage/enabled"},
			Prevention:      "Pre-allocate huge pages at boot time in /etc/sysctl.conf; monitor huge page free count",
			BaseConfidence:  60, BaseRiskScore: 40,
		},
		{
			ID: "shared-memory-full", Category: "system_metric", SubCategory: "memory",
			Keywords:  []string{"shared memory", "shm full", "shmget", "out of shared memory"},
			Severity:  "high",
			RootCause: "System shared memory segment is full, preventing inter-process communication",
			Reasoning: []string{
				"Shared memory limits (SHMMAX, SHMALL) are exceeded by database or application demands",
				"PostgreSQL, Oracle, and other databases use shared memory extensively",
				"New connections or operations that need shared memory will fail",
			},
			Impact:          "Database connections may fail; IPC between processes breaks; new sessions rejected",
			ResolutionSteps: []string{"Check shared memory usage: ipcs -m", "Check kernel limits: sysctl kernel.shmmax kernel.shmall", "Increase limits: sysctl -w kernel.shmmax=<bytes>", "For PostgreSQL: reduce shared_buffers or increase kernel.shmmax", "Clean up orphaned segments: ipcrm -m <shmid>"},
			Prevention:      "Set shmmax and shmall in /etc/sysctl.conf based on database requirements; monitor with ipcs",
			BaseConfidence:  70, BaseRiskScore: 65,
		},
		{
			ID: "mem-fragmentation", Category: "system_metric", SubCategory: "memory",
			Keywords:  []string{"memory fragmentation", "fragmentation ratio", "fragmented memory"},
			Severity:  "medium",
			RootCause: "Memory is heavily fragmented, preventing allocation of large contiguous blocks",
			Reasoning: []string{
				"High fragmentation means free memory exists but not in contiguous chunks",
				"Large allocations (huge pages, DMA buffers) fail even though total free memory is sufficient",
				"This typically builds up over time on long-running systems",
			},
			Impact:          "Large memory allocations fail; huge page allocation fails; kernel may panic in extreme cases",
			ResolutionSteps: []string{"Check fragmentation: cat /proc/buddyinfo", "Trigger memory compaction: echo 1 > /proc/sys/vm/compact_memory", "Drop caches to aid compaction: sync && echo 3 > /proc/sys/vm/drop_caches", "Schedule periodic reboots for long-running hosts if fragmentation is chronic"},
			Prevention:      "Use huge pages to reduce fragmentation; schedule maintenance reboots for long-running hosts",
			BaseConfidence:  60, BaseRiskScore: 40,
		},
	}
}

func buildDiskEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "disk-warning-85", Category: "system_metric", SubCategory: "disk",
			Keywords:   []string{"disk", "disk usage", "disk used", "filesystem"},
			AntiWords:  []string{"inode", "iops", "latency", "read-only"},
			MetricName: "disk.used.percent", Severity: "high",
			RootCause: "Disk utilization has exceeded 85%, approaching capacity",
			Reasoning: []string{
				"At 85% disk, the system has limited space for logs, temp files, and data growth",
				"Some filesystems (ext4) reserve 5% for root by default, so usable space is even less",
				"Applications writing to disk may fail or slow down as free space dwindles",
			},
			Impact:          "Risk of write failures; log rotation may fail; database writes may stall",
			ResolutionSteps: []string{"Check disk usage: df -h", "Find large files and directories: du -sh /* 2>/dev/null | sort -hr | head -20", "Clean old logs: find /var/log -name '*.gz' -mtime +30 -delete", "Remove unused Docker images: docker system prune -a --volumes", "Expand the volume if on cloud storage"},
			Prevention:      "Set disk alerts at 75% warning; implement log rotation; use separate volumes for data and logs",
			BaseConfidence:  70, BaseRiskScore: 60,
		},
		{
			ID: "disk-critical-95", Category: "system_metric", SubCategory: "disk",
			Keywords:   []string{"disk 95", "disk 96", "disk 97", "disk 98", "disk 99", "disk critical"},
			MetricName: "disk.used.percent", Severity: "critical",
			RootCause: "Disk utilization is critically high above 95%, writes are at risk of failing",
			Reasoning: []string{
				"At 95%+ the filesystem may transition to read-only mode to prevent corruption",
				"Database WAL/binlog writes will fail, causing database crashes",
				"Application logs cannot be written, making debugging impossible",
			},
			Impact:          "Services crash due to write failures; databases stop; logging fails; system may become read-only",
			ResolutionSteps: []string{"Emergency: find and remove large dispensable files: find /tmp /var/tmp -type f -size +100M -delete", "Truncate large log files: truncate -s 0 /var/log/syslog", "Remove old journal logs: journalctl --vacuum-time=1d", "If Docker: docker system prune -af --volumes", "Expand volume immediately if on cloud: aws ec2 modify-volume / gcloud disks resize"},
			Prevention:      "Automate log rotation with size limits; use separate data volumes; implement auto-expanding volumes",
			BaseConfidence:  85, BaseRiskScore: 90,
		},
		{
			ID: "disk-full-100", Category: "system_metric", SubCategory: "disk",
			Keywords:  []string{"disk full", "no space left", "disk 100", "filesystem full"},
			Severity:  "critical",
			RootCause: "Disk is completely full — all write operations are failing",
			Reasoning: []string{
				"With 0 bytes free, all write system calls return ENOSPC",
				"Databases crash because they cannot write WAL/transaction logs",
				"Services cannot write logs, temp files, or state, causing cascading failures",
			},
			Impact:          "Complete service outage for all processes writing to this filesystem; data corruption risk",
			ResolutionSteps: []string{"Emergency: remove dispensable files: rm -rf /tmp/* /var/tmp/*", "Truncate the largest log file: ls -lhS /var/log/ | head -5 && truncate -s 0 /var/log/<largest>", "Find and remove core dumps: find / -name 'core.*' -delete 2>/dev/null", "Check for deleted-but-open files: lsof +L1 | grep deleted (restart those processes to reclaim)", "Expand filesystem: resize2fs /dev/<device> (after expanding the underlying volume)"},
			Prevention:      "Never allow production disks above 80%; use monitoring with auto-remediation for disk cleanup",
			BaseConfidence:  90, BaseRiskScore: 95,
		},
		{
			ID: "inode-exhaustion", Category: "system_metric", SubCategory: "disk",
			Keywords:  []string{"inode", "no inodes", "inode exhaustion", "no space left"},
			Severity:  "critical",
			RootCause: "Filesystem inodes are exhausted — cannot create new files even though disk space is available",
			Reasoning: []string{
				"Each file and directory consumes one inode; when all inodes are used, no new files can be created",
				"df -h shows space available but df -i shows 100% inode usage",
				"Common causes: millions of small files (session files, cache files, mail queue)",
			},
			Impact:          "Cannot create new files anywhere on the filesystem; services that write temp files fail",
			ResolutionSteps: []string{"Confirm inode exhaustion: df -i", "Find directories with many files: find / -xdev -printf '%h\\n' | sort | uniq -c | sort -rn | head -20", "Delete the small files causing exhaustion: find /path/to/dir -type f -delete", "Common culprits: /tmp, /var/spool/postfix, PHP session directories", "Reformat with more inodes if chronic: mkfs.ext4 -N <inode_count> /dev/<device>"},
			Prevention:      "Monitor inode usage alongside disk space; clean up session/cache directories with cron",
			BaseConfidence:  80, BaseRiskScore: 85,
		},
		{
			ID: "disk-io-latency", Category: "system_metric", SubCategory: "disk",
			Keywords:  []string{"disk latency", "io latency", "disk slow", "high await"},
			Severity:  "high",
			RootCause: "Disk I/O latency is elevated above 100ms, causing slow reads and writes",
			Reasoning: []string{
				"Normal disk latency is < 10ms for SSD and < 20ms for HDD",
				"Latency > 100ms indicates disk saturation, failing hardware, or storage backend issues",
				"All I/O-dependent services (databases, logging) are affected",
			},
			Impact:          "Database queries slow down; log writes block; application response time increases proportionally",
			ResolutionSteps: []string{"Check disk I/O metrics: iostat -x 1 10 (look at await and %util columns)", "Identify I/O-heavy processes: iotop -o", "Check for disk errors: dmesg | grep -i 'error\\|fail\\|reset'", "If cloud: check for burst credit exhaustion (AWS gp2/gp3 burst balance)", "Move to faster storage tier: migrate to NVMe or provisioned IOPS"},
			Prevention:      "Use provisioned IOPS for databases; monitor disk latency; separate log I/O from data I/O",
			BaseConfidence:  75, BaseRiskScore: 65,
		},
		{
			ID: "disk-read-write-errors", Category: "system_metric", SubCategory: "disk",
			Keywords:  []string{"disk error", "read error", "write error", "i/o error", "medium error"},
			Severity:  "critical",
			RootCause: "Physical disk is reporting read/write errors, indicating hardware failure",
			Reasoning: []string{
				"Disk I/O errors in dmesg indicate the physical media is failing",
				"The filesystem may remount as read-only to protect data",
				"Data on the failing sectors may already be lost",
			},
			Impact:          "Data loss risk; filesystem may go read-only; services crash on write failures",
			ResolutionSteps: []string{"Check disk health: smartctl -a /dev/sda (look for Reallocated_Sector_Ct)", "Check kernel messages: dmesg | grep -i 'error\\|fail\\|ata\\|scsi'", "If SMART shows pending sectors: back up data immediately", "Replace the disk and restore from backup", "For cloud instances: stop instance, detach volume, create new volume from snapshot"},
			Prevention:      "Monitor SMART health weekly; use RAID for data redundancy; maintain regular backups",
			BaseConfidence:  85, BaseRiskScore: 90,
		},
		{
			ID: "filesystem-readonly", Category: "system_metric", SubCategory: "disk",
			Keywords:  []string{"read-only", "readonly", "remount read-only", "ro filesystem"},
			Severity:  "critical",
			RootCause: "Filesystem has been remounted as read-only, typically due to disk errors or corruption",
			Reasoning: []string{
				"The kernel remounts filesystems read-only when it detects I/O errors to prevent further corruption",
				"This is a protective mechanism — the underlying disk or filesystem has serious issues",
				"All write operations fail with 'Read-only file system' error",
			},
			Impact:          "All writes fail; services crash; databases cannot operate; logs cannot be written",
			ResolutionSteps: []string{"Check mount status: mount | grep 'ro,'", "Check dmesg for the cause: dmesg | tail -50", "If disk errors: replace disk (see disk-read-write-errors steps)", "If filesystem corruption: run fsck (requires unmount): umount /dev/<device> && fsck -y /dev/<device>", "Remount as read-write after fixing: mount -o remount,rw /"},
			Prevention:      "Monitor disk health; use journaling filesystems (ext4, xfs); maintain RAID arrays",
			BaseConfidence:  85, BaseRiskScore: 90,
		},
		{
			ID: "raid-degraded", Category: "system_metric", SubCategory: "disk",
			Keywords:  []string{"raid degraded", "raid rebuild", "disk array", "mdadm"},
			Severity:  "high",
			RootCause: "RAID array is operating in degraded mode — one or more disks have failed",
			Reasoning: []string{
				"A degraded RAID has lost redundancy — another disk failure means data loss",
				"Rebuild operations put extra stress on remaining disks, increasing failure risk",
				"Performance may be reduced during rebuild as the array reconstructs parity",
			},
			Impact:          "No redundancy — next disk failure causes data loss; degraded I/O performance during rebuild",
			ResolutionSteps: []string{"Check RAID status: cat /proc/mdstat (software RAID) or vendor-specific tool", "Identify failed disk: mdadm --detail /dev/md0", "Replace failed disk and add to array: mdadm --add /dev/md0 /dev/<new_disk>", "Monitor rebuild progress: watch cat /proc/mdstat", "Do NOT reboot during rebuild unless absolutely necessary"},
			Prevention:      "Monitor RAID health daily; keep hot spares; replace disks proactively when SMART warns",
			BaseConfidence:  80, BaseRiskScore: 80,
		},
		{
			ID: "lvm-snapshot-full", Category: "system_metric", SubCategory: "disk",
			Keywords:  []string{"lvm snapshot", "snapshot full", "snapshot overflow", "snapshot invalid"},
			Severity:  "high",
			RootCause: "LVM snapshot has run out of space and been invalidated",
			Reasoning: []string{
				"LVM snapshots store only the changed blocks (COW); if the snapshot volume fills up, it is dropped",
				"An invalid snapshot means the backup taken from it is incomplete",
				"The origin volume continues to work but the snapshot is lost",
			},
			Impact:          "Backup from this snapshot is invalid; must retake backup from scratch",
			ResolutionSteps: []string{"Check snapshot status: lvs -o lv_name,lv_size,snap_percent", "Remove invalid snapshot: lvremove /dev/<vg>/<snapshot>", "Create new snapshot with more space: lvcreate -L 10G -s -n snap /dev/<vg>/<origin>", "Monitor snapshot fill rate: watch lvs -o snap_percent"},
			Prevention:      "Size snapshots to handle expected change rate; monitor snap_percent; keep snapshots short-lived",
			BaseConfidence:  65, BaseRiskScore: 55,
		},
		{
			ID: "filesystem-corruption", Category: "system_metric", SubCategory: "disk",
			Keywords:  []string{"filesystem corruption", "fsck needed", "superblock", "corrupt filesystem"},
			Severity:  "critical",
			RootCause: "Filesystem metadata is corrupted, requiring repair before safe operation",
			Reasoning: []string{
				"Corruption occurs from power loss, disk errors, or kernel bugs during writes",
				"Files may be missing, directories may show wrong sizes, or data may be silently wrong",
				"Continuing to use a corrupted filesystem risks spreading the damage",
			},
			Impact:          "Data integrity compromised; reads may return wrong data; writes may fail or corrupt further",
			ResolutionSteps: []string{"Check filesystem: dmesg | grep -i 'ext4\\|xfs\\|corrupt'", "Unmount the filesystem: umount /mount/point", "Run filesystem check: fsck -y /dev/<device>", "For XFS: xfs_repair /dev/<device>", "Restore from backup if fsck reports unrecoverable errors"},
			Prevention:      "Use UPS/battery backup; enable filesystem journaling; schedule periodic fsck on reboot",
			BaseConfidence:  80, BaseRiskScore: 90,
		},
	}
}

func buildNetworkEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "network-errors", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"network error", "interface error", "rx_errors", "tx_errors"},
			Severity:  "high",
			RootCause: "Network interface is reporting errors, indicating physical or driver issues",
			Reasoning: []string{
				"Network errors on the interface level indicate cable, NIC, or driver problems",
				"Even a small error rate causes TCP retransmissions and application-level timeouts",
				"Errors tend to worsen over time as the underlying hardware degrades",
			},
			Impact:          "Packet loss causes retransmissions; TCP connections stall; application latency spikes",
			ResolutionSteps: []string{"Check interface errors: ip -s link show", "Check for cable issues: ethtool <interface> (check link detected, speed)", "Check driver errors: dmesg | grep -i 'eth\\|enic\\|ixgbe'", "Replace network cable if physical", "Update NIC driver: modinfo <driver_name> to check version"},
			Prevention:      "Monitor interface error counters; use bonded interfaces for redundancy; keep NIC drivers updated",
			BaseConfidence:  70, BaseRiskScore: 65,
		},
		{
			ID: "packet-drops", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"packet drop", "dropped packet", "rx_dropped", "tx_dropped"},
			Severity:  "high",
			RootCause: "Network packets are being dropped at the host level",
			Reasoning: []string{
				"Drops occur when the kernel receive buffer overflows or the NIC ring buffer is full",
				"High interrupt rates without enough CPU capacity cause drops",
				"Each dropped packet triggers a TCP retransmission, amplifying latency",
			},
			Impact:          "Increased latency from retransmissions; potential connection resets; degraded throughput",
			ResolutionSteps: []string{"Check drop counters: netstat -s | grep -i drop", "Increase ring buffer: ethtool -G <interface> rx 4096", "Increase kernel receive buffer: sysctl -w net.core.rmem_max=16777216", "Check for NIC interrupt affinity: cat /proc/interrupts | grep <interface>", "Enable receive packet steering (RPS) for multi-core: echo <mask> > /sys/class/net/<iface>/queues/rx-0/rps_cpus"},
			Prevention:      "Tune ring buffer and kernel socket buffers; use NAPI/interrupt coalescing; monitor drop rates",
			BaseConfidence:  70, BaseRiskScore: 65,
		},
		{
			ID: "interface-down", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"interface down", "link down", "nic down", "carrier lost"},
			Severity:  "critical",
			RootCause: "Network interface is down — all network connectivity through this interface is lost",
			Reasoning: []string{
				"Interface down means complete network isolation via this path",
				"Could be cable disconnection, switch port issue, or NIC failure",
				"If this is the only interface, the host is completely unreachable",
			},
			Impact:          "Complete network outage via this interface; services unreachable; monitoring blind spot",
			ResolutionSteps: []string{"Check interface status: ip link show", "Bring interface up: ip link set <interface> up", "Check physical cable connection", "Check switch port status (contact network team)", "If bonded interface: verify secondary is active: cat /proc/net/bonding/bond0"},
			Prevention:      "Use bonded/teamed interfaces for redundancy; monitor link state; use out-of-band management (IPMI)",
			BaseConfidence:  85, BaseRiskScore: 90,
		},
		{
			ID: "bandwidth-saturation", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"bandwidth", "saturated", "throughput limit", "network capacity"},
			Severity:  "high",
			RootCause: "Network bandwidth is saturated, causing congestion and increased latency",
			Reasoning: []string{
				"When link capacity is reached, packets queue and latency increases dramatically",
				"TCP flows compete and each gets progressively less bandwidth (congestion collapse)",
				"Burst traffic from batch jobs or large transfers can saturate links quickly",
			},
			Impact:          "All network traffic on the link experiences increased latency; packet loss increases",
			ResolutionSteps: []string{"Check bandwidth usage: iftop -i <interface> or nload", "Identify top bandwidth consumers: nethogs <interface>", "Rate-limit non-critical traffic: tc qdisc add dev <iface> root tbf rate 500mbit burst 32kbit", "Move bulk transfers to off-peak hours", "Upgrade link capacity or add additional network paths"},
			Prevention:      "Monitor bandwidth utilization; implement QoS for critical traffic; schedule bulk transfers off-peak",
			BaseConfidence:  70, BaseRiskScore: 60,
		},
		{
			ID: "tcp-retransmissions", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"retransmission", "tcp retrans", "packet retransmit"},
			Severity:  "high",
			RootCause: "High TCP retransmission rate indicates network path issues between hosts",
			Reasoning: []string{
				"Retransmissions occur when TCP ACKs are not received within the timeout window",
				"Each retransmission adds at least one RTT of latency to the affected flow",
				"Common causes: congested links, faulty cables, or overloaded intermediate switches",
			},
			Impact:          "Increased tail latency; reduced throughput; TCP connections may reset after max retries",
			ResolutionSteps: []string{"Check retransmission stats: ss -ti | grep retrans", "Monitor retransmit rate: netstat -s | grep retransmit", "Trace the network path: mtr <destination> (identifies lossy hops)", "Check for duplex mismatch: ethtool <interface>", "Adjust TCP congestion control: sysctl net.ipv4.tcp_congestion_control=bbr"},
			Prevention:      "Monitor retransmission rate; use TCP BBR congestion control; maintain network hardware",
			BaseConfidence:  70, BaseRiskScore: 60,
		},
		{
			ID: "dns-resolution-failure", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"dns resolution", "dns failure", "name resolution", "nxdomain", "nslookup failed", "getaddrinfo"},
			Severity:  "critical",
			RootCause: "DNS resolution is failing, preventing services from connecting to dependencies by hostname",
			Reasoning: []string{
				"DNS failures affect every service that resolves hostnames — virtually everything",
				"Could be DNS server down, /etc/resolv.conf misconfigured, or upstream DNS issue",
				"Services cache DNS records for TTL, so failures may appear with a delay after DNS goes down",
			},
			Impact:          "All hostname-based connections fail; services cannot reach databases, APIs, or each other",
			ResolutionSteps: []string{"Test DNS resolution: dig example.com @<dns_server>", "Check resolv.conf: cat /etc/resolv.conf", "Test with public DNS: dig example.com @8.8.8.8", "Restart local DNS cache: systemctl restart systemd-resolved", "If using CoreDNS (Kubernetes): kubectl get pods -n kube-system -l k8s-app=kube-dns"},
			Prevention:      "Use multiple DNS servers in resolv.conf; implement DNS caching; monitor DNS latency and failures",
			BaseConfidence:  85, BaseRiskScore: 85,
		},
		{
			ID: "arp-storm", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"arp storm", "arp flood", "arp broadcast", "arp table full"},
			Severity:  "high",
			RootCause: "ARP broadcast storm is flooding the network segment with excessive ARP traffic",
			Reasoning: []string{
				"ARP storms occur from misconfigured hosts, loops, or ARP spoofing attacks",
				"Excessive ARP traffic consumes bandwidth and CPU on all hosts in the broadcast domain",
				"Switches may become overwhelmed and start flooding all traffic",
			},
			Impact:          "Network segment congestion; all hosts on the segment experience latency; switch CPU spikes",
			ResolutionSteps: []string{"Check ARP table: arp -n | wc -l (abnormally high count = storm)", "Identify the source: tcpdump -i <interface> arp | head -50", "Check for network loops: look for STP topology changes in switch logs", "Implement ARP rate limiting on switches", "Isolate the offending host by disabling its switch port"},
			Prevention:      "Enable STP (Spanning Tree Protocol) on switches; implement dynamic ARP inspection; use VLANs",
			BaseConfidence:  65, BaseRiskScore: 60,
		},
		{
			ID: "network-latency-spike", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"network latency", "latency spike", "high latency", "ping timeout", "round trip"},
			Severity:  "high",
			RootCause: "Network latency between hosts has spiked significantly above baseline",
			Reasoning: []string{
				"Latency spikes indicate congestion, routing changes, or link degradation on the path",
				"Applications with tight timeout settings will fail during latency spikes",
				"Intermittent spikes suggest shared infrastructure contention (cloud networks, busy switches)",
			},
			Impact:          "Service timeouts; database query latency increases; distributed system clock sync issues",
			ResolutionSteps: []string{"Measure latency and find the bottleneck hop: mtr -r -c 100 <destination>", "Check for congestion on the local interface: ethtool -S <interface> | grep -i coll", "Verify routing has not changed: ip route show", "Check for QoS or traffic shaping affecting the flow", "Contact network team with mtr output showing the problematic hop"},
			Prevention:      "Monitor inter-host latency; use dedicated network links for critical traffic; implement circuit breakers",
			BaseConfidence:  70, BaseRiskScore: 60,
		},
		{
			ID: "conntrack-table-full", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"conntrack", "connection tracking", "nf_conntrack", "table full"},
			Severity:  "critical",
			RootCause: "Linux connection tracking table (nf_conntrack) is full, dropping new connections",
			Reasoning: []string{
				"Every network connection uses an entry in the conntrack table (used by iptables/NAT)",
				"Default limit is often 65536, which is too low for busy servers or load balancers",
				"When full, new connections are silently dropped — no error message on the client side",
			},
			Impact:          "New TCP connections randomly fail; load balancer drops requests; intermittent connectivity",
			ResolutionSteps: []string{"Check current usage: cat /proc/sys/net/netfilter/nf_conntrack_count", "Check limit: cat /proc/sys/net/netfilter/nf_conntrack_max", "Increase limit: sysctl -w net.netfilter.nf_conntrack_max=262144", "Reduce timeout for established connections: sysctl -w net.netfilter.nf_conntrack_tcp_timeout_established=600", "Check for connection leaks: conntrack -L | wc -l"},
			Prevention:      "Set nf_conntrack_max to at least 4x expected concurrent connections; reduce timeout values; monitor conntrack usage",
			BaseConfidence:  80, BaseRiskScore: 80,
		},
		{
			ID: "mtu-mismatch", Category: "system_metric", SubCategory: "network",
			Keywords:  []string{"mtu mismatch", "mtu", "packet too large", "fragmentation needed"},
			Severity:  "medium",
			RootCause: "MTU mismatch on network path causing packet fragmentation or drops",
			Reasoning: []string{
				"Different MTU settings along a path cause large packets to be dropped if DF bit is set",
				"Common in VPN tunnels, overlay networks, and cloud environments with jumbo frames",
				"Symptoms: small requests work fine but large responses fail intermittently",
			},
			Impact:          "Large transfers fail; intermittent connection resets; TLS handshakes may fail",
			ResolutionSteps: []string{"Test MTU on the path: ping -M do -s 1472 <destination>", "Check interface MTU: ip link show | grep mtu", "Reduce MTU to account for encapsulation: ip link set <interface> mtu 1400", "For VPN/overlay: set tunnel MTU to account for overhead (typically 1400 for VXLAN)", "Enable PMTUD: sysctl -w net.ipv4.ip_no_pmtu_disc=0"},
			Prevention:      "Standardize MTU across the infrastructure; document MTU for overlay/tunnel networks",
			BaseConfidence:  65, BaseRiskScore: 50,
		},
	}
}

func buildSystemEntries() []KnowledgeEntry {
	return []KnowledgeEntry{
		{
			ID: "system-load-critical", Category: "system_metric", SubCategory: "system",
			Keywords:  []string{"system load", "system overloaded", "load critical"},
			Severity:  "critical",
			RootCause: "System is critically overloaded — load average far exceeds available CPU cores",
			Reasoning: []string{
				"Critical system load means the run queue has many more processes than the CPU can handle",
				"Processes compete for CPU time, causing everything to slow down",
				"May be caused by a fork bomb, runaway process spawning, or resource exhaustion",
			},
			Impact:          "All services on the host are affected; SSH may be unresponsive; monitoring may fail",
			ResolutionSteps: []string{"Check load and CPU count: nproc && cat /proc/loadavg", "Kill runaway processes: ps aux --sort=-%cpu | head -5", "Check for fork bomb: ps aux | wc -l", "Reboot if host is unresponsive via out-of-band management", "After recovery, identify root cause in /var/log/syslog"},
			Prevention:      "Set per-user process limits in /etc/security/limits.conf; monitor load average relative to core count",
			BaseConfidence:  80, BaseRiskScore: 85,
		},
		{
			ID: "system-reboot", Category: "system_metric", SubCategory: "system",
			Keywords:  []string{"just rebooted", "uptime 0", "system restarted", "unexpected reboot"},
			Severity:  "high",
			RootCause: "System has recently rebooted, possibly due to kernel panic, OOM, or hardware failure",
			Reasoning: []string{
				"An unexpected reboot indicates a critical system failure occurred",
				"Check if it was a planned maintenance or unplanned crash",
				"Services may not have started correctly after the reboot",
			},
			Impact:          "Service interruption during reboot; potential data loss from unclean shutdown",
			ResolutionSteps: []string{"Check uptime: uptime", "Check last reboot cause: last reboot | head -5", "Check for kernel panic: dmesg | grep -i panic", "Check for OOM kill before reboot: journalctl -b -1 | grep -i oom", "Verify all services started: systemctl --failed"},
			Prevention:      "Implement watchdog timers; use HA failover for critical services; monitor uptime alerts",
			BaseConfidence:  70, BaseRiskScore: 60,
		},
		{
			ID: "ntp-drift", Category: "system_metric", SubCategory: "system",
			Keywords:  []string{"ntp drift", "clock skew", "time sync", "time drift", "clock drift"},
			Severity:  "medium",
			RootCause: "System clock has drifted from NTP reference, causing time synchronization issues",
			Reasoning: []string{
				"Clock drift > 1s causes issues with TLS certificate validation, Kerberos auth, and distributed systems",
				"Database replication, distributed locks, and event ordering break with clock skew",
				"Common causes: NTP service not running, firewall blocking NTP, or virtualization overhead",
			},
			Impact:          "Authentication failures; database replication issues; incorrect log timestamps; distributed system inconsistency",
			ResolutionSteps: []string{"Check clock offset: timedatectl status", "Force sync: chronyc makestep (or ntpdate -u pool.ntp.org)", "Check NTP service: systemctl status chronyd (or ntpd)", "Verify NTP server reachability: chronyc sources -v", "Check firewall allows UDP 123: iptables -L -n | grep 123"},
			Prevention:      "Ensure chrony/NTP is configured and running; monitor clock offset; alert at > 100ms drift",
			BaseConfidence:  65, BaseRiskScore: 50,
		},
		{
			ID: "kernel-panic", Category: "system_metric", SubCategory: "system",
			Keywords:  []string{"kernel panic", "system panic", "kernel oops", "kernel crash"},
			Severity:  "critical",
			RootCause: "Kernel panic — the operating system encountered an unrecoverable error and halted",
			Reasoning: []string{
				"Kernel panics are caused by hardware failures, driver bugs, or kernel bugs",
				"The system halts immediately; all processes are terminated without cleanup",
				"Data on disk may be in inconsistent state if writes were in-flight",
			},
			Impact:          "Complete system outage; potential data corruption; requires reboot to recover",
			ResolutionSteps: []string{"Check panic message: dmesg | grep -A5 panic (after reboot)", "Check /var/crash or /var/log/kern.log for crash dump", "If hardware error: check memory (memtest86+), disk (smartctl), CPU temperature", "If driver: check for kernel module updates or remove the offending module", "If repeating: collect crash dump with kdump and file a kernel bug report"},
			Prevention:      "Keep kernel updated; test hardware with memtest86+; configure kdump for crash analysis; monitor dmesg for warnings",
			BaseConfidence:  90, BaseRiskScore: 95,
		},
		{
			ID: "zombie-processes", Category: "system_metric", SubCategory: "system",
			Keywords:  []string{"zombie", "defunct", "zombie process", "Z state"},
			Severity:  "medium",
			RootCause: "Zombie processes are accumulating — parent process is not reaping child exit statuses",
			Reasoning: []string{
				"Zombie processes do not consume CPU or memory but do consume a PID entry",
				"If PID table fills up, no new processes can be started (critical failure)",
				"Zombies indicate the parent process has a bug in signal handling or wait() calls",
			},
			Impact:          "PID table may fill up preventing new process creation; indicates buggy parent process",
			ResolutionSteps: []string{"Count zombies: ps aux | awk '$8==\"Z\" {print}' | wc -l", "Find zombie parents: ps -eo pid,ppid,stat,cmd | awk '$3==\"Z\" {print $2}' | sort -u", "Restart the parent process to clear zombies", "If parent is PID 1 (init): this is a system-level bug, check init system", "Monitor PID limit: cat /proc/sys/kernel/pid_max"},
			Prevention:      "Implement proper signal handling in parent processes; use wait()/waitpid() in fork-based code",
			BaseConfidence:  60, BaseRiskScore: 40,
		},
	}
}
