package services

import "ai-incident-platform/backend/internal/models"

// integrationCatalog is the canonical 53-entry integration catalog.
// It is product-defined, never tenant-specific, and changes only through code.
var integrationCatalog = []models.IntegrationEntry{

	// ── Monitoring ────────────────────────────────────────────────────────────

	{
		ID: "prometheus", Name: "Prometheus", Category: models.CategoryMonitoring,
		Description:  "Receive Alertmanager webhooks from your Prometheus stack. Supports full alert payload including labels, annotations, and grouping.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/prometheus",
		TestStrategy: models.TestInboundWebhook, Popular: true,
		Tags: []string{"metrics", "alertmanager", "cncf"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"version":"4","groupKey":"{}:{alertname=\"HighErrorRate\"}","status":"firing","groupLabels":{"alertname":"HighErrorRate"},"commonLabels":{"alertname":"HighErrorRate","severity":"critical","service":"checkout-api"},"commonAnnotations":{"summary":"Error rate > 5%","description":"checkout-api error rate is 8.3%"},"alerts":[{"status":"firing","labels":{"alertname":"HighErrorRate","severity":"critical","service":"checkout-api"},"annotations":{"summary":"Error rate > 5%"},"startsAt":"2024-01-15T10:00:00Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus/graph?g0.expr=error_rate%3E0.05"}]}`,
		DocsHint: "Set webhook_url in Alertmanager route config. Use the Prometheus-native endpoint for full label support.",
	},
	{
		ID: "grafana", Name: "Grafana", Category: models.CategoryMonitoring,
		Description:  "Route Grafana alert notifications via webhook. Supports Grafana 9+ unified alerting and legacy notification channels.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: true,
		Tags: []string{"dashboards", "visualization", "observability"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"dashboardId":1,"evalMatches":[{"value":8.3,"metric":"error_rate","tags":{"service":"api"}}],"message":"Error rate exceeded threshold","orgId":1,"panelId":2,"ruleId":10,"ruleName":"High Error Rate","ruleUrl":"http://grafana/alerting","state":"alerting","tags":{"severity":"critical","service":"api"},"title":"[Alerting] High Error Rate"}`,
		DocsHint: "Add a Webhook notification channel in Grafana. Paste the webhook URL from the integration.",
	},
	{
		ID: "datadog", Name: "Datadog", Category: models.CategoryMonitoring,
		Description:  "Ingest Datadog monitor alerts and events. Supports custom webhook format with HMAC signature verification.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/datadog",
		TestStrategy: models.TestInboundWebhook, Popular: true,
		Tags: []string{"apm", "metrics", "logs"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "webhook_secret", Label: "Webhook Secret", Type: "password", Required: false, Placeholder: "dd-webhook-secret", HelpText: "Optional HMAC secret for payload signature verification."},
		},
		SamplePayload: `{"id":123456789,"event_type":"monitor_alert","last_updated":"2024-01-15T10:00:00.000Z","event_type":"monitor_alert","title":"Monitor Alert: High Error Rate on api-service","body":"@webhook-neuroops Monitor alert triggered","msg":"Error rate exceeded 5% threshold","priority":"normal","source_type_name":"Monitor Alert","tags":["env:production","service:api","severity:critical"],"alert_id":12345,"alert_metric":"requests.error","alert_query":"avg(last_5m):error_rate{service:api} > 0.05","alert_scope":"service:api","alert_status":"triggered","date":"1705313200","host":"api-server-01","org":{"id":123,"name":"acme-corp"}}`,
		DocsHint: "Create a Webhook integration in Datadog. Use the custom payload template for enriched data.",
	},
	{
		ID: "newrelic", Name: "New Relic", Category: models.CategoryMonitoring,
		Description:  "Receive New Relic alert policy notifications and infrastructure events via webhook.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: true,
		Tags: []string{"apm", "infrastructure", "synthetics"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"account_id":1234567,"account_name":"Acme Corp","closed_violations_count_critical":0,"closed_violations_count_warning":0,"condition_id":123456,"condition_name":"High Error Rate","current_state":"triggered","details":"Error rate for api-service is 8.3%","duration":300,"event_type":"NOTIFICATION","incident_acknowledge_url":"https://alerts.newrelic.com/accounts/123/incidents/456","incident_id":456,"incident_url":"https://alerts.newrelic.com/accounts/123/incidents/456","metadata":{"entity.guid":"entity-guid-here","entity.name":"api-service","entity.type":"APPLICATION"},"open_violations_count_critical":1,"owner":"Unassigned","policy_name":"Production Alerts","policy_url":"https://alerts.newrelic.com/accounts/123/policies/789","runbook_url":"","severity":"CRITICAL","targets":[{"id":"entity-guid","name":"api-service","labels":{"app":"checkout","env":"production"},"product":"APM","type":"APPLICATION","link":"https://rpm.newrelic.com"}],"timestamp":1705313200000,"timestamp_utc_string":"2024-01-15 10:00:00.000 UTC","version":1,"violation_chart_url":"https://chart-url","violation_callback_url":"https://alerts.newrelic.com/accounts/123/incidents/456"}`,
		DocsHint: "Configure an alert notification channel of type Webhook in New Relic alert policies.",
	},
	{
		ID: "dynatrace", Name: "Dynatrace", Category: models.CategoryMonitoring,
		Description:  "Forward Dynatrace problems, events, and anomalies to NeuroOps for AI-powered correlation.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"fullstack", "ai-ops", "davis"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"State":"OPEN","ProblemID":"P-1234567","ProblemTitle":"Response time degradation on api-service","ProblemURL":"https://acme.live.dynatrace.com/problems","ProblemSeverity":"PERFORMANCE","ProblemImpact":"SERVICES","ProblemSummary":"Response time of api-service has degraded by 40%","ImpactedEntities":"api-service","ProblemDetailsText":"Response time degraded from 200ms to 280ms","Tags":"env:production,service:api","ImpactedEntity":"SERVICE-api12345"}`,
		DocsHint: "Go to Settings > Integrations > Problem notifications > Add webhook notification.",
	},
	{
		ID: "cloudwatch", Name: "AWS CloudWatch", Category: models.CategoryMonitoring,
		Description:  "Route CloudWatch Alarms and Composite Alarms through SNS HTTP subscriptions to NeuroOps.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: true,
		Tags: []string{"aws", "alarms", "sns"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"Type":"Notification","MessageId":"abc-12345","TopicArn":"arn:aws:sns:us-east-1:123456789012:alerts","Message":"{\"AlarmName\":\"HighCPU-api-server\",\"AlarmDescription\":\"CPU usage exceeded 80%\",\"AWSAccountId\":\"123456789012\",\"AlarmConfigurationUpdatedTimestamp\":\"2024-01-15T09:00:00.000Z\",\"NewStateValue\":\"ALARM\",\"NewStateReason\":\"Threshold Crossed: 1 datapoint (84.5) was greater than the threshold (80.0).\",\"StateChangeTime\":\"2024-01-15T10:00:00.000Z\",\"Region\":\"US East (N. Virginia)\",\"AlarmArn\":\"arn:aws:cloudwatch:us-east-1:123456789012:alarm:HighCPU-api-server\",\"OldStateValue\":\"OK\",\"Trigger\":{\"MetricName\":\"CPUUtilization\",\"Namespace\":\"AWS/EC2\",\"StatisticType\":\"Statistic\",\"Statistic\":\"AVERAGE\",\"Unit\":null,\"Dimensions\":[{\"value\":\"i-1234567890\",\"name\":\"InstanceId\"}],\"Period\":300,\"EvaluationPeriods\":1,\"DatapointsToAlarm\":1,\"ComparisonOperator\":\"GreaterThanThreshold\",\"Threshold\":80.0,\"TreatMissingData\":\"missing\",\"EvaluateLowSampleCountPercentile\":\"\"}}","Timestamp":"2024-01-15T10:00:00.000Z","SignatureVersion":"1","Subject":"ALARM: HighCPU-api-server"}`,
		DocsHint: "Create an SNS topic, subscribe with HTTP endpoint pointing to your webhook URL, confirm subscription.",
	},
	{
		ID: "azure-monitor", Name: "Azure Monitor", Category: models.CategoryMonitoring,
		Description:  "Receive Azure Monitor alerts and activity log events via Action Groups webhook.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"azure", "alerts", "activity-log"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"schemaId":"AzureMonitorMetricAlert","data":{"version":"2.0","properties":{"name":"HighCPUAlert","description":"CPU > 80%","conditions":[{"metricName":"Percentage CPU","operator":">","threshold":"80","timeAggregation":"Average"}]},"status":"Activated","context":{"id":"/subscriptions/sub-id/resourceGroups/rg/providers/Microsoft.Insights/metricAlerts/HighCPUAlert","name":"HighCPUAlert","type":"Microsoft.Insights/metricAlerts","resourceGroupName":"production-rg","portalLink":"https://portal.azure.com/#resource/...","timestamp":"2024-01-15T10:00:00.000Z","condition":{"windowSize":"PT5M","allOf":[{"metricName":"Percentage CPU","metricNamespace":"Microsoft.Compute/virtualMachines","operator":"GreaterThan","threshold":"80","timeAggregation":"Average","dimensions":[{"name":"ResourceId","value":"vm-api-01"}],"metricValue":85.2}]}}}}`,
		DocsHint: "Create an Action Group in Azure Monitor, add a webhook action pointing to the integration URL.",
	},
	{
		ID: "gcp-operations", Name: "GCP Operations Suite", Category: models.CategoryMonitoring,
		Description:  "Forward Google Cloud Monitoring alerts and log-based metrics via Pub/Sub push subscriptions.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"gcp", "stackdriver", "pubsub"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"incident":{"incident_id":"0.lh1dzg0n4c8d","resource_id":"","resource_name":"api-service","resource":{"type":"gce_instance","labels":{"project_id":"my-project","zone":"us-central1-a","instance_id":"1234567890"}},"metric":{"type":"compute.googleapis.com/instance/cpu/utilization","displayName":"CPU utilization"},"started_at":1705313200,"ended_at":null,"policy_name":"High CPU Policy","condition_name":"CPU > 80%","condition":{"name":"High CPU","conditionThreshold":{"filter":"resource.type = \"gce_instance\"","aggregations":[{"alignmentPeriod":"60s","crossSeriesReducer":"REDUCE_MEAN","perSeriesAligner":"ALIGN_MEAN"}],"comparison":"COMPARISON_GT","thresholdValue":0.8,"duration":"60s"}},"url":"https://console.cloud.google.com/monitoring/alerting","state":"open","summary":"CPU utilization for api-service exceeded 80%."}}`,
		DocsHint: "Configure Cloud Monitoring notification channels, choose Webhook type, paste integration URL.",
	},
	{
		ID: "zabbix", Name: "Zabbix", Category: models.CategoryMonitoring,
		Description:  "Forward Zabbix trigger alerts and problem events via Zabbix webhook media type.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"network", "infrastructure", "on-premise"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"event_id":"1234","trigger_id":"5678","trigger_name":"CPU usage > 80%","trigger_severity":"4","trigger_status":"PROBLEM","trigger_url":"","host_name":"api-server-01","host_ip":"10.0.0.1","item_name":"CPU utilization","item_value":"84.5","event_date":"2024-01-15","event_time":"10:00:00","event_age":"0d 0h 0m","event_tags":"env:production,service:api","problem_name":"CPU usage > 80% on api-server-01"}`,
		DocsHint: "Create a Webhook media type in Zabbix, configure trigger action to send to this URL.",
	},
	{
		ID: "nagios", Name: "Nagios", Category: models.CategoryMonitoring,
		Description:  "Route Nagios/Nagios XI service and host check results via event broker or HTTP notification.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"network", "infrastructure", "on-premise"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"notification_type":"PROBLEM","service_description":"HTTP Check","host_name":"api-server-01","host_address":"10.0.0.1","service_state":"CRITICAL","service_output":"CRITICAL - Connection refused","long_service_output":"Cannot connect to port 8080","service_state_type":"HARD","service_check_command":"check_http","service_ack_comment":"","notification_author":"","last_service_check":"2024-01-15T10:00:00Z","service_problem_id":"12345"}`,
		DocsHint: "Use Nagios notification commands to curl the webhook URL with alert data.",
	},
	{
		ID: "prtg", Name: "PRTG Network Monitor", Category: models.CategoryMonitoring,
		Description:  "Send PRTG sensor alerts and status changes via PRTG notifications using the HTTP action.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"network", "infrastructure", "windows"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"sitename":"PRTG Network Monitor","device":"Router-Core","sensor":"Ping","status":"Down","message":"No reply from device","priority":"5","group":"Network Infrastructure","probe":"Local Probe","host":"192.168.1.1","home_url":"https://prtg.acme.com","prtg_url":"https://prtg.acme.com/sensor.htm?id=12345","datetime":"2024-01-15 10:00:00","duration":"0 minutes"}`,
		DocsHint: "Add a notification trigger in PRTG and use the HTTP Push action to POST to the webhook URL.",
	},
	{
		ID: "icinga", Name: "Icinga 2", Category: models.CategoryMonitoring,
		Description:  "Integrate Icinga 2 service and host notifications using the IcingaWeb2 notification plugin.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"network", "infrastructure", "open-source"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"notification_type":"PROBLEM","service":"HTTP Check","hostname":"api-server-01","hostaddress":"10.0.0.1","servicestatus":"CRITICAL","serviceoutput":"Connection refused","serviceproblemid":"12345","notificationauthorname":"Icinga2","hosteventid":"67890","long_datetime":"2024-01-15 10:00:00 UTC"}`,
		DocsHint: "Configure an Icinga 2 notification command that POSTs to the webhook URL.",
	},

	// ── Ticketing ─────────────────────────────────────────────────────────────

	{
		ID: "jira", Name: "Jira", Category: models.CategoryTicketing,
		Description:  "Automatically create Jira issues from incidents. Supports Jira Cloud and Server via REST API v3.",
		AuthMethod:   models.AuthBasicAuth, Inbound: false, Outbound: true,
		TestStrategy: models.TestOutboundJira, Popular: true,
		Tags: []string{"ticketing", "atlassian", "agile"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "base_url", Label: "Jira Base URL", Type: "url", Required: true, Placeholder: "https://your-org.atlassian.net", HelpText: "Your Jira Cloud or Server base URL."},
			{Name: "email", Label: "Email / Username", Type: "text", Required: true, Placeholder: "ops@acme.com"},
			{Name: "api_token", Label: "API Token", Type: "password", Required: true, Placeholder: "ATATT3...", HelpText: "Generate at id.atlassian.com/manage-profile/security/api-tokens"},
			{Name: "project_key", Label: "Project Key", Type: "text", Required: true, Placeholder: "OPS"},
		},
		DocsHint: "Incidents auto-create Jira issues. Use workflow automation to keep status in sync.",
	},
	{
		ID: "servicenow", Name: "ServiceNow", Category: models.CategoryTicketing,
		Description:  "Create and sync ServiceNow incident records from NeuroOps via the ServiceNow Table API.",
		AuthMethod:   models.AuthBasicAuth, Inbound: false, Outbound: true,
		TestStrategy: models.TestOutboundSnow, Popular: true,
		Tags: []string{"itsm", "enterprise", "ticketing"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "instance_url", Label: "Instance URL", Type: "url", Required: true, Placeholder: "https://your-instance.service-now.com"},
			{Name: "username", Label: "Username", Type: "text", Required: true, Placeholder: "admin"},
			{Name: "password", Label: "Password", Type: "password", Required: true, Placeholder: "••••••"},
		},
		DocsHint: "Requires a service account with itil role. Auto-assigns incidents to your team queues.",
	},
	{
		ID: "zendesk", Name: "Zendesk", Category: models.CategoryTicketing,
		Description:  "Create Zendesk tickets from critical incidents. Route to the right team based on service tags.",
		AuthMethod:   models.AuthAPIKey, Inbound: false, Outbound: true,
		TestStrategy: models.TestValidateConfig, Popular: false,
		Tags: []string{"ticketing", "support", "customer-success"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "subdomain", Label: "Subdomain", Type: "text", Required: true, Placeholder: "acme (for acme.zendesk.com)"},
			{Name: "email", Label: "Agent Email", Type: "text", Required: true, Placeholder: "ops@acme.com"},
			{Name: "api_token", Label: "API Token", Type: "password", Required: true, Placeholder: "zendesk-api-token"},
		},
		DocsHint: "Create an API token in Admin > Apps > API, then configure the subdomain and agent email.",
	},
	{
		ID: "freshservice", Name: "Freshservice", Category: models.CategoryTicketing,
		Description:  "Automatically raise Freshservice incidents with priority mapping from NeuroOps severity levels.",
		AuthMethod:   models.AuthAPIKey, Inbound: false, Outbound: true,
		TestStrategy: models.TestValidateConfig, Popular: false,
		Tags: []string{"itsm", "ticketing", "freshworks"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "domain", Label: "Domain", Type: "text", Required: true, Placeholder: "acme.freshservice.com"},
			{Name: "api_key", Label: "API Key", Type: "password", Required: true, Placeholder: "freshservice-api-key"},
		},
		DocsHint: "Generate an API key from your Freshservice Profile Settings page.",
	},
	{
		ID: "linear", Name: "Linear", Category: models.CategoryTicketing,
		Description:  "Create Linear issues from incidents. Map NeuroOps severity to Linear priority and assign to teams.",
		AuthMethod:   models.AuthAPIKey, Inbound: false, Outbound: true,
		TestStrategy: models.TestValidateConfig, Popular: false,
		Tags: []string{"ticketing", "project-management", "engineering"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "api_key", Label: "API Key", Type: "password", Required: true, Placeholder: "lin_api_...", HelpText: "Create at linear.app/settings/api"},
			{Name: "team_id", Label: "Team ID", Type: "text", Required: true, Placeholder: "linear-team-uuid"},
		},
		DocsHint: "Create a personal API key in Linear settings. The team ID is in the team's URL.",
	},
	{
		ID: "github-issues", Name: "GitHub Issues", Category: models.CategoryTicketing,
		Description:  "Open GitHub Issues from incidents. Automatically adds severity labels and links to runbooks.",
		AuthMethod:   models.AuthAPIKey, Inbound: false, Outbound: true,
		TestStrategy: models.TestValidateConfig, Popular: false,
		Tags: []string{"github", "issues", "engineering"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "token", Label: "Personal Access Token", Type: "password", Required: true, Placeholder: "ghp_...", HelpText: "Requires repo scope. Create at github.com/settings/tokens"},
			{Name: "owner", Label: "Repository Owner", Type: "text", Required: true, Placeholder: "acme-corp"},
			{Name: "repo", Label: "Repository Name", Type: "text", Required: true, Placeholder: "ops-incidents"},
		},
		DocsHint: "Create a PAT with repo scope. Issues will be created with incident severity as a label.",
	},

	// ── Communication ─────────────────────────────────────────────────────────

	{
		ID: "slack", Name: "Slack", Category: models.CategoryCommunication,
		Description:  "Post incident alerts and RCA summaries to Slack channels. Supports bot token with multi-channel routing.",
		AuthMethod:   models.AuthBotToken, Inbound: false, Outbound: true,
		TestStrategy: models.TestOutboundSlack, Popular: true,
		Tags: []string{"collaboration", "chat", "notifications"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "bot_token", Label: "Bot Token", Type: "password", Required: true, Placeholder: "xoxb-...", HelpText: "Create a Slack app and install it to your workspace. Requires chat:write scope."},
			{Name: "default_channel", Label: "Default Channel", Type: "text", Required: true, Placeholder: "#incidents"},
		},
		DocsHint: "Create a Slack app at api.slack.com/apps, add chat:write permission, install to workspace.",
	},
	{
		ID: "microsoft-teams", Name: "Microsoft Teams", Category: models.CategoryCommunication,
		Description:  "Post incident cards to Teams channels via Incoming Webhook connector. Rich adaptive card format.",
		AuthMethod:   models.AuthIncomingWebhook, Inbound: false, Outbound: true,
		TestStrategy: models.TestOutboundTeams, Popular: true,
		Tags: []string{"collaboration", "chat", "microsoft"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "webhook_url", Label: "Incoming Webhook URL", Type: "url", Required: true, Placeholder: "https://acme.webhook.office.com/...", HelpText: "Add an Incoming Webhook connector to your Teams channel."},
		},
		DocsHint: "In Teams: channel > Connectors > Incoming Webhook. Copy the URL and paste here.",
	},
	{
		ID: "pagerduty", Name: "PagerDuty", Category: models.CategoryCommunication,
		Description:  "Bidirectional PagerDuty integration: receive PagerDuty incident events and trigger PagerDuty incidents from NeuroOps.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/pagerduty",
		TestStrategy: models.TestInboundWebhook, Popular: true,
		Tags: []string{"on-call", "paging", "incident-response"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "webhook_secret", Label: "Webhook Secret", Type: "password", Required: false, Placeholder: "pd-webhook-secret", HelpText: "Optional: set in PagerDuty subscription config for HMAC verification."},
		},
		SamplePayload: `{"messages":[{"event":"incident.trigger","log_entries":[{"type":"notify_log_entry","created_at":"2024-01-15T10:00:00Z","agent":{"type":"service_reference","id":"P1ABC23"},"channel":{"type":"trigger"},"incident":{"id":"P1ABC2345","type":"incident","summary":"High error rate on api-service","self":"https://api.pagerduty.com/incidents/P1ABC2345","html_url":"https://acme.pagerduty.com/incidents/P1ABC2345","incident_number":12345,"title":"High error rate on api-service","created_at":"2024-01-15T10:00:00Z","status":"triggered","incident_key":"api-service-error-rate","service":{"id":"P9GH7I8","type":"service_reference","summary":"API Service","self":"https://api.pagerduty.com/services/P9GH7I8","html_url":"https://acme.pagerduty.com/services/P9GH7I8"},"urgency":"high","body":{"type":"incident_body","details":"Error rate exceeded 5%"}}}]}]}`,
		DocsHint: "Add a webhook subscription in PagerDuty service integrations pointing to the provided URL.",
	},
	{
		ID: "opsgenie", Name: "OpsGenie", Category: models.CategoryCommunication,
		Description:  "Receive OpsGenie alert webhooks and trigger OpsGenie alerts from NeuroOps incidents.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"on-call", "alerting", "atlassian"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"action":"Create","alert":{"alertId":"abc-def-123","alias":"api-service-high-error-rate","message":"High error rate on api-service","groupId":"","tags":["critical","production"],"tinyId":"1","entity":"api-service","source":"NeuroOps","message":"Error rate exceeded threshold","createdAt":1705313200000,"updatedAt":1705313200000,"username":"admin@acme.com","userId":"user-id","note":"","teams":["ops-team"],"actions":[],"responders":[],"integrationId":"integration-id","integrationName":"NeuroOps","status":"open","isSeen":false,"snoozed":false,"count":1,"lastOccurredAt":1705313200000,"priority":"P1"}}`,
		DocsHint: "Create a webhook integration in OpsGenie pointing to the provided URL.",
	},
	{
		ID: "victorops", Name: "Splunk On-Call (VictorOps)", Category: models.CategoryCommunication,
		Description:  "Send alerts to Splunk On-Call (formerly VictorOps) for on-call routing and escalation.",
		AuthMethod:   models.AuthAPIKey, Inbound: false, Outbound: true,
		TestStrategy: models.TestValidateConfig, Popular: false,
		Tags: []string{"on-call", "incident-response", "splunk"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "routing_key", Label: "Routing Key", Type: "password", Required: true, Placeholder: "victorops-routing-key"},
		},
		DocsHint: "Generate a REST endpoint in VictorOps Integrations settings. Use the routing key from the endpoint URL.",
	},
	{
		ID: "webex", Name: "Cisco Webex", Category: models.CategoryCommunication,
		Description:  "Post incident notifications to Webex spaces via incoming webhook or bot token.",
		AuthMethod:   models.AuthBearerToken, Inbound: false, Outbound: true,
		TestStrategy: models.TestValidateConfig, Popular: false,
		Tags: []string{"collaboration", "cisco", "chat"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "webhook_url", Label: "Webex Webhook URL", Type: "url", Required: true, Placeholder: "https://webexapis.com/v1/webhooks/..."},
		},
		DocsHint: "Create an incoming webhook in developer.webex.com for your target space.",
	},
	{
		ID: "discord", Name: "Discord", Category: models.CategoryCommunication,
		Description:  "Send incident alerts to Discord channels via webhook. Supports rich embed format with severity colours.",
		AuthMethod:   models.AuthIncomingWebhook, Inbound: false, Outbound: true,
		TestStrategy: models.TestValidateConfig, Popular: false,
		Tags: []string{"collaboration", "chat", "gaming"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "webhook_url", Label: "Discord Webhook URL", Type: "url", Required: true, Placeholder: "https://discord.com/api/webhooks/..."},
		},
		DocsHint: "Go to channel Settings > Integrations > Webhooks. Copy the webhook URL.",
	},
	{
		ID: "whatsapp", Name: "WhatsApp Business", Category: models.CategoryCommunication,
		Description:  "Send critical incident alerts via WhatsApp Business API to on-call engineers.",
		AuthMethod:   models.AuthAPIKey, Inbound: false, Outbound: true,
		TestStrategy: models.TestValidateConfig, Popular: false,
		Tags: []string{"mobile", "notifications", "meta"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "phone_number_id", Label: "Phone Number ID", Type: "text", Required: true, Placeholder: "1234567890"},
			{Name: "access_token", Label: "Access Token", Type: "password", Required: true, Placeholder: "EAA..."},
		},
		DocsHint: "Set up a WhatsApp Business Account in Meta for Developers. Use the phone number ID and access token.",
	},

	// ── CI/CD ─────────────────────────────────────────────────────────────────

	{
		ID: "github-actions", Name: "GitHub Actions", Category: models.CategoryCICD,
		Description:  "Receive GitHub Actions workflow failure events and deployment status webhooks to correlate deploy-related incidents.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/github",
		TestStrategy: models.TestInboundWebhook, Popular: true,
		Tags: []string{"github", "ci-cd", "deployment"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "webhook_secret", Label: "Webhook Secret", Type: "password", Required: false, Placeholder: "github-webhook-secret", HelpText: "Recommended: used to verify webhook signatures."},
		},
		SamplePayload: `{"action":"completed","workflow_run":{"id":12345,"name":"Deploy to Production","status":"completed","conclusion":"failure","workflow_id":678,"head_branch":"main","head_sha":"abc123def456","run_number":42,"event":"push","created_at":"2024-01-15T09:55:00Z","updated_at":"2024-01-15T10:00:00Z","html_url":"https://github.com/acme/api/actions/runs/12345","repository":{"id":1,"name":"api","full_name":"acme/api","private":true}},"repository":{"id":1,"name":"api","full_name":"acme/api"},"sender":{"login":"deploy-bot"}}`,
		DocsHint: "Add a webhook in GitHub repository Settings > Webhooks. Select workflow_run and deployment events.",
	},
	{
		ID: "gitlab-ci", Name: "GitLab CI/CD", Category: models.CategoryCICD,
		Description:  "Track GitLab CI pipeline failures and deployment events to correlate with production incidents.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/gitlab",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"gitlab", "ci-cd", "deployment"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "token", Label: "Webhook Token", Type: "password", Required: false, Placeholder: "gitlab-webhook-token", HelpText: "Set in GitLab webhook settings for verification."},
		},
		SamplePayload: `{"object_kind":"pipeline","object_attributes":{"id":12345,"ref":"main","tag":false,"sha":"abc123","before_sha":"def456","status":"failed","detailed_status":"failed","stages":["build","test","deploy"],"created_at":"2024-01-15 09:55:00 UTC","finished_at":"2024-01-15 10:00:00 UTC","duration":300,"queued_duration":10,"variables":[]},"builds":[{"id":98765,"stage":"deploy","name":"deploy-production","status":"failed","created_at":"2024-01-15 09:58:00 UTC","started_at":"2024-01-15 09:59:00 UTC","finished_at":"2024-01-15 10:00:00 UTC"}],"project":{"id":1,"name":"api-service","description":"","web_url":"https://gitlab.com/acme/api-service","git_http_url":"https://gitlab.com/acme/api-service.git","namespace":"acme"}}`,
		DocsHint: "Add a webhook in GitLab project Settings > Webhooks. Select Pipeline and Deployment events.",
	},
	{
		ID: "jenkins", Name: "Jenkins", Category: models.CategoryCICD,
		Description:  "Receive Jenkins build notifications via the Notification Plugin or Generic Webhook Trigger.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"ci-cd", "java", "self-hosted"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"name":"deploy-production","url":"job/deploy-production/","build":{"full_url":"http://jenkins.acme.com/job/deploy-production/42/","number":42,"queue_id":100,"timestamp":1705313000000,"phase":"COMPLETED","status":"FAILURE","url":"job/deploy-production/42/","scm":{"url":"https://github.com/acme/api","branch":"origin/main","commit":"abc123def456"},"artifacts":{"binary.jar":{"archive":"binary.jar"}},"log":"Deploy failed: cannot connect to database"}}`,
		DocsHint: "Install the Notification Plugin in Jenkins. Configure a job post-build action to notify this URL.",
	},
	{
		ID: "argocd", Name: "ArgoCD", Category: models.CategoryCICD,
		Description:  "Receive ArgoCD application sync events and health degradation alerts for GitOps-driven incidents.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"gitops", "kubernetes", "cncf"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"application":{"metadata":{"name":"checkout-api","namespace":"argocd"},"spec":{"source":{"repoURL":"https://github.com/acme/k8s-manifests","path":"apps/checkout-api","targetRevision":"main"},"destination":{"server":"https://kubernetes.default.svc","namespace":"production"}},"status":{"health":{"status":"Degraded"},"sync":{"status":"OutOfSync","revision":"abc123"},"operationState":{"phase":"Error","message":"Failed to create Deployment: timeout"}}},"context":{"envName":"production"}}`,
		DocsHint: "Configure ArgoCD notifications in argocd-notifications-cm ConfigMap pointing to this webhook.",
	},
	{
		ID: "terraform-cloud", Name: "Terraform Cloud", Category: models.CategoryCICD,
		Description:  "Receive Terraform Cloud run notifications for infrastructure change correlation with incidents.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"iac", "infrastructure", "hashicorp"},
		ConfigFields: []models.IntegrationConfigField{
			{Name: "hmac_key", Label: "HMAC Key", Type: "password", Required: false, Placeholder: "tfc-hmac-key", HelpText: "Used to verify webhook signatures from Terraform Cloud."},
		},
		SamplePayload: `{"payload_version":1,"notification_configuration_id":"nc-12345","run_url":"https://app.terraform.io/app/acme/workspaces/production/runs/run-abc123","run_id":"run-abc123","run_message":"Apply failed","run_created_at":"2024-01-15T09:55:00.000Z","run_created_by":"ci-pipeline","workspace_id":"ws-xyz789","workspace_name":"production","organization_name":"acme","notifications":[{"message":"Run errored","trigger":"run:errored","run_status":"errored","run_updated_at":"2024-01-15T10:00:00.000Z","run_updated_by":"terraform"}]}`,
		DocsHint: "Add a notification in Terraform Cloud workspace settings. Select run state change triggers.",
	},
	{
		ID: "ansible", Name: "Ansible / AWX", Category: models.CategoryCICD,
		Description:  "Receive Ansible AWX/Tower job completion notifications to correlate automation runs with incidents.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"automation", "configuration-management", "redhat"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"id":12345,"name":"Deploy Production","url":"https://awx.acme.com/#/jobs/playbook/12345","created_by":"ci-pipeline","started":"2024-01-15T09:55:00.308Z","finished":"2024-01-15T10:00:00.000Z","status":"failed","traceback":"","inventory":"production","project":"api-deployments","playbook":"deploy.yml","credential":"production-ssh","limit":"","extra_vars":"{}","hosts":{"api-server-01":{"failed":true,"changed":0,"dark":0,"failures":1,"ok":5,"processed":6,"skipped":0,"rescued":0,"ignored":0}}}`,
		DocsHint: "Configure Webhook notifications in AWX Job Template > Notifications section.",
	},

	// ── Cloud ─────────────────────────────────────────────────────────────────

	{
		ID: "aws-ec2", Name: "AWS EC2", Category: models.CategoryCloud,
		Description:  "Receive EC2 instance state change and health check failure events via CloudWatch + SNS.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"aws", "compute", "infrastructure"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"source":"aws.ec2","detail-type":"EC2 Instance State-change Notification","detail":{"instance-id":"i-1234567890abcdef0","state":"terminated"},"resources":["arn:aws:ec2:us-east-1:123456789012:instance/i-1234567890abcdef0"],"region":"us-east-1","account":"123456789012","time":"2024-01-15T10:00:00Z"}`,
		DocsHint: "Create an EventBridge rule matching EC2 events, target an SNS topic, subscribe HTTP to this URL.",
	},
	{
		ID: "aws-ecs", Name: "AWS ECS", Category: models.CategoryCloud,
		Description:  "Monitor ECS task and service events — catch container crashes, service degradation, and deployment failures.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"aws", "containers", "fargate"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"source":"aws.ecs","detail-type":"ECS Task State Change","detail":{"taskArn":"arn:aws:ecs:us-east-1:123456789012:task/cluster/abc123","clusterArn":"arn:aws:ecs:us-east-1:123456789012:cluster/production","lastStatus":"STOPPED","desiredStatus":"STOPPED","stoppedReason":"Essential container in task exited","containers":[{"name":"api","exitCode":1,"reason":"Error: Cannot connect to database"}],"group":"service:checkout-api","launchType":"FARGATE"},"region":"us-east-1","time":"2024-01-15T10:00:00Z"}`,
		DocsHint: "Configure EventBridge rule for ECS Task State Change events, publish to SNS, subscribe to this URL.",
	},
	{
		ID: "aws-rds", Name: "AWS RDS", Category: models.CategoryCloud,
		Description:  "Receive RDS event notifications for instance failures, storage alerts, and maintenance windows.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"aws", "database", "aurora"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"Event Source":"db-instance","Event Time":"2024-01-15 10:00:00.0","Identifier Link":"https://console.aws.amazon.com/rds/home?region=us-east-1#dbinstances:id=production-postgres","Source ID":"production-postgres","Event ID":"http://docs.amazonwebservices.com/AmazonRDS/latest/UserGuide/USER_Events.html#RDS-EVENT-0006","Event Message":"DB instance restarted","Subscription Name":"rds-events-neuroops"}`,
		DocsHint: "Create an RDS event subscription in the console, set the SNS topic with HTTP subscription.",
	},
	{
		ID: "aws-lambda", Name: "AWS Lambda", Category: models.CategoryCloud,
		Description:  "Capture Lambda function errors and throttling events via CloudWatch Alarms or Lambda Destinations.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"aws", "serverless", "functions"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"source":"aws.cloudwatch","detail-type":"CloudWatch Alarm State Change","detail":{"alarmName":"checkout-lambda-errors","state":{"value":"ALARM","reason":"Threshold Crossed: 1 datapoint (15) was greater than the threshold (0).","timestamp":"2024-01-15T10:00:00.000+0000"},"previousState":{"value":"OK"},"configuration":{"description":"Lambda error rate alarm","metrics":[{"id":"m1","metricStat":{"metric":{"namespace":"AWS/Lambda","name":"Errors","dimensions":{"FunctionName":"checkout-processor"}},"period":300,"stat":"Sum"}}]}},"region":"us-east-1"}`,
		DocsHint: "Create CloudWatch alarms on Lambda error metrics, trigger SNS, subscribe to this URL.",
	},
	{
		ID: "aws-sqs", Name: "AWS SQS", Category: models.CategoryCloud,
		Description:  "Monitor SQS queue depth and DLQ notifications to detect message processing failures.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"aws", "messaging", "queues"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"source":"aws.cloudwatch","detail-type":"CloudWatch Alarm State Change","detail":{"alarmName":"checkout-dlq-depth","state":{"value":"ALARM","reason":"Threshold Crossed: 1 datapoint (100) was greater than the threshold (10)."},"configuration":{"description":"DLQ depth alarm","metrics":[{"metricStat":{"metric":{"namespace":"AWS/SQS","name":"ApproximateNumberOfMessagesVisible","dimensions":{"QueueName":"checkout-dlq"}},"period":60,"stat":"Maximum"}}]}},"region":"us-east-1"}`,
		DocsHint: "Create a CloudWatch alarm on the DLQ's ApproximateNumberOfMessagesVisible metric.",
	},
	{
		ID: "aws-cloudtrail", Name: "AWS CloudTrail", Category: models.CategoryCloud,
		Description:  "Receive CloudTrail events for security-relevant API calls via EventBridge. Detect unauthorized access and config changes.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"aws", "security", "compliance", "audit"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"source":"aws.cloudtrail","detail-type":"AWS API Call via CloudTrail","detail":{"eventSource":"ec2.amazonaws.com","eventName":"TerminateInstances","awsRegion":"us-east-1","sourceIPAddress":"203.0.113.50","userIdentity":{"type":"AssumedRole","arn":"arn:aws:sts::123456789012:assumed-role/admin/cli-session"},"requestParameters":{"instancesSet":{"items":[{"instanceId":"i-1234567890abcdef0"}]}},"errorCode":"","errorMessage":""},"region":"us-east-1","time":"2024-01-15T10:00:00Z"}`,
		DocsHint: "Create an EventBridge rule matching CloudTrail API calls, route to SNS, subscribe to this URL.",
	},
	{
		ID: "azure-events", Name: "Azure Event Grid", Category: models.CategoryCloud,
		Description:  "Receive Azure Resource Manager events, service health alerts, and security center findings.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"azure", "events", "infrastructure"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `[{"id":"abc-12345","eventType":"Microsoft.Resources.ResourceActionSuccess","subject":"/subscriptions/sub-id/resourceGroups/production/providers/Microsoft.Compute/virtualMachines/api-vm-01","eventTime":"2024-01-15T10:00:00Z","data":{"operationName":"Microsoft.Compute/virtualMachines/delete","status":"Succeeded","resourceGroup":"production","resourceProvider":"Microsoft.Compute","resourceUri":"/subscriptions/sub-id/resourceGroups/production/providers/Microsoft.Compute/virtualMachines/api-vm-01"},"dataVersion":"2.0","metadataVersion":"1"}]`,
		DocsHint: "Create an Event Grid subscription with WebHook endpoint type pointing to this URL.",
	},
	{
		ID: "gcp-pubsub", Name: "GCP Pub/Sub Push", Category: models.CategoryCloud,
		Description:  "Receive Google Cloud audit logs, VPC flow logs, and security findings via Pub/Sub push subscriptions.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"gcp", "pubsub", "security"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"message":{"attributes":{"logging.googleapis.com/timestamp":"2024-01-15T10:00:00Z"},"data":"eyJwcm90b1BheWxvYWQiOnsibWV0aG9kTmFtZSI6Imdvb2dsZS5jb21wdXRlLnYxLkluc3RhbmNlc0RlbGV0ZSIsInN0YXR1cyI6eyJjb2RlIjowfX0sInJlc291cmNlIjp7InR5cGUiOiJnY2VfaW5zdGFuY2UiLCJsYWJlbHMiOnsiaW5zdGFuY2VfaWQiOiIxMjM0NTY3ODkwIiwicHJvamVjdF9pZCI6Im15LXByb2plY3QiLCJ6b25lIjoidXMtY2VudHJhbDEtYSJ9fX0=","messageId":"abc123","publishTime":"2024-01-15T10:00:00Z"},"subscription":"projects/my-project/subscriptions/neuroops-push"}`,
		DocsHint: "Create a Pub/Sub push subscription with the webhook URL as the endpoint. Configure IAM for the push subscriber.",
	},
	{
		ID: "oci-events", Name: "Oracle Cloud (OCI)", Category: models.CategoryCloud,
		Description:  "Receive OCI Events service notifications and monitoring alarms for Oracle Cloud workloads.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"oci", "oracle", "cloud"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"cloudEventsVersion":"0.1","eventID":"unique-event-id","eventType":"com.oraclecloud.monitoring.alarm.statechange","source":"monitoring","eventTime":"2024-01-15T10:00:00Z","contentType":"application/json","data":{"compartmentId":"ocid1.compartment.oc1..abc","compartmentName":"Production","resourceName":"api-server-alarm","resourceId":"ocid1.alarm.oc1..xyz","availabilityDomain":"AD-1","namespace":"oci_computeagent","query":"CpuUtilization[5m].mean() > 80","reason":"FIRING","severity":"CRITICAL","timestamp":"2024-01-15T10:00:00Z"}}`,
		DocsHint: "Create an OCI Events rule or Monitoring alarm notification with HTTPS action pointing to this URL.",
	},
	{
		ID: "kubernetes", Name: "Kubernetes Events", Category: models.CategoryCloud,
		Description:  "Stream Kubernetes warning events and pod crash events via the NeuroOps agent or a custom event exporter.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: true,
		Tags: []string{"kubernetes", "containers", "cncf"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"type":"Warning","reason":"BackOff","message":"Back-off restarting failed container checkout-api in pod checkout-api-7d4b9f-x8k2p_production(abc-def-ghi)","metadata":{"name":"checkout-api-7d4b9f-x8k2p.123456","namespace":"production","creationTimestamp":"2024-01-15T10:00:00Z"},"involvedObject":{"kind":"Pod","namespace":"production","name":"checkout-api-7d4b9f-x8k2p","uid":"pod-uid","apiVersion":"v1","resourceVersion":"12345","fieldPath":"spec.containers{checkout-api}"},"source":{"component":"kubelet","host":"node-01"},"firstTime":"2024-01-15T09:55:00Z","lastTimestamp":"2024-01-15T10:00:00Z","count":15}`,
		DocsHint: "Install the NeuroOps agent in your cluster, or deploy kubewatch/event-exporter pointing to this webhook.",
	},

	// ── APM & Tracing ─────────────────────────────────────────────────────────

	{
		ID: "elastic-apm", Name: "Elastic APM", Category: models.CategoryAPM,
		Description:  "Receive Elastic Watcher alerts from APM anomaly detection and error threshold rules.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"elastic", "apm", "tracing"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"id":"watcher-alert-12345","type":"PercentageOfErrors","severity":"error","message":"Error rate exceeded 5% for checkout-service","timestamp":"2024-01-15T10:00:00.000Z","rule":{"id":"checkout-error-rate","name":"Checkout Error Rate"},"params":{"threshold":5,"window":"5m","service":"checkout-service","environment":"production"},"fields":{"service.name":"checkout-service","service.environment":"production","transaction.type":"request"}}`,
		DocsHint: "Configure Elastic Watcher actions to call the HTTP webhook with your alert context.",
	},
	{
		ID: "honeycomb", Name: "Honeycomb", Category: models.CategoryAPM,
		Description:  "Receive Honeycomb trigger notifications for SLO burn rate and query threshold violations.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"observability", "tracing", "distributed-systems"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"version":"v0.1.0","id":"trigger-abc123","type":"trigger","name":"High Latency Alert","trigger":{"id":"abc123","name":"High Latency","description":"p99 latency > 500ms","dataset":"api-service","query":{"calculations":[{"op":"P99","column":"duration_ms"}],"filters":[{"column":"service.name","op":"=","value":"checkout"}],"time_range":300},"threshold":{"op":">","value":500},"frequency":60,"alert_type":"on_change"},"status":"triggered","summary":"p99 latency is 780ms (threshold: 500ms)","trace_link":"https://ui.honeycomb.io/acme/datasets/api-service","start_time":1705313200,"end_time":null}`,
		DocsHint: "Configure a Trigger recipient of type Webhook in your Honeycomb dataset trigger settings.",
	},
	{
		ID: "lightstep", Name: "ServiceNow Lightstep", Category: models.CategoryAPM,
		Description:  "Receive Lightstep alert notifications for latency regressions and error budget burn.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"apm", "distributed-tracing", "slo"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"alert":{"id":"alert-12345","title":"High Latency on checkout-service","condition":{"type":"latency","threshold_ms":500,"percentile":99},"status":"active","triggered_at":"2024-01-15T10:00:00Z","service":"checkout-service","environment":"production","metric_value":780,"threshold":500}}`,
		DocsHint: "Add a webhook notification destination in Lightstep alert rule destinations.",
	},
	{
		ID: "jaeger", Name: "Jaeger", Category: models.CategoryAPM,
		Description:  "Export Jaeger trace sampling results and span error summaries for incident correlation.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"tracing", "cncf", "open-source"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"service":"checkout-api","operation":"POST /checkout","error_rate":0.08,"p99_latency_ms":1200,"sample_traces":[{"trace_id":"abc123","span_id":"def456","operation":"POST /checkout","duration_ms":1200,"error":true,"error_message":"database connection timeout","tags":{"db.type":"postgresql","db.statement":"SELECT * FROM orders"}}],"window":"5m","timestamp":"2024-01-15T10:00:00Z"}`,
		DocsHint: "Use a custom Jaeger exporter or SPM (Service Performance Monitoring) to push summaries.",
	},

	// ── Log Management ────────────────────────────────────────────────────────

	{
		ID: "elastic-kibana", Name: "Elastic / Kibana", Category: models.CategoryLogging,
		Description:  "Route Kibana Alerting rule notifications and Elastic SIEM detection alerts via webhook action.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: true,
		Tags: []string{"elastic", "logs", "siem"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"rule":{"id":"abc123","name":"High Error Rate","tags":["production","api"]},"context":{"message":"Error rate for api-service exceeded 5%","title":"[Alerting] High Error Rate on api-service","alertActionGroup":"default","alertId":"alert-abc123","alertInstanceId":"checkout-api","date":"2024-01-15T10:00:00.000Z","value":8.3,"threshold":5,"conditions":[{"type":"threshold","comparator":">","threshold":[5],"timeWindowSize":5,"timeWindowUnit":"m","aggType":"avg","field":"error_rate","index":["logs-*"]}]},"rule":{"name":"High Error Rate","rule_type_id":".index-threshold","space_id":"default","id":"abc123"},"kibanaBaseUrl":"http://kibana.acme.com"}`,
		DocsHint: "Create a Kibana Alerting rule. Add a Webhook action connector pointing to this URL.",
	},
	{
		ID: "splunk", Name: "Splunk", Category: models.CategoryLogging,
		Description:  "Receive Splunk alert actions from Enterprise Security and ITSI for log-based incident creation.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"logs", "siem", "enterprise"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"sid":"scheduler__admin__search__RMD5abc123456__at_1705313200_0","search_name":"High Error Rate Alert","app":"search","owner":"admin","results_link":"http://splunk.acme.com/app/search/search?q=search%20index%3Dmain%20error_rate%3E0.05","trigger":{"type":"number of events","activated":true,"threshold":1},"result":{"sourcetype":"access_combined","count":"25","error_rate":"0.083","_time":"2024-01-15 10:00:00","service":"checkout-api","host":"api-server-01"},"fields":[{"name":"service","value":"checkout-api"},{"name":"error_rate","value":"0.083"}]}`,
		DocsHint: "Create a Splunk alert action of type 'Webhook', set the URL, and configure field mapping.",
	},
	{
		ID: "grafana-loki", Name: "Grafana Loki", Category: models.CategoryLogging,
		Description:  "Receive Loki alerting rule (LogQL-based) notifications via Grafana unified alerting webhook.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"logs", "grafana", "loki"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"receiver":"neuroops-webhook","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"HighErrorLogs","service":"checkout-api","severity":"critical","job":"api-logs"},"annotations":{"summary":"High error log rate","description":"More than 100 error logs per minute"},"startsAt":"2024-01-15T10:00:00Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://grafana/alerting/abc123","fingerprint":"abc123def456"}],"groupLabels":{"alertname":"HighErrorLogs"},"commonLabels":{"alertname":"HighErrorLogs","service":"checkout-api"},"commonAnnotations":{"summary":"High error log rate"}}`,
		DocsHint: "Configure Loki alerting rules in Grafana and add a Webhook contact point for this URL.",
	},
	{
		ID: "sumologic", Name: "Sumo Logic", Category: models.CategoryLogging,
		Description:  "Receive Sumo Logic scheduled search and monitor alerts for centralized log-based incident detection.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"logs", "cloud-siem", "analytics"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"numRawResults":25,"fields":[{"name":"service","fieldType":"string","keyField":true},{"name":"count","fieldType":"long","keyField":false}],"results":[{"service":"checkout-api","count":"25"}],"searchName":"High Error Rate Monitor","timeRange":{"from":1705312900000,"to":1705313200000},"sourceUrl":"https://service.sumologic.com/ui/dashboard.html","triggerTimeStart":1705313200000,"triggerTimeEnd":1705313200000,"alertName":"High Error Rate on checkout-api","alertStatus":"Critical"}`,
		DocsHint: "Create a Webhook connection in Sumo Logic (Manage > Connections > Add Webhook).",
	},

	// ── Security ──────────────────────────────────────────────────────────────

	{
		ID: "wiz", Name: "Wiz", Category: models.CategorySecurity,
		Description:  "Receive Wiz cloud security findings, misconfigurations, and vulnerability alerts for security-incident correlation.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"security", "cspm", "cloud"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"id":"issue-abc123","type":"MISCONFIGURATION","status":"OPEN","severity":"CRITICAL","title":"Public S3 bucket with sensitive data","createdAt":"2024-01-15T10:00:00Z","updatedAt":"2024-01-15T10:00:00Z","entity":{"id":"arn:aws:s3:::acme-customer-data","type":"BUCKET","name":"acme-customer-data","cloudProvider":"AWS","cloudRegion":"us-east-1"},"note":"S3 bucket acme-customer-data is publicly accessible and contains customer PII","remediation":"Enable block public access settings on the S3 bucket"}`,
		DocsHint: "Configure a Webhook automation trigger in Wiz Settings > Automation > Webhooks.",
	},
	{
		ID: "snyk", Name: "Snyk", Category: models.CategorySecurity,
		Description:  "Receive Snyk vulnerability scan results and new CVE notifications for dependency-related incidents.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"security", "vulnerabilities", "sca"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"project":{"id":"abc-123","name":"acme/checkout-api","origin":"github","type":"npm","readOnly":false,"testFrequency":"daily","totalDependencies":145,"issueCountsBySeverity":{"critical":1,"high":3,"medium":12,"low":8},"imageTag":""},"org":{"id":"org-abc","name":"acme"},"newIssues":[{"id":"SNYK-JS-LODASH-1040724","url":"https://snyk.io/vuln/SNYK-JS-LODASH-1040724","title":"Prototype Pollution","type":"vuln","packageName":"lodash","version":"4.17.19","severity":"high","cvssScore":7.4,"exploitMaturity":"proof-of-concept"}],"removedIssues":[],"delta":{"removedIssues":0,"newIssues":1}}`,
		DocsHint: "Create a Snyk webhook in Organization Settings > Integrations > Webhooks.",
	},
	{
		ID: "lacework", Name: "Lacework", Category: models.CategorySecurity,
		Description:  "Forward Lacework behavioral anomaly alerts, compliance violations, and cloud activity detections.",
		AuthMethod:   models.AuthWebhook, Inbound: true, Outbound: false,
		WebhookPath:  "/api/v1/ingest/webhook",
		TestStrategy: models.TestInboundWebhook, Popular: false,
		Tags: []string{"security", "cloud-security", "behavioral"},
		ConfigFields: []models.IntegrationConfigField{},
		SamplePayload: `{"START_TIME":"2024-01-15T09:55:00Z","END_TIME":"2024-01-15T10:00:00Z","EVENT_CATEGORY":"Anomaly","EVENT_TYPE":"NewExternalServerDns","SEVERITY":3,"ACCOUNT":"acme-prod","STATUS":"OPEN","REC_ID":"REC-12345","SUMMARY":"New connection to external DNS server detected from container checkout-api","ENTITY_MAP":{"Machine":[{"MID":123,"HOSTNAME":"checkout-api-7d4b9f-x8k2p","EXTERNAL_IP":"203.0.113.50","INTERNAL_IP":"10.0.0.5"}]}}`,
		DocsHint: "Add a Webhook alert channel in Lacework Settings > Alert Channels > Add New.",
	},
}

// catalogByID provides O(1) lookup. Built once at package init.
var catalogByID map[string]*models.IntegrationEntry

func init() {
	catalogByID = make(map[string]*models.IntegrationEntry, len(integrationCatalog))
	for i := range integrationCatalog {
		catalogByID[integrationCatalog[i].ID] = &integrationCatalog[i]
	}
}

// getCatalogEntry returns the catalog entry for the given ID, or nil.
func getCatalogEntry(id string) (*models.IntegrationEntry, bool) {
	e, ok := catalogByID[id]
	return e, ok
}

// allCatalogEntries returns a copy of the full catalog slice.
func allCatalogEntries() []models.IntegrationEntry {
	return integrationCatalog
}
